### ISSUE TITLE
Support current time & date in RVD

### ISSUE THREAD

**Issue by otsakir** [RestComm/Restcomm-Connect#1034]
RVD is missing a way to get the currrent day and time. We could add new macro command syntax or provide additional $core_ variables to add this feature.

**Comment by gvagenas** [comment]
closed by commit https://github.com/RestComm/Restcomm-Connect/commit/f68d1d9692225e59b5e4080d978fc62c4574089e

**Comment by otsakir** [comment]
@antonmry, you patch has  been reviewed and merged to master. Thanks for the contribution!
