### ISSUE TITLE
Review the concept of Application entity uniqueness

### ISSUE THREAD

**Issue by ghjansen** [RestComm/Restcomm-Connect#1040]
As an extension of the discussion started on **#restcomm-connect** channel, I'm opening this issue to elaborate on arguments regarded to the way we intend to keep the uniqueness of Application entities.

Give the proper handling for uniqueness may depends on being aware of the chronology in which some relevant changes occurred. The following try to describe this timeline up to now.

--------------

**1. Project era** (past)
* **1.1 Management dependency**: RVD was managing projects based on his own workspace only, there was no dependency on different parts;
* **1.2 Workspace naming convention**: RVD was applying the name chosen for the project as the name of the folder created for it, inside the workspace (example: `workspace/test/`);
* **1.3 Usage**: RVD Projects were used by RestComm IncomingPhoneNumbers and Clients by configuring them with a URL, this URL is used by RestComm Interpreters to get the RCML of the project;
* **1.4 Uniqueness**: RVD was using only his own workspace to consist project uniqueness. The name of the project was the attribute that defined a project as unique, thereby the verification relied on the case sensitiveness used by the filesystem of the server (example: Linux filesystem is case sensitive).

**2. Migration era** (present)
* **2.1 Management dependency**: RVD was slowly replicating the actions for local projects through  RestComm Applications REST API, linking with Application entities by project name;
* **2.2 Workspace naming convention**: RVD remained using the name of the projects as the name of its folders until the workspace migration executed at RestComm's bootstrap, that renamed each project folder in the workspace to a applicationSid, generated by a Application entity that represents this project.
* **2.3 Usage**: RVD Projects remained used through URL by RestComm IncomingPhoneNumbers and Clients until the workspace migration executed at RestComm's bootstrap, that replaced the usage of URL by the applicationSid of this project.
* **2.4 Uniqueness**: Both RVD and RestComm still using the project's name (or Application friendly name) as case sensitive to define uniqueness. Once this was a previous approach, the migration algorithm placed at RestComm's bootstrap relies on this assumption to be able to at least transport the current state of the workspace to the database, creating all the projects as Application entities.

**3. Application era** (present+future)
* **3.1 Management dependency**: RVD depends on RestComm Applications API to manage its projects (only CRUD operations at entity level, not the logic inside the project).
* **3.2 Workspace naming convention**: RVD uses the applicationSid as name of the folders created to each project inside the workspace.
* **3.3 Usage**: RVD Projects can be assigned to RestComm IncomingPhoneNumbers or Clients through a URL or Application (using a applicationSid).
* **3.4 Uniqueness**: RestComm Application Endpoint controls the uniqueness at Application entity level, using the "friendly_name" attribute as case sensitive.

--------------

With that, its important to notice that it won't be wise to change the concept of uniqueness until we pass the Migration era (until all environments are successfully migrated) once the migration relies on this uniqueness style to bind projects with Applications, but after that i think its all green.

So, the three more evident choices seems to be:
**A**. uniqueness based on case sensitive (example of two different applications: appgui, appGui);
**B**. uniqueness based on case insensitive (example of two different applications: appgui, appgui1);
**C**. uniqueness based on applicationSid (example of two different applications: appgui, appgui).

As mentioned before, option **A** represents the current state. At last but not least, its interesting to bring RAS in the mix, since some sort of uniqueness have to be used there as well, in the same or different way on which RestComm does.

@otsakir @gvagenas @deruelle thoughts?

**Comment by otsakir** [comment]
IMO we should move with plan C. It looks much more concrete. There is not much more to lose either.
* Keeping FriendlyName uniqueness for supporting old DIDs with URLs like /link/to/rvd/application/FriendlyName/controller to projects that failed migration is not an argument. Support for such URLs is already removed from RVD.
* It proves that complex implementations that look after near-obsolete features do not always reach their goal. I consider A and B more complex. We've already missed checking for application import that compromise uniqueness. Also, they are based on DB of FS case sensitivity. Finally, uniqueness which is not enforced on the DB layer but rather through first-read-and-then-store fashion which is not atomic. So, it's still kind of fuzzy.

**Comment by deruelle** [comment]
Agreed with @otsakir Plan C looks the best option. using a random UUID to provide the uniqueness is more correct. If it happens to be simpler to implement even better

**Comment by otsakir** [comment]
Solution C was adopted.
