### ISSUE TITLE
Block sip scanners

### ISSUE THREAD

**Issue by gvagenas** [RestComm/Restcomm-Connect#1050]
Add the following to mss-sip-stack.properties

org.mobicents.ext.javax.sip.congestion.SIP_SCANNERS=sipvicious,sipcli,friendly-scanner,VaxSIPUserAgent

**Comment by deruelle** [comment]
Enabled gov.nist.javax.sip.SIP_MESSAGE_VALVE=org.mobicents.ext.javax.sip.congestion.CongestionControlMessageValve as well.
