### ISSUE TITLE
Convert Olympus Doc to Asciidoc

### ISSUE THREAD

**Issue by deruelle** [RestComm/Restcomm-Connect#1064]
Convert http://docs.telestax.com/how-to-use-olympus-with-restcomm/ to asciidoc and improve it

**Comment by malihanaveed** [comment]
[How to use olympus with restcomm.pdf](https://github.com/RestComm/Restcomm-Connect/files/264948/How.to.use.olympus.with.restcomm.pdf)

**Comment by malihanaveed** [comment]
Hi @deruelle I have created a pull request for this issue: https://github.com/RestComm/Restcomm-Connect/pull/1072. Please have a look and let me know how to improve. Thanks

**Comment by deruelle** [comment]
Thanks @malihanaveed 
I'll try to make a review this week.

**Comment by deruelle** [comment]
thanks @malihanaveed I added my comments on the pull request for your review.

**Comment by ammendonca** [comment]
This has been done, as per https://github.com/RestComm/Restcomm-Connect/pull/1072#issuecomment-222134538.
