### ISSUE TITLE
Need to add a reset password feature at AdminUI. 

### ISSUE THREAD

**Issue by leftyb** [RestComm/Restcomm-Connect#1069]
We need to examine a proper feature for users to ask for new password in case of lose, forgetting etc.
Maybe an email should be send to the administrator of the account.
Or we should brainstorm for some other way.

**Comment by deruelle** [comment]
Done through an external service for now but can be done through the REST API "Change default account password(AuthToken)" Section of http://documentation.telestax.com/connect/api/account-api.html#account and done as part of https://github.com/RestComm/Restcomm-Connect/issues/1398
