### ISSUE TITLE
ConferenceState COMPLETED is not captured in VoiceInterpreter

### ISSUE THREAD

**Issue by maria-farooq** [RestComm/Restcomm-Connect#1070]
In scope of VoiceInrepreter conferenceState **completed** is not captured, which is why actions based on this state do not get executed.
impact:
- ConferenceStateChanged.State.COMPLETED is not caught which is why conference remain in old state.
- VoiceInterpreter wont know that conference is completed so it wont call DestroyConference and thus there is chance that some resources don't get cleaned up

**Comment by gvagenas** [comment]
Closed with merge of PR https://github.com/RestComm/Restcomm-Connect/pull/1071
