### ISSUE TITLE
Calls that are conference participants never get disconnected when Conference finish and there is no RCML tag to be executed

### ISSUE THREAD

**Issue by gvagenas** [RestComm/Restcomm-Connect#1081]
The RCML could be like this,
```<Response><Dial><Conference timeLimit="50">myConfRoom1234</Conference></Dial></Response>```

This means that after 50 seconds, Conference will stop and will remove participants (Call actors). 
Problem is that Call actors move to Completed state, then are removed and destroyed (so we free memory) but we never send Bye request to them so sip client stays on call.

**Comment by maria-farooq** [comment]
Got it @gvagenas 
Let me reproduce it. which will give me more clear view of this issue and how its related to #1071

**Comment by gvagenas** [comment]
@maria-farooq thanks for checking this. Check the RCML again in the first comment because the first time it wasn't properly formated

**Comment by maria-farooq** [comment]
Conference Application i created from RVD: it looks like:
```xml
<Response>
    <Dial timeLimit="50">
        <Conference>myConfRoom1234</Conference>
    </Dial>
</Response>
```
We want **timeLimit** for **Conference** not for **Dial**
any clues how can i do this with or without RVD

**Comment by deruelle** [comment]
Linked to https://github.com/RestComm/Restcomm-Connect/issues/1097
