### ISSUE TITLE
Migrate http://docs.telestax.com/restcomm-docker-quick-start-guide/ to asciidoc

### ISSUE THREAD

**Issue by deruelle** [RestComm/Restcomm-Connect#1086]

**Comment by gsaslis** [comment]
@deruelle looks like this is already done?

https://github.com/RestComm/Restcomm-Connect/blob/master/restcomm/restcomm.docs/sources-asciidoc/src/main/asciidoc/configuration/docker/Restcomm%20-%20Docker%20Quick%20Start%20Guide.adoc

**Comment by deruelle** [comment]
yes thanks @gsaslis
