### ISSUE TITLE
Adapt SIP Clients for Organizations concept compliance

### ISSUE THREAD

**Issue by ghjansen** [RestComm/Restcomm-Connect#1094]
This issue is an extension of issues #748 and #784.

As discussed in #784 , SIP Clients must have a unique friendly name at Organization level, so **Organization Foo** can have a SIP Client named **alice** just like **Organization Bar** can have a different SIP Client with the same friendly name **alice**.

By the time that RestComm receives a call, the domain present in the SIP URI must be used to identify the Organization and lookup for the Client inside the Organization scope.

**Call 1**: `sip:alice@foo.com`
**Call 2**: `sip:alice@bar.com`

This way, even if the SIP Client friendly name is the same, the domain in the SIP URI will points to RestComm which is the right **alice** to call.

REGISTRARLESS over IP will not be supported for now.

**Comment by ghjansen** [comment]
@deruelle @gvagenas @otsakir while testing my modifications for this issue i hit a blocker that i think requires some depth analysis before move on, that i reported in #1107.

In a nutshell, `Registration` entity needs to be adjusted to consider the Organization scope just like i did in this issue for `Client` entity. During a call, `MybatisClientsDao` is now providing a unique `Client` based on a informed `organizationSid`, so its possible to find the right `Client` during the workflow in Voice/SMS interpreters. But apart from that, the registration process is not Organization compliant and is not able yet to operate with `Clients` that have the same name.

Apart from my efforts trying to find a solution for that (like including a `organizationSid` to the `Registration` entity, or make use of the `Registration.addressOfRecord` that holds the namespace of the Organization), i know this is a critical area that requires careful attention to not mess up with Interpreters life cycle or FSM consistency, so i'm raising the red flag. 

We can discuss this better tomorrow if may be difficult to understand from my explanations (I'm rushing to finish sth @ university also). I created the branch `Issue1094_SIPOrganization` based on `Issue748_Organization` to keep my changes about the `Client` uniqueness (27c12e3d2a606ddd53ad3f69defc4813cf8bdedf) and also to better manage problems.

**Comment by deruelle** [comment]
@ghjansen do you want to organize a quick call on that topic so we can move forward ?

**Comment by ghjansen** [comment]
yes @deruelle after the daily conference call fits in your agenda?

**Comment by deruelle** [comment]
No I have conflicts today. Let's sync up on slack

**Comment by ghjansen** [comment]
@deruelle after a constructive discussion with @gvagenas and @otsakir we agreed to go ahead using `Registration.addressOfRecord` to locate the correct registration for the particular `Client` and `Organization`. So i will move forward with the respective adjustments to finish it today.

**Comment by deruelle** [comment]
great. thanks guys !

**Comment by ghjansen** [comment]
Will be finished when #1107 is finished also.

**Comment by ghjansen** [comment]
@maria-farooq could you confirm that this issue can be closed?
