### ISSUE TITLE
Display role information in AdminUI

### ISSUE THREAD

**Issue by otsakir** [RestComm/Restcomm-Connect#1103]
One can't tell what role an account is assigned to. Should we add this piece of information in the form ?

**Comment by deruelle** [comment]
Yes

**Comment by otsakir** [comment]
depends on #1105

**Comment by muhammadbilal19** [comment]
@otsakir @deruelle  i don't know whether anyone is working on this issue or not i add role value in Account response and shows it on AdminUI .My branch location is 
https://github.com/muhammadbilal19/Restcomm-Connect/tree/Issue-1105

if you want i can give it to you for review.

I didn't ask before fixing i just see and implement it.

**Comment by deruelle** [comment]
@muhammadbilal19 do you want to do a pull request on this so that @otsakir can review ?

**Comment by muhammadbilal19** [comment]
Pull request created for this change.
https://github.com/RestComm/Restcomm-Connect/pull/1109

**Comment by deruelle** [comment]
great @otsakir can you review ?

**Comment by otsakir** [comment]
Thanks for the contribution @muhammadbilal19. I'll review your PR and get back to you.

**Comment by otsakir** [comment]
@muhammadbilal19, your patch has been merged.

**Comment by muhammadbilal19** [comment]
Thanks @otsakir for confirming. I just see that i miss the xml response part which you fix thanks for that.

**Comment by otsakir** [comment]
np @muhammadbilal19. email_address field was also wrong so it seems that you were unlucky enough to pick the wrong reference :-).

**Comment by muhammadbilal19** [comment]
:) yup anyways one extra issue is resolved along with this so it is good that i choose that one as a reference.
