### ISSUE TITLE
Allow Cascading Conferences

### ISSUE THREAD

**Issue by deruelle** [RestComm/Restcomm-Connect#1104]
Ideally to run better in a distributed cluster environment, a conference should record which master media server was selected to start the conference.  Potentially it can record slaves as well when https://docs.google.com/drawings/d/1J7FGvMU5gBfmf3_WGjOZy2Njh50Isjob6CJGYvbVIRw/edit?usp=sharing is implemented
#932 is a requirement before this can be implemented.

**Comment by maria-farooq** [comment]
As suggested by @hrosa 
it would be simpler if the task was delegated to a single MRB.
As it will cleaner approach to have resource management by MRB. an example:
(https://www.dialogic.com/~/media/products/docs/media-server-software/14160-powermediamrb-ds.pdf)

**Comment by deruelle** [comment]
@maria-farooq @hrosa please share you sequence flow diagrams as discussed offline so we decide on the best course of action

**Comment by maria-farooq** [comment]
@deruelle will update in an hour here
thanks

**Comment by maria-farooq** [comment]
Possible sequence for #1154 : https://www.draw.io/#G0B2CFlEFeY-zfZnNDUG9hdHh1RWs
Possible sequence for #1104 : ?
Possible sequence for MRB : ?

**Comment by deruelle** [comment]
@maria-farooq I can't access the sequence diagram, Let's use plantuml as it can be integrated with asciidoc easily.

**Comment by maria-farooq** [comment]
http://www.plantuml.com/plantuml/svg/lLZRRkCs47ttLyn3qSP0iexP0biOzIA1amB68bdNSM-0NsYASjbAf4lAReqq_zuX9KkKTR6SJPk789Q6SpcSENCSoXAbOKPr8fZOK9aCU_Ju4Udvx-7g0yovIPYAun4OiHcOO0CJ6aN3tk4vN5rzyCyuEnXUNmyMUY_asZD4PmzFQ12l6NgPJtuPBUNpJ8kOwZq-LIl1k4pCOAL5iEQ3BswSEVc6VBkKXZCb0pJqxCHE-qOlFVjdEMSNwcdB63V6Hgi46NO9CYm5gQ_duSxLqtWGWrlWfdUZuILW6CbP8fHCFq_opmygu0WXbu7cR7UgfANqZe88CB081TSDIQRNPu5F8x3T29XB2WsaicSPTQwiesGFEdFZrvK2LwhiwMu65_RQMIJGvYi3GeRg4gOpu0dhDnJXiZdS3JWVCGy4nTpqZklCHm4LK1b0Qc5VzVqYAnted9Fhwty-VOIB9qn4o9r8UB-zl-5syh4t7ZjGGDWoOAFL6c4mC1wNptvtbMCxNynwD4fW5j4zt4gfjfBn697e0VuqDCpyXyT5TzGhtKItWL0GYeZ3LaTBgVcVMpnd-ocDsjeudWdQbD7RO1Kuk0XtKSYxjaeU5z__-XcLV5gv2m_kT_OztFuu6IXseTaOIQI_b8ccqj1iMCRlsufR5AR0_-Pic_00ZAiut4RHlkeCfw1dBnoRAhAj5dBDiMHxsMt4vTV3P5ZFLFSos2WXar4pPPqSxrAOuLbXY6zTOXmtI4G6bZgcTsSH6gaZD794QEH_8xJiCh3TgXXK2FxzKh9IMcCC5MgyxgKaAPGptm4Ydfs-iQTFPuvKiSEKJNq94EAgNQdajpnR3pNphlCr56bLzygRm-x8i1WBfCJVCNESAZiWEUNzJ4K23riZM0DDL8gesxudwb0osh-KUQie1fa-NKFF5bFuqjiJe49xugKXDKl3hPDZn5hIQ9xIwmZAlDl0HkOqoyOMBhZ0rT7FMIYTQTWKXYPTHNOroMsymYwomFk2hHJN8aWGYEbiOC6OFluqNTmtIJKoQf5f-BAZGYDT51ef51efGtLId94kuepKYpCoQj5b9E-xjgcfJxShJnrWFDPRhv9RfBlSQW0vLLdk_K5g6UCgQ15Kf5PGNLfV9Jbr53EJKgMUzbhwI5tPbOGaWaypKaIEIPI3y4XvaLnvaJEL5nczLdIHMj5r6EzwiBstvU4dPqWij7sbkY9Tr5L31QTqL4vOYOYvlIQcEKsulodo7OSk3fVOC1nrOefa2xkRc4gjswQrggCwHo1-X6xqGlm0pszF9nqK3_ainKDkJW7wjcAd3iWYcGEGRydJJjYaNKj1yhyW1Izhrs735u2KovypCd_vR_vzKHJHufrqyVwrvnsMwHTekm5KY6FgId8uR2WISF4yr2fEGV08k76ndG76EKgXccwUrk6sk-D4kk14Md0Y1Kvs3SPcdQT3CfI63IWvVUb8eRLBSvgLIiVKScnt5KtyhpZre96QBm1EC-UAO5Yl2EoBetrRtSLbPPlGw0_twry0

**Comment by deruelle** [comment]
Thanks @maria-farooq. This looks good to me and what I had in mind. I would like @hrosa to review as well for full correctness of MGCP messages.

**Comment by maria-farooq** [comment]
updated ports in diagram. previously there were some typo in them

**Comment by hrosa** [comment]
Hi @maria-farooq @deruelle 

I think it would be a good idea for you to push your diagram code to [this folder](https://github.com/RestComm/Restcomm-Connect/tree/master/architecture_diagrams/mscontrol) so that we can comment inline.

First, I would also advice **NOT** to repeat endpoint IDs in the diagram so we can read it better and avoid confusing to which MS and endpoint belongs.

You can erase the following message as it will be removed from the workflow soon (it's an unnecessary operation)

> mgcp MDCX:
> mobicents/ivr/1@RMS1:2427
> {CallID:1, connectionID:1, ConnectionMode: sendrecv}

Another thing, the direction of NTFY message is inverse. It's the Media Server that Notifies RestComm.

> mgcp NTFY: notification entity restcomm
> mobicents/ivr/1@RMS1:2427

Also, there is not need to create an IVR endpoint for the bridge endpoint that connects both media servers. It will never be used.
Also, don't forget that you must create a local connection between the newly created bridge and the conference endpoints!

> CRCX: {sendrcv}
> {Primary: mobicents/bridge/$@RMS1:2427
> secondary mobicents/ivr/$@RMS1:2427}

Other than these notes, I think the flow is correct overall.

Looking forward to the diagram with resource cleanup ;)

Good job!

**Comment by hrosa** [comment]
Visual representation of a clustered conference can be found [here](https://docs.google.com/drawings/d/1Y8u5rGoqrXig8Wchnbhy2ZyIBUJ9wHUGyrQxkXPRF8A/edit?usp=sharing).

**Comment by maria-farooq** [comment]
@hrosa thanks a lot for the feedback, i ll follow through..

**Comment by maria-farooq** [comment]
@hrosa 

> mgcp MDCX:
> mobicents/ivr/1@RMS1:2427
> {CallID:1, connectionID:1, ConnectionMode: sendrecv}

As you said above is an unnecessary operation and will be removed from flow soon, so i removed all MDCX calls for ivr sent after CRCX: 
what about following?

> mgcp MDCX:
> mobicents/cnf/2@RMS1:2427
> {sendrecv}

Do we have any purpose for this call? this one is also called after creating connection (CRCX) b/w bridge and conference endpoint.

thanks

**Comment by maria-farooq** [comment]
updated diagram with:
- removed MDCX for ivr
- corrected NTFY direction
- created connection b/w new bridges and conference endpoints

http://www.plantuml.com/plantuml/svg/tLVBRkCs5DtxAxWesWH8nX4JO02Z7YHmKi0O9ECwxWlmXgOebwr4kYJj6SFrl_UIaYLAbcHvKdJHB8949E_ptCD3GerKQ4AKuPIlY311ZrG_uPw_Zgu_e2dJXiea6I3DLtqThj28n77GEtn7rzSV_3Dk7mfkRlepjULYwMq4Oy-li25PKh0o7Vqwc8lTHF64g2rybGjEcJ2wlr0yNBB-D_TkExx3x-T2Cof521kzVNoZ_4txdlsp7BDpzRgcb6bjlHqv2Reu2Nmd3GcbfR598Sr4gEXcW2XKQlm86uGqFEAK62u50hFSR97ApCn5DQXIJA-F4tHXIqfZ3dk-quYBI5wXyGGnGoyRSdRH7F96paR2GauWDhLXAhC1sGf6NL14X2ZTOPSk_IIFkkkCuvkRlpzzH1Ul40WN6sxOPJjsqCFeOsyuT4L1tAQ1LaekeGmQ3OVbizzVvxMTpYOz4XiqYSaMFGWXruAo12hHG_3J0AxfZo-pxbMlj7Wko3ha4aKyPcYjujHHAxIyBR2dNB0L10vp01KkOd_NPlDbziDlRmZ-qyBrE7pQs7NqyDEeB-c5eaEOoSkvC8e8JLpJnu_3zsrLd1LR4Vl2wDgm46cNSRIEu-snCG1-p_OOS1HRT4LCCKZPzhUD1_nyg8Zg1_z9X2l9XHaqCy090gYu2SvoWpqtxRb0juvDrD5DCNxFCcJ34THBGRNc0gUHJ7m3471s-hvJgdQuDZna6esAAOV_XOKLC404nB-GvlSyMeyDzBkc39yV7MlNXPKbjHivqXi4LvvZcr_6YunkzgU3hutPGSj35P387n0vWDBYAoU9NmWtw7cjEMq0zr4ITSqvaOSKyNPV7liY6U36bBXtjgReMuzPaOpiYNr3Q9Quce47XT5yAKWyPN-juUm0TM8gVPga4bikT05aUvaFSJeIQ5Lir2bvMp8NwsG1ABA5z-L3oQ-j88P2Z2TzMupnoy_ZsLEJSC235j40Yntr0kwY5t2X5t2vL6rI0NUnV-lRRqgZgX3E5GYbI3e8X8OaKrtWrW_YG6itSYqI0DTAW2jhgoG0AZwpox-4AGzI5JrWrGWCCNpDI0bct4XNmefMmBbMm6Tg1Jpu2fbmwrU-VlZgY-sjbeSFdr085NFdYuDIoAtYeA5AfsH0JXY69yosYIf63FEPEhzZmCIXYGt3KQS5y5bQ0ETQeBuL5G_uB0ztdeV63DeKGCdTsGeWFNr_Ai5_z_B7W_fxlvJAhlMsRmoqvQ9FKKIGO9zHMhmCFa63daovTPUHwxxhupAN8qLyBGTllODedZwSB8_A2C3k0Yb7xxsn5inyPapu2TdJnPm4rK49JYldDgpT_i_LPjRhjqhA5O4hf-XXf6II5j-xSXglyZFWXfjGatiyZ4ed9DwrshHhNuz4t9MoEoBnxar8n6KaulyEYRWDYRWHYVWjIBJIAj7B71Kums7Gq0BtPd0tVIlJvbUta2eXzjxk_Z8g4KazTd7D1BftKAuoWtgLQHSg6kvOtvLVAuR4VxfV_m00

**Comment by deruelle** [comment]
Thanks @maria-farooq can you also include the resource cleanup and conference termination in the same diagram or a new one ?

**Comment by maria-farooq** [comment]
ok @deruelle  i will add it, preferably in a new one which starts from 1 participant leaving the conference and then evetually the last one.
thanks

**Comment by deruelle** [comment]
@maria-farooq great ! makes sense to me

**Comment by maria-farooq** [comment]
@hrosa  @deruelle  here are snapshots of planned resource creation and cleanup
https://docs.google.com/presentation/d/1rr2O3aBHaw9tQEYwzaI3uheoSj76lxSBlqhvf3vkhZE/edit#slide=id.p

**Comment by maria-farooq** [comment]
i will attach the sequence diagram for it as well.

**Comment by deruelle** [comment]
It looks like it leaves a bridge on the other RMS left not being connected to anything. Shouldn't it be cleaned up as well ?

**Comment by maria-farooq** [comment]
Yes but i left it intentionally as a point.
this is a bit complex situation, participant-1 might not be the only one connected to that bridge..
we have taken a very simple 2 participant and 2RMS example, which is very simple compare to many other scenarios.

**Comment by maria-farooq** [comment]
Better explained in these diagrams:
[Cascading Conference Creation PNG](https://github.com/maria-farooq/Restcomm-Connect/blob/issue-1154/architecture_diagrams/mscontrol/cascading-conference-creation.png)
[Cascading Conference Creation PNG](https://github.com/maria-farooq/Restcomm-Connect/blob/issue-1154/architecture_diagrams/mscontrol/cascading-conference-creation.adoc) 
[Cascading Conference Cleanup PNG](https://github.com/maria-farooq/Restcomm-Connect/blob/issue-1154/architecture_diagrams/mscontrol/cascading-conference-cleanup.png) 
[Cascading Conference Cleanup PNG](https://github.com/maria-farooq/Restcomm-Connect/blob/issue-1154/architecture_diagrams/mscontrol/cascading-conference-cleanup.adoc)

**Comment by hrosa** [comment]
@maria-farooq agree with @deruelle when he says that bridge/4 should be deleted as well in this case.

> this is a bit complex situation, participant-1 might not be the only one connected to that bridge..

In this example, he is :)

**Comment by hrosa** [comment]
@maria-farooq I think it's bad idea to add .png files to the github repo. The repo size will increase very fast like this. Please add .png to .gitignore.
There are tools online that let us render the .adoc code. That's the beauty of it.

**Comment by maria-farooq** [comment]
thanks @hrosa 
Yes agree with deleting those bridges as well, as i have added their deletion in new plantuml cleanup diagram.
Agree on not pushing .png file as well.

**Comment by maria-farooq** [comment]
I have changed MMSConferenceController and MMSCallController to be able to select MediaGatewy from a list of available(poweredON) MS.

Each time CallManager Create a new call we get MMSCallController with next MS (roundrobin)
Each time ConferenceCenter Create a new conference we get MMSConferenceController with next MS (roundrobin)

Problem?
As per our design we need conferenceEndpoint from same MediaGateway which is holding controlling our Call 

Solution?
When ConferenceCenter asks MSControllerFactory to provideConferenceController() we can pass MediaGateWay as a parameter.

Is it a good approach?

**Comment by deruelle** [comment]
any progress on design here after our last discussion ?

**Comment by maria-farooq** [comment]
@deruelle @gvagenas @hrosa 
Here are UML diagrams according to our last discussion.
I have pushed .png files for temporary purposes, will remove them at the time of pull.
.adoc files are also pushed in repo in my local branch.

[Sequence Diagram](https://github.com/maria-farooq/Restcomm-Connect/blob/issue-1154/architecture_diagrams/mscontrol/cascadingconference/cascading-conference-mrb-sequence.png)
[Data Model](https://github.com/maria-farooq/Restcomm-Connect/blob/issue-1154/architecture_diagrams/mscontrol/cascadingconference/cascading-conference-mrb-data-model.png)
[Class Diagram](https://github.com/maria-farooq/Restcomm-Connect/blob/issue-1154/architecture_diagrams/mscontrol/cascadingconference/cascading-conference-mrb-class-diagram.png)
[Class Diagram Simple](https://github.com/maria-farooq/Restcomm-Connect/blob/issue-1154/architecture_diagrams/mscontrol/cascadingconference/cascading-conference-mrb-class-diagram-simple.png)
[Conference - in-progress Resource Snapshot](https://github.com/maria-farooq/Restcomm-Connect/blob/issue-1154/architecture_diagrams/mscontrol/cascadingconference/cascading-conference-in-progress-resource-snapshot.png)
[State Machine incomplete](https://github.com/maria-farooq/Restcomm-Connect/blob/issue-1154/architecture_diagrams/mscontrol/cascadingconference/cascading-conference-mrb-state-machine.png)

[Here is Conference Creation & Cleanup Resource Snapshots Step by Step](https://docs.google.com/presentation/d/1Neozc9g4VzMvFzFzAW7gp13nO9wav88DNlEGGjB8nQo/edit#slide=id.p)

**Comment by deruelle** [comment]
@gvagenas @hrosa I already talked to @maria-farooq this morning in our meeting. 

One thing to note is how to avoid synchronization issue on ConfSiD creation and on Master RMS assignment when 2 participants joins a conference at the same time.

Please review the class diagram and data model and provide your thoughts as well here

**Comment by maria-farooq** [comment]
After successfully connecting 2 RMS together (for a conference where participants were on difference media-servers)
Here is a list of items TODO to complete this task:

- [ ]

**Comment by maria-farooq** [comment]
After successfully connecting 3 RMS together (for a conference where participants were on difference media-servers)
Here is a list of items TODO to complete this task:

- [x] Try connecting both conference endpoints directly (this is optional/experimental work and can be tried in a separate branch) 
- [x] Scale the solution for N-RC|RMS nodes in HA. 

## Resource Cleanup on participant-left/conference-end events
- [ ] Make Sure Master conference-EP is Not deleted/cleaned, If Master Conf participants leave first.

    > MMSController should see DB and check if slaves are currently connected to it (means he is not last in conference) then dont destroy cnf EP). Now it will be responsibility of Last Slave to clean it up
- [ ] Make Sure when last participant leaves on a Slave Conference: It (CMRC) closes connections (that it opened) with Its (Own Cnf-EP) As well as with Master (Cnf-EP).
- [ ] Make Sure Master conference-EP is deleted/cleaned after conference ends.

   > If Salve leaves and MMSController see in DB that it is last participant (ALL over the cluster) in conference, then it send destroyEndpoint to Master RMS.

## Synchronisation 
- [ ] Concurrency: make sure entity based decision are based on consistent data.
    
    > MVCC or Optimistic Locking
    > This could resolve following 2 problems as well.
- [ ] Synchronisation to pick master, when participants join at same time.
- [ ] Synchronisation to generate conferenceSid, when participants join at same time.

## Music and Beeps
- [ ] Modify music on hold: according to conference in cluster
- [ ] Modify beep on enter and exit: according to conference in cluster
- [ ] Send join-complete to all all observers when slave is connected to master and not before that. 

## StartOnEnter & EndOnExit
- [ ] Modify StartOnEnter: according to conference in cluster
- [ ] Modify EndOnExit: according to conference in cluster

## Unit Testing
- [ ] Test Cases 

    > See Mock Media Server works, discuss with George and add TC for the feature

## Documentation
- [ ] Update relevant diagrams according to latest design.
- [ ] Remove the ones which were discarded due to design.
- [ ] Configuration instructions etc.

## Party
- [ ] Cheers!
