### ISSUE TITLE
Adapt SIP Registrations for Organizations concept compliance

### ISSUE THREAD

**Issue by ghjansen** [RestComm/Restcomm-Connect#1107]
This issue is an extension of issues #748, #784 and #1094.

To make it possible the merge between Organizations and SIP concepts, its required that the `Registration` entity became aware of the Organization of the Clients involved, so that will be possible to redirect calls and manage the registration lifecycle properly.

Currently, the `MybatisRegistrationsDao.getRegistration(String user)` is used in `SmsSession`, `UserAgendManager` and `B2BUAHelper`, without considering the Client's Organization. The consequence is that a call to a Client `bob@foobar.com` will always ring in the last successful Registration for Client named `bob`, independent of the Organization. So even calling `bob@foobar.com`, its possible that `bob@xpto.com` pickup the call, if he is the last one successful registered.

https://github.com/RestComm/Restcomm-Connect/blob/master/restcomm/restcomm.dao/src/main/java/org/mobicents/servlet/restcomm/dao/mybatis/MybatisRegistrationsDao.java#L73

**Comment by ghjansen** [comment]
@deruelle @gvagenas as discussed yesterday, the solution agreed for this blocker was to make use of the `Registration.addressOfRecord` to properly locate the registration in the database and continue the call flow.

This worked well for `SipServletRequest`s carrying **INVITE** or **REGISTER** messages, and the call is redirected properly between three distinct Clients named `bob` from different Organizations. It was possible because the URIs present in the SIP message header brings the DNS name defined in the application client e.g. `sip:bob@foobar.restcomm.com`.

The blocker i hit now is that for `SipServletResponse`s carrying **OPTIONS** messages, there is no URIs using DNS like i mentioned above, they are using the format `sip:bob@127.0.0.1:5080` instead, so its not possible to locate the `Registration` and update it through `UserAgentManeger.pong(Object message)`, which consequently results in the registration removal for the Client. I tested with four different SIP softwares (Linphone, Jitsi, iSoftPhone and Telephone) and they all demonstrated the same behaviour.

I tried also to find some unique information inside the `Registration` record that may be located in the **OPTIONS** message, to use this as search parameter to update the record, but it seems that there is no such thing. Can you guys confirm if you are aware of these details or if i'm missing something?

Any light from you will be great. Thanks in advance!

**Comment by deruelle** [comment]
@ghjansen @gvagenas  Can you share a pcap of REGISTER and OPTIONS ?

If it's just a 200 OK Response we receive, we could keep the registration in the SIP Session of the OPTIONS request that we send out and update it in the pong method by fetching the Registration from the SIP Session. This would also relieve the DB of 1 query operation especially with a lots of Clients registered this may be good for performance.

**Comment by gvagenas** [comment]
@ghjansen UserAgentManager uses the registration location to create the OPTIONS request as you can see here, https://github.com/RestComm/Restcomm-Connect/blob/3bf9435099c0b67dcaac579d745fabc194fbe286/restcomm/restcomm.telephony/src/main/java/org/mobicents/servlet/restcomm/telephony/ua/UserAgentManager.java#L143-L143.

Maybe you need to change this to use the AddressOfRecord but I believe this will be a problem later with NAT. Nevertheless to solve the issue you are now the proper way is to use AOR.

For the record, location is the real ip address and port that the REGISTER request arrived to Restcomm and AOR is constructed by the SIP Header TO.

**Comment by ghjansen** [comment]
Thats great @gvagenas ! Thanks to your suggestion, Voice and SMS seems stable now in main scenarios. I'm moving forward by replacing what is left for properly handle `Client` and `Registration` entities under the concept of `Organization`, until we cover everything. Lets see if we hit more blockers like these or if the NAT issue pops up, like you mentioned.

Thank you very much! 😃

**Comment by ghjansen** [comment]
Needs to replace the usage of `MybatisRegistrationsDao.getRegistrations` by `MybatisRegistrationsDao.getRegistrationsByAoR`.

**Comment by ghjansen** [comment]
@maria-farooq could you confirm that this issue can be closed?
