### ISSUE TITLE
Restcomm IncomingPhoneNumbers must Regex 

### ISSUE THREAD

**Issue by croufay** [RestComm/Restcomm-Connect#1112]
related to this issue

https://github.com/RestComm/Restcomm-Connect/issues/708

**Comment by gvagenas** [comment]
@croufay, what is not covered at #708 and you opened this issue?

**Comment by croufay** [comment]
The previous issue focused on using a default * that will be used by Restcomm if nothing else matches. As far as I understand implementing full Regex will allow us match fine tune the IncomingNumbers to match a given pattern.

ex.

Alll numbers that start with 8899....
or all number that ends with ...8899[*] and many more


Regards

Charles

**Comment by gvagenas** [comment]
@croufay the comments following the issue provide more details for the feature that also includes what you say here. Please check there and if needed add a comment to the #708 issue. 
I will close this one as duplicate for now.

**Comment by croufay** [comment]
@gvagenas ok np

charles
