### ISSUE TITLE
cache-uri is wrong for external media server options

### ISSUE THREAD

**Issue by hamsterksu** [RestComm/Restcomm-Connect#1124]
Hi 

i have found a bug: `cache-uri` doesn't contains restcomm `port`
in case if external mediaserver is specified 

https://github.com/RestComm/Restcomm-Connect/blob/d663828440f51a5687ea78aad0caa0cc94daf5be/restcomm/configuration/config-scripts/as7-config-scripts/restcomm/autoconfig.d/config-restcomm.sh#L430

https://github.com/RestComm/Restcomm-Connect/blob/master/restcomm/configuration/config-scripts/as7-config-scripts/restcomm/autoconfig.d/config-restcomm.sh#L436

thanks,

**Comment by hamsterksu** [comment]
@leftyb, @hrosa it's very important for our customer. is it possible to get it today?

**Comment by deruelle** [comment]
@hamsterksu can you do a pull request for this ? this will help speed up the process.

**Comment by hamsterksu** [comment]
@deruelle i have added PR

**Comment by leftyb** [comment]
@hamsterksu ,

Thank you for your contribution.
There is a small issue at your PR. You use "http" always. Need to use either "http" or "https".
For that reason you can see the "if [ "$DISABLE_HTTP" = "true" ]; then"

Regards

**Comment by hamsterksu** [comment]
@leftyb thank you for review. 
i have fixed it.
