### ISSUE TITLE
Adapt Outbound Calls for Organizations concept compliance

### ISSUE THREAD

**Issue by ghjansen** [RestComm/Restcomm-Connect#1131]
This issue is an extension of issues #748, #784, #1094 and #1107.

After #1094 and #1107, main scenarios involving Calls are stable and working with the concept of Organizations. But considering outbound calls like the ones involving WebRTC Clients or RVD Applications (executed at `CallManager.outboundToClient`), is not currently possible to determine the Organization namespace.

The investigation need to take into account that the methods `MybatisRegistrationsDao.getRegistrationByInstanceId` and `MybatisRegistrationsDao.getRegistrations` still using only the name of the client, and somehow, the namespace of the Organization needs to be informed like it was done to `MybatisRegistrationsDao.getRegistrationByAoR`.

Considering that RVD Projects allow to inform the client name on which will be the destination of a call, possibly the UI will have to be adjusted to replace the current inputs in the formats `bob` and `client:bob` to something like `bob@foobar.restcomm.com` or `client:bob@foobar.restcomm.com`.

**Comment by otsakir** [comment]
Issue moved to [RestComm/visual-designer #90](https://github.com/RestComm/visual-designer/issues/90) via [**ZenHub**](https://www.zenhub.com/)
