### ISSUE TITLE
Adapt Outbound SMSs for Organizations concept compliance

### ISSUE THREAD

**Issue by ghjansen** [RestComm/Restcomm-Connect#1132]
This issue is an extension of issues #748, #784, #1094 and #1107.

After #1094 and #1107, main scenarios involving SMSs are stable and working with the concept of Organizations. But considering outbound SMSs like the ones involving Applications (executed at `SmsSession.outbound`), is not currently possible to determine the Organization namespace.

The investigation need to take into account that the methods `MybatisRegistrationsDao.getRegistrationByInstanceId` and `MybatisRegistrationsDao.getRegistrations` still using only the name of the client, and somehow, the namespace of the Organization needs to be informed like it was done to `MybatisRegistrationsDao.getRegistrationByAoR`.

Considering that RVD Projects allow to inform the client name on which will be the destination of a SMS, possibly the UI will have to be adjusted to replace the current inputs in the formats `bob` and `client:bob` to something like `bob@foobar.restcomm.com` and `client:bob@foobar.restcomm.com`.

**Comment by otsakir** [comment]
This issue was moved to RestComm/visual-designer#43
