### ISSUE TITLE
When calling PSTN from olympus, If PSTN side (e.g. moibile phone) reject the call BUSY (486) not reaching Olympus

### ISSUE THREAD

**Issue by leftyb** [RestComm/Restcomm-Connect#1155]
Tried on cloud server calling by mobile phone and then if reject the call from my mobile Olympus continues to ring. The proper function should be that Olympus stops ringing and print a message for BUSY end.

**Comment by gvagenas** [comment]
@leftyb I just tested the same call flow and for me, call at Olympus stopped after I rejected call from my mobile. Can you please check again as I think problem is with your browser or something?

**Comment by leftyb** [comment]
@gvagenas 
 I tried it and still same issue. I am using Chrome Version 51.0.2704.79 (64-bit)

**Comment by leftyb** [comment]
Closing issue. False tested.  After 2-3 seconds Olympus quits as well..
