### ISSUE TITLE
Support account role update

### ISSUE THREAD

**Issue by otsakir** [RestComm/Restcomm-Connect#1168]
Account role update is not supported. The existing policy used in account *creation* is the following:

* Administrators can explicitly set the roles of the sub-accounts they create.
* non-administrators create sub-accounts of  their own role.

The same policy can be adapted to account modification:

* Administrators can explicitly update the role of a sub-account arbitrarily.
* non-administrator cannot change the role of their sub-accounts at all.
* Administrators can change their own role arbitrarily too. That may imply privilege loss and a warning can be displayed in the UI in such a case.

The patch includes patching AccountsEndpoint, AdminUI account details form and the AccountsEndpointTest in the testsuite (check role is updated).

**Comment by muhammadbilal19** [comment]
@otsakir i stated making some changes for this issue. I need to clarify few things

- if Current login user Say Default Admin (admin@company.com) want to update own role do we need to allow ? In that case do system need to force this user to login again?
- According to the rule non-administrator can only create sub accounts of their own types but in that scenario their is a possibility that Default Admin may have few administrator sub accounts

**Comment by muhammadbilal19** [comment]
@otsakir can you please comment on my previous comment.

**Comment by otsakir** [comment]
@muhammadbilal19, appologies for the delay. Your comment fell through the cracks :-(.

* Indeed, it seems that allowing an admin to change his own role is not really necessary, i agree.
* The Default Admin may have administrator sub-accounts. I think that's ok. Default Admin should take care when someone is made admin (not sure if i got your second bullet here). 
* In general, allowing an account changing his own role seems like a useless feature.

Thinking over it, it seems to me that the only case of role modification that is really needed is for an Admin to be allowed to change the roles of his sub-accounts arbitrarily.

@muhammadbilal19 wdyt?
@gvagenas, @deruelle , any thoughts on this ?

**Comment by deruelle** [comment]
As a general rule, there is some documentation on accounts and sub accounts at http://documentation.telestax.com/connect/api/Restcomm%20-%20Multi-tenancy%20and%20Managing%20Sub-Accounts.html#restcomm-rest-api. If there is not enough information. Please consider contributing changes to it at https://github.com/RestComm/Restcomm-Connect/blob/master/restcomm/restcomm.docs/sources-asciidoc/src/main/asciidoc/api/Restcomm%20-%20Multi-tenancy%20and%20Managing%20Sub-Accounts.adoc

1. "allowing an admin to change his own role is not really necessary" i agree.
2. "The Default Admin may have administrator sub-accounts." I think that's ok too
3. "In general, allowing an account changing his own role seems like a useless feature." Agreed.

**Comment by muhammadbilal19** [comment]
Thanks @otsakir and @deruelle for your comments and apologies for the late reply.

I also agree that the only thing which is required is to allow ADMIN to update its sub accounts. I will create a pull request for this issue after doing above changes.

**Comment by deruelle** [comment]
Thanks @muhammadbilal19 . Please refer to the Pull request here once done so it can be reviewed

**Comment by muhammadbilal19** [comment]
@deruelle Pull request created for this issue #1294
