### ISSUE TITLE
Version number displayed incorrectly

### ISSUE THREAD

**Issue by ivelin** [RestComm/Restcomm-Connect#117]
After purchasing the latest AMI from AWS Marketplace, the expected version number in the Admin UI should be 7.2.0. Instead it sill shows 7.1.5.

In addition to version number, the information box should also display the release date.

![screen shot 2014-11-16 at 11 33 29 am](https://cloud.githubusercontent.com/assets/2234901/5063216/d6df770e-6da2-11e4-9892-a9f6046bcb2b.png)

**Comment by brainslog** [comment]
Requires https://github.com/Mobicents/RestComm/issues/123.
