### ISSUE TITLE
Feature flag to disable checking registration.instanceId for WebRTC clients during creation of outbound call to Clients

### ISSUE THREAD

**Issue by gvagenas** [RestComm/Restcomm-Connect#1174]

**Comment by gvagenas** [comment]
@deruelle Currently when CallManager is asked to prepare an outbound call to a WebRTC client, first checks if Restcomm is behind LB, 

- If Restcomm is behind LB then proceed to add the client's location to be dialed
- If Restcomm is not behind LB, then CallManager checks if the instanceId of the registration is the same as the current instance, and if not it will discard this location.

I believe the above behavior is ok for Restcomm in a cluster, since there will be LB in front of the Restcomm cluster and WebRTC client will register there.

Can you please comment

**Comment by deruelle** [comment]
that sounds correct to me

**Comment by gvagenas** [comment]
Moved to testing so we confirm the functionality at the hastaging
