### ISSUE TITLE
Music on hold does not stop when non-moderatror particpant joins the conference

### ISSUE THREAD

**Issue by maria-farooq** [RestComm/Restcomm-Connect#1180]
We can reproduce the issue by defaults apps in latest restcomm binaries.
### Steps to reproduce 

1. Dial 1311:  `moderator` **Result?**  `music on hold starts playing`
2. Dial 1310 `non moderator` **Result?**  `music on hold` **Expected Result** `music on hold should stop and conference should start (so participants could talk to each other, as both moderator and an other participant are there)`

> Please note as soon as 2 moderators join the conference, music-on-hold stops and conference continues.

### Restcomm Release
[Restcomm-JBoss-AS7-7.8.0.935](https://mobicents.ci.cloudbees.com/job/RestComm/935/)

cc: @gvagenas  @deruelle

**Comment by deruelle** [comment]
This happened to me on cloud today with the default music on hold.

**Comment by deruelle** [comment]
Reopening issue as it was reported today on cloud that 2 persons were waiting with music on hold until me the 3rd participant joined and we were all bridged together. This is happening on 7.8.0

**Comment by deruelle** [comment]
Also tied to issue https://github.com/RestComm/Restcomm-Connect/issues/1180

**Comment by maria-farooq** [comment]
@deruelle i have collected the logs. i will truncate them to the problem window you described in chat and will attach here.

**Comment by maria-farooq** [comment]
logs: https://drive.google.com/a/telestax.com/folderview?id=0B2CFlEFeY-zfQmttUWJsQlE1bjA&usp=sharing

**Comment by maria-farooq** [comment]
should be fixed with new builds
