### ISSUE TITLE
Display Instance Initializing web page while instance is booting

### ISSUE THREAD

**Issue by ivelin** [RestComm/Restcomm-Connect#119]
Currently while the AWS AMI instance is loading and the user tries to access it via web browser, the result is either no-response or partial response showing login screen, but not allowing login. See screenshot.

The Restcomm instance should show a user friendly static page making it clear that the server is loading and the user should wait a few moments. When the instance is ready to rock, the web page should indicate that.

This problem is especially noticeable when the instance is pulling a new image update (e.g. from 7.1.5 to 7.2.0). 4-5 minutes feel like a long time. The time has to be filled in with intelligent UX.

![screen shot 2014-11-16 at 5 59 20 pm](https://cloud.githubusercontent.com/assets/2234901/5063864/32697b04-6dbe-11e4-8d87-6f2e374c0326.png)

**Comment by ammendonca** [comment]
Not applicable anymore. Closing.
