### ISSUE TITLE
Implement user-linking-on-demand (SSO)

### ISSUE THREAD

**Issue by otsakir** [RestComm/Restcomm-Connect#1208]
Out of the box, all restcomm accounts will be unlinked from their keycloak user counterparts. When an instance uses SSO the the *user-linking-on-demand* "protocol" will be used to securely link an account with a keycloak user and thus allow this account to be accessed through keycloak authentication workflow.

This "protocol" is about allowing the following workflow:

1. Alice has an 'unlinked' account in a Restcomm instance that has recently switched to SSO operation.
2. She tries to access AdminUI but instead of seeing the familiar login form she is redirected to keycloak login screen.
3. She doesn't have a keycloak user yet but she can easily register for one. It's free and easy. So she does.
4. She then tries to access AdminUI again, but this time she manages to login to the keycloak login screen and sent back to AdminUI.
5. AdminUI can tell that this user has been authenticated but does not yet know if she has an account in this instance. So, a linking challenge form is displayed. She is asked to enter the password of her restcomm account. At this state, Alice can do no more. Only this form is accessible in AdminUI.
6. Alice enters the correct account password and hits "submit". Restcomm knows Alice's email form the valid keycloak token as well as the claimed password of Alice's account. A verification is done and if all goes right, the account is "linked" and Alice is now allowed access to AdminUI normally.

This issue is about implementing this workflow in AdminUI and Restcomm REST api's. 

**Design consideration**

The only important design consideration i see is *which* REST method to use to allow alice try to update her account while not trusted by Restcomm (at least at an instance level). Two solutions seem possible here:

a. Introduce a new method somewhere under /Accounts/alice@company.com/... For example:
```
PUT .../Accounts/alice@company.com/linking
Authorization: Bearer [keycloak token here that contains the email address]
value=true&auth_token=${alice_account_password}
```
that will return on of the following:
* 200 - account linked normally
* 401 - bad Bearer token
* 403 - bad encodedPassword
* 409 - already linked

b. Handle that in the existing account *update* method:
```
PUT .../Accounts/alice@company.com
Authorization: Bearer [keycloak token here]
linked=true&auth_token=${alice_account_password}
```
HTTP responses will be the same as in (a).

@gvagenas , @deruelle wdyt? Any other suggestions ?

**Comment by deruelle** [comment]
@otsakir New method seems cleaner. But I don't have strong preferences.
