### ISSUE TITLE
RVD Apps should allow multiple entry points (SMS, USSD, Voice, etc).

### ISSUE THREAD

**Issue by ivelin** [RestComm/Restcomm-Connect#1214]
Currently an App can be either SMS, USSD or Voice. This does not look intuitive when I go to the number to app assignment page. From a user perspective, I would like to be able to assign an app to one or more numbers. For example conferencing app with call-in numbers in multiple countries. 

I would also like to be able to use the same app to communicate via multiple channels. For example I would like to be able to text all participants in a conference call. Sending an SMS to the call-in number should broadcast the message to all conference call attendees. Same intuitive logic as a group call via Skype , Hangouts, etc.

Currently the Number to App assignment page separates SMS, USSD and Voice in different entry fields, which is confusing. This approach makes more sense for advanced configuration mode with URL assignment per communication channel, but the basic UX should be simple Number to logical App correlation.

Further in the current UI, it is possible to assign a Voice app to an SMS channel, which does not make sense. See screenshot. 

![screen shot 2016-06-22 at 3 52 59 pm](https://cloud.githubusercontent.com/assets/2234901/16283357/13db6346-3892-11e6-9d90-4a260b62fe76.png)

**Comment by deruelle** [comment]
@ipsilantide has this feedback been taken into account in the new UI ?

**Comment by otsakir** [comment]
This issue was moved to RestComm/visual-designer#41
