### ISSUE TITLE
Conference is not cleaned properly.

### ISSUE THREAD

**Issue by leftyb** [RestComm/Restcomm-Connect#1248]
Calls are staying/hanging  at the conference.

As a result music on hold cannot be heard.
13:39:56,662 INFO  [org.mobicents.servlet.restcomm.interpreter.VoiceInterpreter](RestComm-akka.actor.default-dispatcher-2363) At conferencing, state: joining conference , playMusicForConference: true conferenceInfo.participants().size(): 4

**Comment by gvagenas** [comment]
RestComm has to request notification on connection level
then we need to implement timeout mechanism on RTP connection
then have Connection send NTFY to Restcomm

**Comment by gvagenas** [comment]
related to https://github.com/RestComm/mediaserver/issues/191 and https://github.com/RestComm/mediaserver/issues/114
