### ISSUE TITLE
 VOICE ANALYTICS GRAPH - Minutes line always flat

### ISSUE THREAD

**Issue by ivelin** [RestComm/Restcomm-Connect#1263]
The minutes line does not seem to be accurately measuring call minutes for the restcomm account. See screenshot.

![capture](https://cloud.githubusercontent.com/assets/2234901/16656098/fb93d8f6-4465-11e6-9d58-e30660a51e19.PNG)

**Comment by deruelle** [comment]
Duplicate of https://github.com/RestComm/Restcomm-Connect/issues/309
