### ISSUE TITLE
Include InstanceID in the CallSID

### ISSUE THREAD

**Issue by gvagenas** [RestComm/Restcomm-Connect#1266]
... so sip responses and requests generated by Restcomm will include the instance id

**Comment by deruelle** [comment]
Useful for Live Call Modifications in a cluster to stick to same node without any state storing

**Comment by deruelle** [comment]
tied to https://github.com/RestComm/sip-servlets/issues/172

**Comment by hamsterksu** [comment]
hi @gvagenas 

i downloaded restcomm v7.9.0.987 released 08/15/2016 10:26AM
and haven't found `instanceid` in `CallSid` in http request to my app. i suppose it should be here too

it's raw http post body 
`CallSid=CA19cf1a9dd14c4e3395f49a53638446e9&AccountSid=ACae6e420f425248d6a26948c17a9e2acf&From=alice&To=1111&CallStatus=ringing&ApiVersion=2012-04-24&Direction=inbound&CallerName=null&ForwardedFrom=null&CallTimestamp=2016-08-18T13%3A46%3A29.507Z`

could you explain this moment for me please?
it critical knowledge to contribute issue - https://github.com/RestComm/load-balancer/issues/41 

thanks,

**Comment by gvagenas** [comment]
@hamsterksu The patch for this issue add InstanceId to the SIP requests/responses.
For the HTTP request/responses to include InstanceID the following issues have been created #1327 and #1226 

Thanks
George

**Comment by hamsterksu** [comment]
thank you @gvagenas 
i have question about id format why do you use `<callid>-<instanceId>` instead of `<instanceId>-<callid>`

IMHO `<instanceId>-<callid>` looks like grouping by `instanceId`. it will be easy to filter logs and etc

**Comment by gvagenas** [comment]
@hamsterksu I haven't thought about what you suggest and sounds a good idea. I will change the format as you suggest. Can you please comment this for issue #1327 ?
