### ISSUE TITLE
Execute custom script code in an RVD module

### ISSUE THREAD

**Issue by otsakir** [RestComm/Restcomm-Connect#128]
Run custom code snippets in an RVD module. JavaScript, Groovy and JRuby could be considered. Easy of use and performance are key factors.

**Comment by deruelle** [comment]
@gvagenas @otsakir can we already run javascript code in RVD to allow RVD apps to do some things more dynamic rather than always delegating to an ES ?

**Comment by otsakir** [comment]
@deruelle , there had been an old implementation of a "Script" element that supported Groovy but never reached production branch. Here are some considerations regarding 'script' feature:

* Security issues and administrative load for RAS applications.
* Performance issues probably.
* Deviation from the typical RVD design goals i.e. one should not have programming skills to use it.

There are a couple of alternative ideas though that will improve RVD's in the same direction and allow implementing much more complex logic with it that we currently can handle (without ES):

https://github.com/RestComm/Restcomm-Connect/issues/1225
https://github.com/RestComm/Restcomm-Connect/issues/317
