### ISSUE TITLE
Under LB ACK Request -URI is not properly patched.

### ISSUE THREAD

**Issue by leftyb** [RestComm/Restcomm-Connect#1282]
At the  pcap : lbp2p.pcap 
package No. 328 the Request-URI is not correct. It uses the private IP address.

Call flow:
P2P SIP call
from alice to bob under LB (edited)
The flow looks good until the time the the p2p connection is about to establish.
So the Dest. client send the ACK to the LB->RC->LB->Src.Client
but the part from RC->LB is wrong
due to erroneous Request-URI

logs :
https://app.box.com/files/0/f/8852418198/Issue__1282

**Comment by gvagenas** [comment]
@leftyb what is the value of "<patch-for-nat-b2bua-sessions>" in the restcomm.xml you test?

**Comment by deruelle** [comment]
@leftyb tested the patch successfully however @gvagenas we should also patch for BYE, right ?

**Comment by leftyb** [comment]
After testing with @gvagenas  latest Modifications (sip, WebRTC )P2P calls works properly on HA. (ACK, BYE, BUSY).
