### ISSUE TITLE
Support Live Call Modification in a cluster

### ISSUE THREAD

**Issue by deruelle** [RestComm/Restcomm-Connect#1312]

**Comment by deruelle** [comment]
Link to https://github.com/RestComm/Restcomm-Connect/issues/1285, https://github.com/RestComm/load-balancer/issues/41, https://github.com/RestComm/Restcomm-Connect/issues/1266

**Comment by deruelle** [comment]
@gvagenas @maria-farooq given the work we did on https://github.com/RestComm/Restcomm-Connect/issues/1266 for Live Call Modifications in a cluster. Is the ConferenceSid taking the instance-id as well (of the master node for Conference in a Cluster) ?

**Comment by maria-farooq** [comment]
@deruelle it is not so far. But it saves Media-Server id.
Can you please guide what kind of changes we should be able to make in a live conference.

**Comment by deruelle** [comment]
ConferenceSID should be changed from `ConferenceSID=<random ConferenceSid>` to `ConferenceSID = <Instance ID (of the conf master)>-<random ConferenceSid>`

We will then modify the LB to route HTTP calls to /2012-04-24/Accounts/{AccountSid}/Conferences/{<Instance ID (of the conf master)>-<ConferenceSid>} and /2012-04-24/Accounts/{AccountSid}/Conferences/{<Instance ID (of the conf master)>-<ConferenceSid>}/Participants/{CallSid} to the conf master always for easier central management of Conferences. Or is it needed at all, ie can any nodes of the cluster even those without any participants on it manage the conference still ?

**Comment by maria-farooq** [comment]
## Manage the Conference

### Adding a participant: 
- Can be done from LCM: where from any node we can join the conference.
- ConferenceSid does not have a say here as we join conference by providing their friendly name.

### Removing a participant: 
- Should be done from LCM.
- I have not checked functionality but if callSid is combined already with instanceId and LB will send this request only to relative instance than we are fine here well and 
- ConferenceSid does not have any say here as its a call which is being hung up and as per existing flow if if belongs to a conference, it will leave the conference and existing procedure should be able to handle it like a normal hangup.

**Comment by deruelle** [comment]
@maria-farooq sounds good. How about muting/unmuting a participant. done through CallSid as well ?

**Comment by maria-farooq** [comment]
I am starting work on it since it is blocking current task to clear LCM related test-cases on RC+RMS5 testing.

**Comment by maria-farooq** [comment]
After discussion with @leftyb and @gvagenas it is better if LB truncate instance ID from request and only forward call Sid to relevant restcomm Node.

**Comment by maria-farooq** [comment]
https://github.com/RestComm/load-balancer/issues/85

**Comment by maria-farooq** [comment]
After the discussion over [design for the solution ](https://docs.google.com/document/d/1_hkfvP7YfuLzwrG6iEf1RfCyN1OPnoINxiUCpePUhJQ/edit?ts=587d5b91#heading=h.u8zqipdng3v7)

- [ ] https://github.com/RestComm/Restcomm-Connect/issues/1907
- [ ] https://github.com/RestComm/load-balancer/issues/100
