### ISSUE TITLE
Update Documentation for SSL/ HTTPS Restcomm configuration

### ISSUE THREAD

**Issue by croufay** [RestComm/Restcomm-Connect#1321]
Update Documentation for SSL/ HTTPS Restcomm configuration

The following page is out of date

http://documentation.telestax.com/connect/configuration/Restcomm%20-%20Enable%20HTTPS%20secure%20connector%20on%20JBoss%20AS%207%20or%20EAP%206.html#secure

**Comment by croufay** [comment]
fixed and doc updated

**Comment by leftyb** [comment]
@croufay Just one comment, using SECURESSL=SELF, you dont need to manually create a self-signed certificate. RC scripts are generating the certificate as well.
