### ISSUE TITLE
Adapt performance test scripts to collect data from RMS pid

### ISSUE THREAD

**Issue by ghjansen** [RestComm/Restcomm-Connect#1323]
The script https://github.com/RestComm/Restcomm-Connect/blob/master/load_tests/run.sh is currently collecting data from RESTCOMM pid, and needs to be able to work also with RMS pid.

The inclusion of a additional flag parameter to indicates if the test should run using RMS pid will set the pid properly and proceed with tests. This new flag will also be included as a parameter inside the CI job.

**Comment by deruelle** [comment]
@ghjansen can this be merged ? did you do a PR on that ?

**Comment by ghjansen** [comment]
@deruelle i would like to have all RMS jobs running with success first (one of them seems to have issues) so we can fix as needed and merge it all at once. I'll conclude the investigation on that and create the PR with my considerations for @gvagenas when done.

**Comment by ghjansen** [comment]
Closed via PR #1416.
