### ISSUE TITLE
Restcomm HTTP requests (download RCML etc) should include InstanceID

### ISSUE THREAD

**Issue by gvagenas** [RestComm/Restcomm-Connect#1327]

**Comment by hamsterksu** [comment]
let's use the following format for new `callsid`: `<instanceId>-<callid>`

`<instanceId>-<callid>` looks like grouping by `instanceId`. it will be easy to filter logs and etc

**Comment by deruelle** [comment]
@knosach @hamsterksu Let's modify https://github.com/RestComm/load-balancer/issues/41 implementation as well then to match this

**Comment by deruelle** [comment]
Can this one be closed ?
