### ISSUE TITLE
Switch to VI API 3.0 for DID provisioning so number capabilities search works as expected

### ISSUE THREAD

**Issue by ivelin** [RestComm/Restcomm-Connect#133]
In the current implementation, number capabilities search is not effectively working. When a user wants to see SMS enabled numbers before registering one, the UI does not respond as expected.

**Comment by ivelin** [comment]
http://wiki.voipinnovations.com/display/VI/Listing+of+all+API+3.0+Methods

**Comment by gvagenas** [comment]
Since now we use Nexmo we wont invest time on the VI 3.0 API
