### ISSUE TITLE
RVD HTTP method in Redirect verb should be mandatory

### ISSUE THREAD

**Issue by ghjansen** [RestComm/Restcomm-Connect#1340]
When a Redirect verb is configured with the URL of a target module (`controller?target=module1`) but the field `method` is not informed, the interpreter fails to process the verb and the call is hanged up. 

Once the `method` field is not required and the project is saved without errors (filling it or not), that may cause unexpected results. So if this field turns into mandatory, that should avoid this situations.

**RVD Configuration**

![screen shot 2016-08-30 at 11 11 00](https://cloud.githubusercontent.com/assets/1459428/18092517/ec2897b4-6ea2-11e6-93fe-187eef73f6c7.png)

**Resultant RCML**

![screen shot 2016-08-30 at 11 12 37](https://cloud.githubusercontent.com/assets/1459428/18092520/f5253e4e-6ea2-11e6-91f9-05d1ed176c0e.png)

**Comment by otsakir** [comment]
This issue was moved to RestComm/visual-designer#37
