### ISSUE TITLE
Support Conference Management in a cluster

### ISSUE THREAD

**Issue by deruelle** [RestComm/Restcomm-Connect#1342]
We need to ensure that HTTP requests for a given conference SID always go the master node through LB stateless algorithms similar to https://github.com/RestComm/Restcomm-Connect/issues/1312

**Comment by jaimecasero** [comment]
Hopefully this will be accomplished through an specific HTTP header. We could do with URI parsing, but LB performance would be impacted..

**Comment by maria-farooq** [comment]
only feature left here is Mute/unMute participants https://github.com/RestComm/Restcomm-Connect/issues/1135
which is part of my current sprint

**Comment by maria-farooq** [comment]
Hi @deruelle ,
> HTTP requests for a given conference SID always go the master node through LB stateless algorithms similar to
can you please explain why we need that?

**Comment by deruelle** [comment]
this comment was made before the Conference in a Cluster work so it may not be applicable anymore.

**Comment by maria-farooq** [comment]
conference API behaves as same in standalone env as in cluster.
IMO this task is not applicable anymore.
