### ISSUE TITLE
Rules to enforce strong password for clients/accounts

### ISSUE THREAD

**Issue by gvagenas** [RestComm/Restcomm-Connect#1347]

**Comment by deruelle** [comment]
Needed at Both API and Admin UI level. @otsakir will need your help here on having something similar to choosing a password for the first time for the account but for the Restcomm SIP Client this time

**Comment by otsakir** [comment]
@deruelle, i suggest the following:

1. Password sanitizing at AdminUI level when a Client is created (not including the default Client which is not created directly from AdminUI).
2. Password **sanitizing** at AdminUI level when a Client is updated.
3. Password sanitizing at Endpoint level when an Account is created/updated. The same sanitization rules as the ones currently in AdminUI will be applied. Return 400 - BAD_REQUEST when the rules fail.
4. Password sanitizing at Endpoint level when a Client is created/updated. Same rules, same return values when rules fail.

I'm not sure about the following:

* Does it make sense to bypass these restrictions in some cases?
* Parameterize sanitization rules ? From configuration/per account/role ? Better to deal with this later.

**Comment by otsakir** [comment]
After discussing with @gvagenas , i'll proceed with the AdminUI part of the patch.

**Comment by otsakir** [comment]
Server side work pending. Re-opening issue

**Comment by otsakir** [comment]
Here is the specification of the password strength algorithm and a version of the algorithm itself in JS:

https://github.com/subarroca/ng-password-strength#formula
https://github.com/subarroca/ng-password-strength/blob/master/app/src/services/password-strength-formula.factory.js#L25

**Comment by deruelle** [comment]
Thanks @otsakir

**Comment by deruelle** [comment]
@otsakir how much work is left on the server side work ?
