### ISSUE TITLE
Allow Admin account to see all CDRs from all accounts (even from deleted accounts)

### ISSUE THREAD

**Issue by deruelle** [RestComm/Restcomm-Connect#1349]
True for Account with regards to their sub accounts as well. 

Ideally we should be able to filter calls by account/sub-account in the Admin UI as well

**Comment by otsakir** [comment]
So, are we essentially talking about two parameters?

**1. Nesting flag**

An option on whether to include resources (Call records) from child sub-account as well. For example 'recurse=true' or 'subAccount=true'. Any ideas on naming ?

Also note:

- We need a clean contract here as to which depth this will work for. Supporting more than one level will probably introduce much complexity in the DB. It seems to me that even having a single level (returning CDRs of admin and his children) will already introduce a join with accounts table.

- Which users will be allowed to use this flag. Is it only for the administrators ? Keep in mind that currently we can only store a single role in an account.

**2. Include deleted**

An option that will determine whether cdrs from deleted (or CLOSED) accounts will be included in the result. For example 'removed=true'. It's also important which users will be allowed to use this feature. Will it be only for admin ? 

@deruelle , @gvagenas , any feedback here ?

Btw, if we start creating logic using nesting, we need to have a clear plan as to how tall account hierarchies we support. UI and API wise we don't restrict long account nested forms yet.

**Comment by deruelle** [comment]
@otsakir good thoughts on performance concerns. Actually I'm thinking if we support Impersonnation of any other accounts by Admin account as described in https://github.com/RestComm/Restcomm-Connect/issues/715. This issue here may not be needed.

**Comment by otsakir** [comment]
@deruelle , but there will still be usability issues. An administrator will have to switch between impersonated account and won't easily have an overview of things. 

I gave it some more thought and also discussed with @gvagenas. It seems that we could get away with the difficulties introduced by the hierarchies and the mess in the queries if we split the process in two steps. First we find the sub-account sids involved and then apply the rest of the filter using the resources belonging to this *set* of accounts. It seems much cleaner and easier to work with. Also, having a way to get the tree of sub-accounts, is a reusable pattern to be applied in other endpoint too.

I'll proceed with this two-step implementation roughly as described. The question can now be reduced to what will be the default filtering behavior of the additional parameter **subAccounts=true**.

**Comment by gvagenas** [comment]
@otsakir to me **subAccount=true** would mean to fetch all CDR of the account and sub-accounts no matter what is the status of the sub-accounts.

**Comment by otsakir** [comment]
@deruelle , but there will still be usability issues. An administrator will have to switch between impersonated account and won't easily have an overview of things. 

I gave it some more thought and also discussed with @gvagenas. It seems that we could get away with the difficulties introduced by the hierarchies and the mess in the queries if we split the process in two steps. First we find the sub-account sids involved and then apply the rest of the filter using the resources belonging to this *set* of accounts. It seems much cleaner and easier to work with. Also, having a way to get the tree of sub-accounts, is a reusable pattern to be applied in other endpoint too.

I'll proceed with this two-step implementation roughly as described. The question can now be reduced to what will be the default filtering behavior of the additional parameter **subAccounts=true**.

**Comment by otsakir** [comment]
Closing as fixed
