### ISSUE TITLE
Structural improvements of restcomm configuration classes

### ISSUE THREAD

**Issue by otsakir** [RestComm/Restcomm-Connect#1362]
Currently, many of the restcomm configuration properties are accessed through the MainConfigurationSet class. This is a concrete implementation that is not very flexible. For testing we still rely on initializing it from restcomm.xml and we keep editing the file to simulate configuration changes.

We can hide this implementation behind Java interfaces with getters only or setters for better decoupling. That way it will be much easier to use to construct and use in tests or allow runtime-updating at some point.

In detail, as a first step the following can be done:

- The current class implementation will renamed to *MainConfigurationSetImpl*.
- A new MainConfigurationSet interface will be introduces that will implement only getters.

**Comment by deruelle** [comment]
tied to https://github.com/RestComm/Restcomm-Connect/issues/512

**Comment by otsakir** [comment]
@gvagenas , any thoughts on the 'update/mutability' feature of the configuration classes? Anything that can help the discussion, use cases, design considerations..

**Comment by otsakir** [comment]
Closing the issue after discussing with @gvagenas. Further brainstorming will be on a separate issue dedicated on configuration mutability.
