### ISSUE TITLE
Date filtering issues in AdminUI logs

### ISSUE THREAD

**Issue by otsakir** [RestComm/Restcomm-Connect#1395]
The list view in messages, recordings and notifications displays no results if Date filter is used.

**Comment by deruelle** [comment]
Actually we should have a from date and end date as well like in Calls Logs view

**Comment by forever3000** [comment]
Hi @deruelle ,
Should we support filter on client side or server side?
Thanks and Best Regards,
Vu Nguyen

**Comment by forever3000** [comment]
Hi @deruelle ,
Should we support filter on client side or server side ?
Thanks and Best Regards
Vu Nguyen

**Comment by deruelle** [comment]
@otsakir can you comment here on how it was done for the Logs => Calls screen ?

**Comment by forever3000** [comment]
Hi @deruelle ,
As I saw, we already implemented filter on server side for Call Logs screen. So should we do the same with messages, recordings and notifications?
Thanks
Vu Nguyen

**Comment by deruelle** [comment]
@forever3000 good investigation. yes please

**Comment by forever3000** [comment]
Hi @deruelle , @otsakir,
I have modified many files for implementing these features so please help me review them.
Thanks,
Vu Nguyen

**Comment by deruelle** [comment]
Thanks @forever3000. @otsakir will try to review this week and comment back
