### ISSUE TITLE
Remove sub-account list from profile page

### ISSUE THREAD

**Issue by otsakir** [RestComm/Restcomm-Connect#1426]
Sub-accounts are displayed both in an account profile page (#profile/...), as well as in the dedicated sub-accounts view (#subaccounts/...). We need to remove this redundancy and settle with the dedicated view. It's more powerful, supports paging, sorting, filtering , searching etc.

**Comment by otsakir** [comment]
this is also part of #1496

**Comment by ammendonca** [comment]
Outdated.
