### ISSUE TITLE
Video Conferencing API 

### ISSUE THREAD

**Issue by deruelle** [RestComm/Restcomm-Connect#1432]
- [ ] General - define Video API proposal for long-term implementation
- [ ] Video conferencing – ability to create conference and add participants (SIP or WebRTC) into conference using the <dial> verb
- [ ]  Re-using what was already done / validating that audio conferencing can be updated with video. Play a video file by example should be possible on the Play verb only if XMS is used via RVD & RESTFul API & RCML
- [ ]  Video peer-to-server - ability to join clients using <dial> verb through media server (alice – restcomm/xms – bob) with the added ability to record

**Comment by ghjansen** [comment]
Duplicated. Video API is now represented by the Epic #1880 and all issues associated to it.
