### ISSUE TITLE
start-restcomm.sh and 'sed' on OS X El Capitan

### ISSUE THREAD

**Issue by peteroyle** [RestComm/Restcomm-Connect#1445]
Hello,

I've noticed in 7.9.0 that I can't start RestComm under OS X El Capitan any more. I upgraded from 7.6 (which worked for me) so not sure exactly when the "breaking" change was introduced. The issue is likely due to "BSD sed" being on the path under El Capitan, whereas the scripts seem to expect "GNU sed". I suspect this because I installed "GNU sed" via Brew and it started working.

The exact commands used when installing sed were:
$ brew install gnu-sed --with-default-names
$ PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"   

I'll attach the output of the start-restcomm.sh script both with and without this workaround.

**Comment by peteroyle** [comment]
Attached logs

Original output:
[original.txt](https://github.com/RestComm/Restcomm-Connect/files/507606/original.txt)

Output after applying workaround (installing gnu-sed):
[with_workaround.txt](https://github.com/RestComm/Restcomm-Connect/files/507607/with_workaround.txt)

**Comment by deruelle** [comment]
Thanks for reporting back @peteroyle 

@leftyb @ghjansen can you have a look ?

**Comment by gvagenas** [comment]
Provided a script to change 'sed' to 'gsed', check comments of issue #1595
