### ISSUE TITLE
Restrict SupervisorEndpoint and MonitoringEndpoint to SuperAdministrator

### ISSUE THREAD

**Issue by gvagenas** [RestComm/Restcomm-Connect#1456]
These endpoints should be accessible only to top-level accounts i.e. superadministrators.

**Comment by deruelle** [comment]
RestComm/Restcomm-Connect#1488

**Comment by maria-farooq** [comment]
created PR https://github.com/RestComm/Restcomm-Connect/pull/1933

**Comment by maria-farooq** [comment]
https://telestax.atlassian.net/browse/RESTCOMM-807
