### ISSUE TITLE
Include Restcomm XMS Documentation 

### ISSUE THREAD

**Issue by deruelle** [RestComm/Restcomm-Connect#1459]
Migrate attached doc to asciidoc. 
[Getting-started-with-Telestax-RestComm-and-PowerMedia-XMS_final.docx](https://github.com/RestComm/Restcomm-Connect/files/514737/Getting-started-with-Telestax-RestComm-and-PowerMedia-XMS_final.docx)
improve ease of integration as well as much as possible. Discuss possibility of an XMS Docker container

**Comment by deruelle** [comment]
Adding the XMS Docker Container Documentation [Running-XMS-Under-Docker.docx](https://github.com/RestComm/Restcomm-Connect/files/515500/Running-XMS-Under-Docker.docx)

Ideally we should be able to run both XMS and Restcomm in Docker for faster setup and integration

**Comment by gsaslis** [comment]
@deruelle i guess we can close this in light of #2687 ?

**Comment by deruelle** [comment]
Yes.
