### ISSUE TITLE
Making a video call from tadhack olympus to +1235 fails

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/Restcomm-Connect#1477]
TADHack server uses XMS, but I would expect it if video is not available to be able to work like RMS which is to fallback to audio-only call.

The root cause here seems to be that the server returns in the SDP answer less m-lines than where in the offer (that is 1 instead of 2), which breaks Peer Connection in the client side

Here's the [web console](https://gist.github.com/atsakiridis/082bd8af5d3031eeb0b9becf912e757f)

Here's the error: `error=OperationError: Failed to set remote answer sdp: Offer and answer descriptions m-lines are not matching. Rejecting answer.`

**Comment by ghjansen** [comment]
Issue is not happening anymore after the last upgrades performed in the environment.
