### ISSUE TITLE
Support transition for Account auth token

### ISSUE THREAD

**Issue by gvagenas** [RestComm/Restcomm-Connect#1491]
Whenever the account auth token needs be changed, we need to support a transition period, for example in order to change scripts etc.

Possible solution could be that we support 2nd auth token and the account owner later will have to update/remove.

Relates to #1386

**Comment by otsakir** [comment]
relates to https://github.com/RestComm/Restcomm-Connect/issues/1386

**Comment by deruelle** [comment]
Duplicate of https://github.com/RestComm/Restcomm-Connect/issues/2164
