### ISSUE TITLE
Update to RMS-5 and update auto-configuration scripts

### ISSUE THREAD

**Issue by hrosa** [RestComm/Restcomm-Connect#1526]
Update configuration scripts to:
- use xmlstarlet instead of sed
- use tmux instead of screen

Here is an example of usage in the RMS config scripts https://github.com/RestComm/mediaserver/issues/286

Useful guide comparing screen and tmux: http://hyperpolyglot.org/multiplexers#cmd-line-opts

**Comment by hrosa** [comment]
start-mediaserver and stop-mediaserver are working correctly. Default media server configuration is overwritten and a tmux session is started/stopped.

**Comment by gvagenas** [comment]
Last, please update documentation also for any new configuration options etc
