### ISSUE TITLE
Properly handle InDialog INVITES

### ISSUE THREAD

**Issue by croufay** [RestComm/Restcomm-Connect#1544]
Restcomm doesn't Include SDP on the 200 OK to the Re-invite
*******************************************
You mean the 200 OK on the RE-INVITE, right? This is the problem, that the 200 OK doesn’t have SDP. One quick workaround would be to use the same SDP as the original 200 OK, or otherwise change the FSM to get new SDP from RMS and include it in the 200 OK. The problem is that 200 OK on the re-invite doesn’t have SDP and the SBC there is too restrictive

The proper way is to ask RMS for new SDP based on the SDP of the re-Invite. For this you need to change the FSM and send message to RMS for new SDP the same way as for the initial INVITE

**Comment by gvagenas** [comment]
InDialog Invites for HOLD or renegotiate the SDP
