### ISSUE TITLE
Play video file - RCML

### ISSUE THREAD

**Issue by atika2k** [RestComm/Restcomm-Connect#1551]
Play video file using `<play>` verb.

Planned tasks
---
- [x] ~~Adapt RCML parser~~ (not needed)
- [x] Adapt `Jsr309CallController`
- [x] Create video demo

Unplanned tasks
---
- [x] Investigation of issues on media cache, reported in #1894
- [x] Research on `ffmpeg`, media file containers and codecs

**Comment by deruelle** [comment]
@atika2k why play and record are in the same issue ? Let's create 2 separate issues for that and track them independently

**Comment by ghjansen** [comment]
@deruelle i edited this issue and moved the `record` verb to the new issue #1767 .

**Comment by deruelle** [comment]
@ghjansen good decision
