### ISSUE TITLE
Video call via RVD

### ISSUE THREAD

**Issue by atika2k** [RestComm/Restcomm-Connect#1555]
Adapt RVD to allow video calls through `<Dial>` verb.

Planned tasks
---
- [ ] Adapt UI elements
- [ ] Adapt uploader for video files
- [ ] Adapt project scheme to save new format
- [ ] Adapt RCML provision ensuring new format
- Tests:
- [ ] Ability to create direct video call to client using `<Dial>`
- [ ] Play/record a video file
- [ ] Ability to create video call to client using Web trigger

**Comment by otsakir** [comment]
This issue was moved to RestComm/visual-designer#32
