### ISSUE TITLE
Using a bad account SID in Call creation API returns stack trace

### ISSUE THREAD

**Issue by otsakir** [RestComm/Restcomm-Connect#1568]
Instead just a 500 response with a small error description should be returned.

**Comment by forever3000** [comment]
Hi @otsakir ,
As @deruelle 's assign, I will try to handle this issue. Can you give me more details.
Thanks and Best Regards,
Vu Nguyen

**Comment by otsakir** [comment]
Hi @forever3000.

Thanks for taking the step and getting your hands dirty! ;-)

Well, i would start with registering a client, creating a call to this client using the Calls REST api like the following:

http://documentation.telestax.com/connect/api/calls-api.html#making-a-call-to-a-restcomm-client

And then replacing the Account SID in the url with (a) a totally broken account SID (like 'crappy-sid') or (b) a _syntactically valid but not existing_ SID like AC00000000000000000000000000000000.

That should do the trick.

Ping here if you need any help.

**Comment by forever3000** [comment]
Hi @otsakir ,

Sorry for bothering you more :). This's my very first time that I'm working on Restcomm-Connect so can not speed up. 
After start Restcomm-Connect server, I tested by making call between Alice and Bob on Jitsi SIP Phone to make sure server working properly.
Then I tried to make a call to SIP account as below:
`curl -X POST https://ACae6e420f425248d6a26948c17a9e2acf:5471175aea6081a114cc5c9e5bb99bae@10.211.55.4:8080/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/Calls.json -d "From=+16175551212" -d "To=sip:alice@10.211.55.4:8080" -d "Url=http://10.211.55.4:8080/restcomm/demos/hello-play.xml"`

As I understand 
ACae6e420f425248d6a26948c17a9e2acf: SID of admin account
5471175aea6081a114cc5c9e5bb99bae: maybe the auth token
10.211.55.4: my private IP
2012-04-24: I'm not sure about this one
And I always got : curl: (35) Unknown SSL protocol error in connection to 10.211.55.4:8080

May you have some advices for me. Beside that, can you give me how to register a client with curl command :).

Thanks and Best Regards,
Vu Nguyen

**Comment by otsakir** [comment]
Hi forever3000,

1. In local installations restcomm runs on plain http by default. So, you have to access the REST API under http:// and not https://.
2. ACae6e420f425248d6a26948c17a9e2acf is the SID of the account
3. 5471175aea6081a114cc5c9e5bb99bae looks like an auth token indeed. You can get from the administration console dashboard. See here for help: 
http://documentation.telestax.com/connect/admin/Restcomm%20-%20Overview%20Admin%20User%20Interface.html#dashboard
4. You don't need curl to register a sip client. You have to use a sip phone like jitsi, linphone, x-lite (for windows) etc. 
Regards

Orestis

**Comment by forever3000** [comment]
Hi @otsakir ,

Thank for your very good support. I will update to you the status asap.

Thanks and Best Regards,
Vu Nguyen

**Comment by forever3000** [comment]
Hi @otsakir ,

As my test result, when we try to create a call to registered client (Alice on Jitsi Sip Phone) using Call REST API then replacing with not exist Account SID or like AC00000000000000000000000000000000 or incorrect Auth Token, 401 (Unauthorized) response with one html page as below
[http://s.pictub.club/2016/11/30/NisMf.png](url)
.I can modify but I still don't understand why we need return 500 response in this case.

Thanks and Best Regards,
Vu Nguyen

**Comment by forever3000** [comment]
Hi @deruelle ,

I think @otsakir is off todays so can you give me more details about this issue. As my test result, I'm very confusing what should be returned in this case is correct. Should I return 500 response http or write 500 response and small error description to stack trace.

Thanks and Best Regards,
Vu Nguyen

**Comment by otsakir** [comment]
Hi @forever3000 ,

You should be able to reproduce with a curl statement that follows the pattern:

`curl ... -X POST http://192.168.2.3:8080/restcomm/2012-04-24/Accounts/crappy-sid/Calls ...`

Using this i got a 500 and a stack trace. Of course the credentials should be correct in order for your request to be accepted.

Regarding for status code that should be returned do you suggest returning something other than 500 ?

Regarding the content of the response, there is a patchy though handy method in AbstractEndpoint that may help you building your message:
https://github.com/RestComm/RestComm-Connect/blob/20c88245bfef7f66c9917ac317efe2dc202cdea9/restcomm/restcomm.http/src/main/java/org/restcomm/connect/http/AbstractEndpoint.java#L117-L117

A small string like "invalid account SID" should be enough to help the caller figure out was wrong. 


Btw, here is the (ugly) response i got:

`<html><head><title>JBoss Web/7.2.0.Final - JBWEB000064: Error report</title><style></style> </head><body><h1>JBWEB000065: HTTP Status 500 - crappy-sid is an INVALID_SID sid value.</h1><HR size="1" noshade="noshade"><p><b>JBWEB000309: type</b> JBWEB000066: Exception report</p><p><b>JBWEB000068: message</b> <u>crappy-sid is an INVALID_SID sid value.</u></p><p><b>JBWEB000069: description</b> <u>JBWEB000145: The server encountered an internal error that prevented it from fulfilling this request.</u></p><p><b>JBWEB000070: exception</b> <pre>java.lang.IllegalArgumentException: crappy-sid is an INVALID_SID sid value.
	org.restcomm.connect.commons.dao.Sid.&lt;init&gt;(Sid.java:46)
	org.restcomm.connect.http.CallsEndpoint.putCall(CallsEndpoint.java:303)
	org.restcomm.connect.http.CallsXmlEndpoint.putCall(CallsXmlEndpoint.java:69)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:606)
	com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1480)
	com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1411)
	com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1360)
	com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1350)
	com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
	com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538)
	com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
</pre></p><p><b>JBWEB000072: note</b> <u>JBWEB000073: The full stack trace of the root cause is available in the JBoss Web/7.2.0.Final logs.</u></p><HR size="1" noshade="noshade"><h3>JBoss Web/7.2.0.Final</h3></body></html>`

**Comment by deruelle** [comment]
Thanks @forever3000 ! Contribution acknowledged at https://telestax.com/acknowledgements/
