### ISSUE TITLE
All participants hear MOH

### ISSUE THREAD

**Issue by maria-farooq** [RestComm/Restcomm-Connect#1572]
Quoting JJS:
I just tried to dial into Peters conf bridge using my FONE.DO account on my SIP HArd phone. I Dialed Peters DID, <> started playing I have never heard before.  A voice I never heard before made the IVR announcement, I press 2 to get into the conf room.  The music kept playing.  I was put into Peters Confernece room, the music kept playing, everybody heard the music.  I am now a Restcomm DJ!!!!

**Comment by maria-farooq** [comment]
@deruelle @leftyb i was able to reproduce it:
Here are steps to reproduce it 

1. Register 2 clients (for example: `client-A` and `client-B`) on 2 different nodes.
2. `client-A` Dials conference as a `moderator/admin` (for example: dials 1311)
3. It will start hearing MOH.
4. `client-B` Dials conference as a `non-moderator` (for example: dials 1310)
5. Both listening to MOH.

**Comment by deruelle** [comment]
@maria-farooq can this one be closed or this is still something we need to fix ?

**Comment by maria-farooq** [comment]
@deruelle this one is not fixed yet.

**Comment by deruelle** [comment]
@maria-farooq can we close this one ?

**Comment by maria-farooq** [comment]
yes
