### ISSUE TITLE
Provide Japaneese translation for RVD

### ISSUE THREAD

**Issue by croufay** [RestComm/Restcomm-Connect#1582]
Provide Localization feature for RVD

Users of Restcomm-Connect RVD will like to be able to access RVD in local languages like Japanese, French, Spanish, etc..

**Comment by otsakir** [comment]
@croufay , RVD already has that feature and supports English, Spanish and Portuguese right now. Also, its relatively easy to translate to new languages as well as the literals are in separate files.

**Comment by croufay** [comment]
@otsakir ,

What if we want to support Japanese, how would we go about that?


Regards

Charles

**Comment by otsakir** [comment]
@croufay, we need a translation file like the following in the target language:

https://github.com/RestComm/Restcomm-Connect/tree/73b80e617ce04f0684213b59f9b4e25007af70e3/restcomm/restcomm.rvd/src/main/webapp/languages

What other languages do you have in mind ?

**Comment by croufay** [comment]
@otsakir ,

The only other language will be Arabic.

**Comment by otsakir** [comment]
@croufay , i renamed this issue to "Provide Japaneese translation for RVD". Can you also create another issue for the Arabic language ?

**Comment by otsakir** [comment]
This issue was moved to RestComm/visual-designer#26
