### ISSUE TITLE
move Default Welcome RVD message to configuration file

### ISSUE THREAD

**Issue by croufay** [RestComm/Restcomm-Connect#1605]
the default message is current here and should be move to a configuration file so that white labeling could be easier.
https://github.com/RestComm/Restcomm-Connect/blob/4cb3186007f31a469d6a4738af7f671f9937137d/restcomm/restcomm.rvd/src/main/java/org/restcomm/connect/rvd/model/client/ProjectState.java#L38

**Comment by gsaslis** [comment]
Looks like this should be moved over to https://github.com/RestComm/visual-designer ?

**Comment by deruelle** [comment]
@gsaslis yes @otsakir can you take care of this ?

**Comment by otsakir** [comment]
Issue moved to [RestComm/visual-designer #159](https://github.com/RestComm/visual-designer/issues/159) via [**ZenHub**](https://www.zenhub.com/)
