### ISSUE TITLE
RestComm sends EndSignal and PlayAnnouncement signal simultaneously

### ISSUE THREAD

**Issue by hrosa** [RestComm/Restcomm-Connect#1622]
This can cause unpredictable behaviour on Media Server side. Instead, RC should send EndSignal and wait for response from RMS before sending the play.

As described on https://github.com/RestComm/Restcomm-Connect/issues/1621

**Comment by abdulazizali77** [comment]
@gvagenas Are you currently working on this issue (or #1621, #1623)? If not i would like to have a go at it

**Comment by gvagenas** [comment]
Hi @abdulazizali77 none is working on those issues and it would be great if you want to take over and work on them.

**Comment by abdulazizali77** [comment]
Thanks @gvagenas . 
I notice that the in-progress tag is hardly used, so its hard to tell whether an assigned issue is being worked on or not. 
Additionally some fixed issues dont seem to be set to closed.... :)

**Comment by maria-farooq** [comment]
Good point @abdulazizali77 about `in progress` label, i agree that we should use it to make things more clear.
Thanks for raising the point.
by the way is this `in progress`?

Thanks
-Maria-

**Comment by abdulazizali77** [comment]
Yes @maria-farooq, #1621 and #1622 both seem to stem from problems in `VoiceInterpreter` on conference instances. Im not too sure yet with #1623, but all of them revolve around conference so im sort of addressing the three in tandem. Do you have any advice?

**Comment by abdulazizali77** [comment]
@maria-farooq @gvagenas @deruelle 
Seems my initial idea should still apply, i will potentially add substates to `MgcpMediaGroup` Active state, `VoiceInterpreter` Conferencing state and preverify and consume the commands in the RCML. 
I have not completely ascertained where, but potentially `IvrEndpoint` `Call` `Bridge` `Conference`  the `*Controllers`, maybe `GenericEndpoint` will also need to be changed
The Request-Response path from `VoiceInterpreter` all the way to `MediaGateway` is a long and messy one..

**Comment by maria-farooq** [comment]
Thanks Abdul.Aziz,
Can you please share a sequence diagram as per your idea,
Best regards 
Maria

**Comment by maria-farooq** [comment]
Hi @abdulazizali77 ,

Do we have any update on it, i see `in progress` label to this issue.

thanks
Maria

**Comment by maria-farooq** [comment]
as per discussion lets implement https://github.com/RestComm/Restcomm-Connect/issues/2024 instead
