### ISSUE TITLE
RestComm sends EndSignal to unknown IVR endpoint

### ISSUE THREAD

**Issue by hrosa** [RestComm/Restcomm-Connect#1623]
Simple scenario: calling +1311 (conference moderator) with nobody else in the bridge.
We can see in the pcap that RC sends an end signal to /mobicents/ivr/$ (using ANY wildcard).

This operation should not be allowed as the result can be unpredictable as it can interrupt literally ANY ivr endpoint in the media server. It can also register RestComm to listen to events happening on unknown endpoint.

[rqnt-wildcard-not-allowed.pcapng.zip](https://github.com/RestComm/Restcomm-Connect/files/630911/rqnt-wildcard-not-allowed.pcapng.zip)

**Comment by maria-farooq** [comment]
@hrosa can you please check if it is still happening? as i remember some refactoring went through for rms5 upgrade and it should not be happening now. or can you provide steps to reproduce so we close or implement this issue?

**Comment by maria-farooq** [comment]
it was bcz of an extra ivr we were creating and it was fixed during rms5 upgrade

**Comment by maria-farooq** [comment]
it is also irrelevant after implementing #2024
