### ISSUE TITLE
Investigate integration of Amazon Lex 

### ISSUE THREAD

**Issue by deruelle** [RestComm/Restcomm-Connect#1626]
https://aws.amazon.com/lex/

Provide potentially a new API in Restcomm to be able to plug Lex, Watson, etc

**Comment by muhammadbilal19** [comment]
Really cool new feature of amazon, i wanted to get my hand dirty with it. I started reading documentation and also register myself in the waiting list to try Lex on amazon free tier let see when amazon allow me to play with it. I will share my experience once i have something to share.

**Comment by deruelle** [comment]
Great @muhammadbilal19. Please keep me updated on this.

**Comment by deruelle** [comment]
Closing and moving this one to https://github.com/RestComm/mediaserver/issues/406.

**Comment by muhammadbilal19** [comment]
yes I want to . For my current customer I am playing with https://api.ai/
which is provided by google. I will start looking into Lex again.

**Comment by deruelle** [comment]
@muhammadbilal19 the new issue is actually part of a broader issue https://github.com/RestComm/mediaserver/issues/284 (you can install zenhub to see the epic) that includes https://github.com/RestComm/mediaserver/issues/370 for Google if you prefer.

**Comment by muhammadbilal19** [comment]
Ohh that's great I will look into both the issues tomorrow morning and will let you know in which part I can help.

**Comment by deruelle** [comment]
ok great. Comment directly on  RestComm/mediaserver#284 so that @hrosa can guide as there is also another contributor working on this for IBM Watson
