### ISSUE TITLE
Date Ordering over multiple pages is not working correctly

### ISSUE THREAD

**Issue by deruelle** [RestComm/Restcomm-Connect#1635]
Notice below how First Page is at 30 September
![screenshot from 2016-12-08 10-47-34](https://cloud.githubusercontent.com/assets/54279/21005114/c774fc7a-bd33-11e6-8cfd-ba8ef5792b06.png)

and last page is at 8th December
![screenshot from 2016-12-08 10-47-23](https://cloud.githubusercontent.com/assets/54279/21005130/da7b2d62-bd33-11e6-9f14-bcfb48e22a49.png)

The ordering is done on the client side while it should be done on the server side otherwise it can't work through page filtering

**Comment by forever3000** [comment]
Hi @deruelle ,
I'm developing this issue : https://github.com/RestComm/Restcomm-Connect/issues/1395 and have same issue with messages, recordings and notifications. So can I also try on this issue?
Thanks

**Comment by deruelle** [comment]
@forever3000 that would be great !

**Comment by forever3000** [comment]
Hi @deruelle ,
As I understand your want, once date reverse is selected the list should be reversed through all pages? The last calls should be in first page and the very first calls should be in last page?
Thanks

**Comment by deruelle** [comment]
Correct @forever3000

**Comment by forever3000** [comment]
Hi @deruelle ,
Sorry I forgot to create other branch for this issue so when I try to make the new pull request, it is merged to the previous commit. Please help me review.
If everything is ok, I will fix this issue for message, notification, recording and transcription too.
Thanks

**Comment by deruelle** [comment]
@forever3000 can you create a pull request for this one so it gets reviewed by @otsakir  ?

**Comment by forever3000** [comment]
Hi @deruelle ,

I finish this one https://github.com/RestComm/Restcomm-Connect/issues/1395 and create pull request first then I push some commits more to fix this issue, those has been merged to the last pull request because last pull request still be in review. So may you give me some advices for the better.

Thanks and Best Regards,
Vu Nguyen
