### ISSUE TITLE
Make olympus port configurable for http and https

### ISSUE THREAD

**Issue by croufay** [RestComm/Restcomm-Connect#1647]
I tested the new Olympus during the training in Utah and I noticed that we are no longer able to change the websocket port
the problem we had was that WS is set to port 5082 and WSS is set to port 5083 in Restcomm config. When you try to login into Olympus, it defaults to port 5082 which fails when you have HTTPS enabled.

1. I think we should somehow configure it to default to 5083 when https is enabled and 5082 for http. I mean without having to do anything manually

A point to note about make the port permanent is this, if you want to route traffic through the LB, the LB might be listening on a different port and you will need to make sure the port for Olympus matches the LB. This is especially so if you want to run the LB and the Restcomm on the same machine. 

I will suggest we detect HTTP and HTTPS for and apply the default ports 5082 and 5083 according but still leave an option to manually modify the ports.

Charles

**Comment by ammendonca** [comment]
This is now implemented.
