### ISSUE TITLE
When verb is Dial, delay 200 OK to INVITE until outbound dial answers

### ISSUE THREAD

**Issue by gvagenas** [RestComm/Restcomm-Connect#1649]

**Comment by gvagenas** [comment]
@kacmos please provide documentation for the feature

**Comment by kacmos** [comment]
@gvagenas What kind of information do you need? 
Sequence diagram with new call flows...?
Description of changes?

**Comment by gvagenas** [comment]
@kacmos if you can please create a document with the description of the feature, when to use, how to configure and 1-2 example call flows and important aspects of the feature, and then we can documentation writer to add it to the Restcomm docs.

**Comment by kacmos** [comment]
George,
I attach the document. Let me know if it's ok.
[Issue1649 delay 200 ok to invite.docx](https://github.com/RestComm/Restcomm-Connect/files/744269/Issue1649.delay.200.ok.to.invite.docx)

**Comment by gvagenas** [comment]
Thanks @kacmos , I will check document and let you know if anything needed.

**Comment by abdulazizali77** [comment]
@gvagenas Thanks, i will look into this

**Comment by abdulazizali77** [comment]
@gvagenas Apparently you had already merged the implementation for this enhancement by @kacmos on 16th and 19th Jan ? So im not sure why i was assigned this :D
I havent completely tested/verified the call flows yet, but what else is there to be done for this enhancement?

**Comment by gvagenas** [comment]
Sorry @abdulazizali77 , that was by mistake. Thanks

**Comment by abdulazizali77** [comment]
@gvagenas A good learning exercise nonetheless :+1:
