### ISSUE TITLE
Have an option to play back the prompt in RVD if user didn't enter DTMF

### ISSUE THREAD

**Issue by deruelle** [RestComm/Restcomm-Connect#1660]
Right now if the user fails to enter DTMF on time, the call is hung up automatically. Instead of hanging up we should play the prompt at least 1 or 2 times to leave the user a chance to enter DTMF correctly. 

We currently have a box for Validation 'Say if invalid' (which miss language, male and female choice too) maybe we should have one for Timeout as well in case no option was entered so a developer can input a text like I'm sorry we didn't recognize any numbers.

comments @otsakir @ipsilantide ?

**Comment by ipsilantide** [comment]
Yes that make sense. There should be at least one notification before hang up. May be we should let the user to choose the number of the reminders. About the voice male/female maybe we should give somehow the chance to the user to choose it for the whole app. Does it make sense to change it from one verb to another?

**Comment by otsakir** [comment]
This issue was moved to RestComm/visual-designer#22
