### ISSUE TITLE
Return different error (500) when RCML problem.

### ISSUE THREAD

**Issue by leftyb** [RestComm/Restcomm-Connect#1663]
Change `Exception` for `Problem`, for log parsing/warning reasons. 
```xml
<![CDATA[SIP/2.0 503 Problem to setup services
...
Reason: Exception,while,trying,to,download,RCML LoadBalancer Exception
Content-Length: 0

]]>```

**Comment by gvagenas** [comment]
@leftyb you want to change the error message in the Reason Header or you want to return different error response?

**Comment by deruelle** [comment]
@gvagenas both.

**Comment by gvagenas** [comment]
@deruelle what error response should we return?

**Comment by deruelle** [comment]
@gvagenas 500 as described in the title
