### ISSUE TITLE
RVD/ES response parsing error should be more discrete in log

### ISSUE THREAD

**Issue by otsakir** [RestComm/Restcomm-Connect#1666]
When an ES response fails to get parsed, for example when a String property is expected but an Object is found instead), a much too verbose Exception trace appears in the logs. This error can very easily be produced by an improperly configured RVD application (a user action) and lead to restcomm log flooding. 

Just a warning with a proper description would be enough.

**Comment by deruelle** [comment]
15:20:58,279 ERROR [org.restcomm.connect.rvd.http.resources.RvdController] (http-/10.0.0.14:80-3) No primitive value found (maybe null returned?): org.restcomm.connect.rvd.interpreter.exceptions.BadExternalServiceResponse: No primitive value found (maybe null returned?)

**Comment by deruelle** [comment]
@otsakir do we report it in application logs as well ?

**Comment by otsakir** [comment]
@deruelle , yes. All exceptions get logged in the RVD application log if enabled.

**Comment by otsakir** [comment]
Hi @panoski. Here are some tips to help you get started:

* All requests for RCML pass through RvdController:runInterpreter(). That's the key point where exception handling occurs and probably where you'll have to apply your patch. 
* As already noted, the problem is that the exception reporting is too verbose. To reproduce,  you'll probably need to create an RVD application with an ES element that fails to process the responses it gets. The resources may come in handy:

http://www.mocky.io/ - this will help you create custom responses
http://documentation.telestax.com/connect/rvd/Restcomm%20-%20Quick%20External%20Service%20Demo.html#configure-externalservices-module - just create an assignment, forget about module scope stuff
http://documentation.telestax.com/connect/rvd/Restcomm%20-%20Quick%20External%20Service%20Demo.html#video - a bit outdated

Ping me if you need any more help.

Orestis

**Comment by panoski** [comment]
Hi @otsakir.

I added in the line 109 of RvdController the above code
catch (BadExternalServiceResponse e) {
	logger.warn(e.getMessage());
	if (rvdContext.getProjectSettings().getLogging())
		rvdContext.getProjectLogger().log(e.getMessage()).tag("app", appname).tag("EXCEPTION").done();
	rcmlResponse = Interpreter.rcmlOnException();
}

Let me know if this patch is what you want.
Thank you.

**Comment by otsakir** [comment]
Hi @panoski,

This issue is about producing less verbose messages in case the ES response is not parsed correctly. For whatever reason, RVD may produce an error when trying to consume a response. We need to make this short.

I noticed that you only cach BadExternalService response. Note that it may not only be a BadExternalServiceResponse exception that is thrown. I think (though not sure) i had come accross some other cases too. It's important to experiment with all sorts of responses to search for corner cases. Create an RVD application, put an ES element with an assignment in it, setup a test server whose responses  you can control and start playing around. At the same time check your log for exceptions.

Regards

**Comment by otsakir** [comment]
Hi @panoski. Thanks for getting into that.

I went through your patch. Error handling can be really tricky at times. If you mute all _Exceptions_ then even critical exceptions will be summarized and their stack trace will be hidden. For example, if sth really wrong happens at storage level like if the project files are trashed, then we won't be have the stack trace available. 

The point here is that you have to separate the errors that originate form the _user_ from those that come from the RVD _system_. And that has to be done at the lower layers from the code that can tell one from another. 

IMO, your first attempt was in the right direction. What is further needed is to catch the MalformedJsonException error early enough and rethrowing as BadExternalServiceResponse. That way your lower layers will make sure that the library exceptions (e.g. MalformedJsonException) are assigned the proper semantic value (by be rethrowed as BadExternalServiceResponse) and the upper layers will just need to mute the exceptions they care about i.e. BadExternalServiceResponse. The rest will be displayed verbosely with full stack trace. 

Panos, does this make any sense ? Please ping me if you have any more questions.

Regards

**Comment by otsakir** [comment]
Hi @panoski.

I noticed you have commited a new patch but at the same time you closed the PR of the issue. Are you still on it ?

**Comment by otsakir** [comment]
closing this as of 9c6a8f3
