### ISSUE TITLE
Application not visible in Restcomm numbers "Features" column when assigned to a USSD RVD project

### ISSUE THREAD

**Issue by FerUy** [RestComm/Restcomm-Connect#1691]
When a new number is registered and assigned to an RVD application, it becomes visible only if it is assigned to an SMS or Voice application, but not if assigned to an USSD one. 
See attached images.

![restcomm_ussd_rvd_app_example](https://cloud.githubusercontent.com/assets/14883482/21661868/4249c5d4-d2b5-11e6-9fb0-8e4d1058b510.png)

![restcomm_ussd_numbers](https://cloud.githubusercontent.com/assets/14883482/21661873/456683ce-d2b5-11e6-8ad4-b0c0ffeea194.png)

**Comment by deruelle** [comment]
@FerUy do you want to try to fix it ?
