### ISSUE TITLE
Live call modification throws error

### ISSUE THREAD

**Issue by vmykhailiuk** [RestComm/Restcomm-Connect#1700]
Trying to perform call transfer by using Live Call Modification. Client bob calls client carol and while call is in-progress I run following command line:

curl -XPOST -u user:password http://192.168.1.3:8080/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/Calls.json/CA5a2d4f0f3bdb46c7aba0d78923b3469a -d "Url=http://192.168.1.3:8080/restcomm-rvd/services/apps/AP85e9ec395ba44e189bc52a4c5169f5c8/controller"

However, command fails with Futures timed out after [10 seconds]

By debugging Restcomm source (release 8.0.0.1114) I found source of the issue, it's

`cdr = dao.getCallDetailRecord(new Sid(callSid));`
`...`
`callPath = cdr.getCallPath(); // == NULL`
`Future future = (Future) ask(callManager, new GetCall(callPath), expires);`

in https://github.com/RestComm/Restcomm-Connect/blob/8.0.0.1114/restcomm/restcomm.http/src/main/java/org/restcomm/connect/http/CallsEndpoint.java (lines 446-448)

Logs:
network trace https://github.com/vmykhailiuk/issues/blob/master/sip.pcapng
log https://github.com/vmykhailiuk/issues/blob/master/server.log

Is it working as designed or it's a bug?

**Comment by gvagenas** [comment]
Thanks for reporting @vmykhailiuk . Will update you on the progress

**Comment by gvagenas** [comment]
@vmykhailiuk you are trying to execute LCM on a P2P call which is not supported. 
LCM is supported on calls that are created with Dial verb.

In your case, you should have an RCML application with <Dial><Client>Carol</Client></Dial> and then execute LCM on this call.

**Comment by vmykhailiuk** [comment]
Thank you @gvagenas. I suspected it's supported only for such calls, but documentation was lacking.

**Comment by gvagenas** [comment]
@vmykhailiuk I added more logs and updated the documentation for such cases

**Comment by deruelle** [comment]
@gvagenas shall we also report a notification to the user so that if that fails they can see it from the API or Dashboard on why the LCM failed ?
