### ISSUE TITLE
UsageEndpoint integration test

### ISSUE THREAD

**Issue by otsakir** [RestComm/Restcomm-Connect#1711]
There is no arquilian test for the UsageEndpoint currently. We need to add one.

**Comment by abdulazizali77** [comment]
@otsakir this is a duplicate of #1698 ? When i worded 'test suite' i meant integration test

**Comment by otsakir** [comment]
oops, you 're right @abdulazizali77. I missed your issue (#1698) when i created this. Closing this as duplicate.
