### ISSUE TITLE
RESTfull response inconsistencies - II

### ISSUE THREAD

**Issue by otsakir** [RestComm/Restcomm-Connect#1738]
The following request reveal mostly minor inconsistencies wrt to the uri/subresource_uris fields returned:

1. http://this:8080/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/IncomingPhoneNumbers.json

    Response still contains the 'restcomm' part:

    "uri": "/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/IncomingPhoneNumbers/PNdd7a0a0248244615978bd5781598e5eb.json"

2. This is dead (returns 404). There is no REST method for this path. 
http://this:8080/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/AvailablePhoneNumbers.json

3. Calls list method has no .json suffix in 'subresource_uris'
test uri: 
    http://this:8080/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/Calls.json
response:
    ...
      "subresource_uris": {
        "notifications": "/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/Calls/CA1cbea362aaef4482a941af600f3f7f05/Notifications",
        "recordings": "/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/Calls/CA1cbea362aaef4482a941af600f3f7f05/Recordings"
    ...
    
4. Errors /2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/Conferences.json
 /2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/Conferences.json

    a. 'last_page_uri' looks like: "last_page_uri": "/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/Conferences.json?Page\u003d0\u0026PageSize\u003d50" ( '=', '&' are encoded)
    b. 'conferences.participants' looks like: /2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/Conferences/CF1e4a2e67ada54298a83b93818c0ea1e4/Participants (no .json extension)
    c. 'subresource_uris' is empty - {} 

This issue extends fixes started in #1723 .

**Comment by abdulazizali77** [comment]
@otsakir I guess i should look at these! :D
Potentially this should be linked to #898

**Comment by deruelle** [comment]
@abdulazizali77 assigned to you

**Comment by otsakir** [comment]
Issue fixed. Merged by #1801.
