### ISSUE TITLE
Dashboard doesn't provide options to change client's password

### ISSUE THREAD

**Issue by gvagenas** [RestComm/Restcomm-Connect#1741]
can only change friendly name

**Comment by gvagenas** [comment]
Client can change if we click on the Username of the client but its not obvious, while the pen icon that appears when mouse over the client, only changes the name

**Comment by ammendonca** [comment]
The client password can be changed in the clients details page

![image](https://user-images.githubusercontent.com/1737954/35677680-85125c6e-0748-11e8-83ba-afe00533a65b.png)
