### ISSUE TITLE
Hide empty URLs in numbers list

### ISSUE THREAD

**Issue by otsakir** [RestComm/Restcomm-Connect#1761]
The request urls appear crowded  in the numbers list. 

![crowded_urls](https://cloud.githubusercontent.com/assets/8972800/22586121/c09dea7c-ea03-11e6-8d52-9605f019a66f.png)

In case they are empty maybe it's better to hide them altogether.

**Comment by otsakir** [comment]
After patch it looks like this:

![empty_urls_hidden](https://cloud.githubusercontent.com/assets/8972800/22587299/d03b464a-ea09-11e6-8090-6aa4f3f27d1c.png)

**Comment by ipsilantide** [comment]
Great!
