### ISSUE TITLE
Many tcp connections left in TIMED_WAIT mode

### ISSUE THREAD

**Issue by hrosa** [RestComm/Restcomm-Connect#1803]
After a clean test run, the netstat file shows many tcp connection left in TIMED_WAIT state.

[restcomm_2017-02-11_02_52.tar.gz](https://github.com/RestComm/Restcomm-Connect/files/769452/restcomm_2017-02-11_02_52.tar.gz)

**Comment by deruelle** [comment]
@hrosa this issue doesn't really tell anything about which test was done nor steps to reproduce the issue.

**Comment by gvagenas** [comment]
@hrosa all ports at TIMED_WAIT mode are in the port 8080 for HTTP. What test you run? 

Also TIMED_WAIT seems to be a normal state for TCP connections:
```
TIME_WAIT is normal. It's a state after a socket has closed, used by the kernel to keep track of packets which may have got lost and turned up late to the party. A high number of TIME_WAIT connections is a symptom of getting lots of short lived connections, not nothing to worry about.
```

**Comment by hrosa** [comment]
ok, tks for confirming @gvagenas
