### ISSUE TITLE
Upgrade to Media Server 6.0

### ISSUE THREAD

**Issue by hrosa** [RestComm/Restcomm-Connect#1821]
Configure the build process to use the upcoming version of RestComm Media Server 6.0.

**Comment by maria-farooq** [comment]
corresponding epic in jira https://telestax.atlassian.net/browse/RESTCOMM-791

**Comment by deruelle** [comment]
All remaining issues have been moved to https://github.com/RestComm/Restcomm-Connect/issues/1909
