### ISSUE TITLE
Exception handling in all AKKA actors

### ISSUE THREAD

**Issue by maria-farooq** [RestComm/Restcomm-Connect#1829]
We have been facing many issue where an exception that trace back to `onReceive` method causes death of actor and reinitialisation.
Having said that we having been dealing with issue by overriding postStop method and finding reason of exception.
At the same time none of `onReceive` method is protected by a simple try/catch.
i think we should think about it unless i am missing something.
please keep in view that all AKKA actor reply in asynchronous way (most of the time), and in case of actor's being dead/reinitialization a `sender` might wait for unreasonable amount of time.
by adding `try/catch` in `onReceive` we can respond with some general ERROR response so that `sender`/`observers` can take further action

**Comment by gvagenas** [comment]
@maria-farooq can you point to logs that shows the reasons of actor death?

**Comment by maria-farooq** [comment]
@gvagenas we can make a simple test to reproduce this with any AKKA actor.

**Comment by gvagenas** [comment]
@maria-farooq how can we reproduce it? Can you try to provide a test case in the testsuite?

**Comment by maria-farooq** [comment]
@gvagenas yes i added a experimental test case in mrb tests.
here is quick trace:

```
[INFO] [02/20/2017 13:46:57.278] [default-akka.actor.default-dispatcher-4] [akka://default/user/$a] turnOnMediaGateway local ip: 127.0.0.1 local port: 2727 remote ip: 127.0.0.1 remote port: 2427
[INFO] [02/20/2017 13:46:57.278] [default-akka.actor.default-dispatcher-4] [akka://default/user/$a]  ********** MockMediaResourceBroker akka://default/user/$a Processing Message: java.lang.String
[ERROR] [02/20/2017 13:46:57.281] [default-akka.actor.default-dispatcher-4] [akka://default/user/$a] null
java.lang.NullPointerException
	at org.restcomm.connect.telscale.mrb.mock.MockMediaResourceBroker.testExceptionOnRecieve(MockMediaResourceBroker.java:65)
	at org.restcomm.connect.telscale.mrb.mock.MockMediaResourceBroker.onReceive(MockMediaResourceBroker.java:59)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:159)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425)
	at akka.actor.ActorCell.invoke(ActorCell.scala:386)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230)
	at akka.dispatch.Mailbox.run(Mailbox.scala:212)
	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)

[INFO] [02/20/2017 13:46:57.308] [default-akka.actor.default-dispatcher-5] [akka://default/user/$a] MRB Mock post stop called
[INFO] [02/20/2017 13:46:57.308] [default-akka.actor.default-dispatcher-5] [akka://default/user/$a] MRB on post stop
```

**Comment by gvagenas** [comment]
Thanks @maria-farooq, I will give this issue high priority.

**Comment by gvagenas** [comment]
@maria-farooq send me the link to the test case

**Comment by maria-farooq** [comment]
@gvagenas 
Test: `https://bitbucket.org/telestax/telscale-restcomm/src/RESTCOMM-766/restcomm/telscale-restcomm-connect.mrb/src/test/java/org/restcomm/connect/mrb/MediaResourceBrokerTestExceptionHandling.java`
Mock Class: `https://bitbucket.org/telestax/telscale-restcomm/src/RESTCOMM-766/restcomm/telscale-restcomm-connect.mrb/src/main/java/org/restcomm/connect/telscale/mrb/mock/MockMediaResourceBroker.java?fileviewer=file-view-default#MockMediaResourceBroker.java-59`

**Comment by hrosa** [comment]
@maria-farooq @gvagenas This is surely a must to ensure RestComm stability. But was wondering if Akka doesn't provide any error handling mechanism for actors?
