### ISSUE TITLE
Voice gender is shown by RVD even if not supported

### ISSUE THREAD

**Issue by ghjansen** [RestComm/Restcomm-Connect#1835]
Some TTS platforms (like VoiceRSS) doesn't support male voice, so even choosing it by the configuration of a `<Say>` verb, the audio is synthesised using female voice. That could cause some confusion for users since the end result would be different that the predefined configuration.

In the other hand, other TTS services support male and female genders, so it doesn't feels right to me to control the visibility of the components based on RestComm TTS configuration, because the RCML application should always keep the information of preferred gender. So what about a informative tooltip or a message somehow explaining in few words this "worst case scenario"? Thoughts? Not sure if worth the hassle, just thinking out loud.

@otsakir ? @ipsilantide ?

**Comment by otsakir** [comment]
This issue was moved to RestComm/visual-designer#31
