### ISSUE TITLE
When using the Search function in Numbers tab, system returns a 404

### ISSUE THREAD

**Issue by ipsilantide** [RestComm/Restcomm-Connect#1867]
@scottbarstow commented on [Tue Jan 31 2017](https://github.com/RestComm/graphics-design/issues/76)

This is in Search existing numbers, not searching for Provider numbers

Get the following error:

JBWEB000065: HTTP Status 404 - /search

JBWEB000309: type JBWEB000067: Status report

JBWEB000068: message /search

JBWEB000069: description JBWEB000124: The requested resource is not available.

JBoss Web/7.2.0.Final

---

@deruelle commented on [Tue Feb 07 2017](https://github.com/RestComm/graphics-design/issues/76#issuecomment-277938247)

@scottbarstow I can't reproduce on cloud. Can you provide the steps to reproduce and potentially some screenshots ?

---

@scottbarstow commented on [Tue Feb 07 2017](https://github.com/RestComm/graphics-design/issues/76#issuecomment-278009433)

Type a value into search. It filters down. If you then hit enter, you get the error. See attached @deruelle 

![screen shot 2017-02-07 at 9 05 50 am](https://cloud.githubusercontent.com/assets/746403/22694315/bfa3e432-ed14-11e6-94f3-a012fe4ddcc6.png)

![screen shot 2017-02-07 at 9 06 01 am](https://cloud.githubusercontent.com/assets/746403/22694317/c32018ba-ed14-11e6-930a-dd993c6e0a0a.png)

---

@deruelle commented on [Wed Feb 08 2017](https://github.com/RestComm/graphics-design/issues/76#issuecomment-278267927)

Thanks @scottbarstow. Confirmed. Assigning to @brainslog and tied to https://github.com/RestComm/Restcomm-Connect/issues/1455

**Comment by ipsilantide** [comment]
moved here from design repository

**Comment by muhammadbilal19** [comment]
@deruelle this bug is also available in client tab as well. Current functionality is only fetching values from current filter records (which are visible on the current page). On pressing enter button form submit request generated from system which causes 404. 
Do we need to provide remote filtering functionality for Numbers ?

**Comment by deruelle** [comment]
> Do we need to provide remote filtering functionality for Numbers ?

What would be the filtering criterias ?

**Comment by muhammadbilal19** [comment]
@deruelle look like to me only friendly_name and phone_number not sure if customer want any other field for searching in this table.

**Comment by deruelle** [comment]
@muhammadbilal19 those makes sense. if you can take care of it as part of the PR that would be great.

**Comment by muhammadbilal19** [comment]
@deruelle sure i will create PR for that soon.

**Comment by ammendonca** [comment]
Outdated.
