### ISSUE TITLE
When searching for numbers the error message should appear vertically centered

### ISSUE THREAD

**Issue by ipsilantide** [RestComm/Restcomm-Connect#1868]
@otsakir commented on [Thu Dec 22 2016](https://github.com/RestComm/graphics-design/issues/61)

![adminui_issue3](https://cloud.githubusercontent.com/assets/8972800/21424710/31c56974-c84d-11e6-99d6-8c2d07c24cf8.png)

**Comment by ipsilantide** [comment]
moved here from design repository

**Comment by ammendonca** [comment]
Outdated.
