### ISSUE TITLE
When you add a contact that already exist you shouldn't have it twice

### ISSUE THREAD

**Issue by ipsilantide** [RestComm/Restcomm-Connect#1869]
@ipsilantide commented on [Tue Feb 21 2017](https://github.com/RestComm/olympus/issues/92)

We need an alarm when someone is entering a contact that already exist. This way we will not have the problem of having the same contact many times.

---

@ipsilantide commented on [Tue Feb 21 2017](https://github.com/RestComm/olympus/issues/92#issuecomment-281310009)

moved here from design repository

**Comment by ipsilantide** [comment]
moved here from design repository

**Comment by ammendonca** [comment]
Duplicate of https://github.com/RestComm/olympus/issues/92, and it's fixed.
