### ISSUE TITLE
Restcomm Apps drop area overlaps UI buttons

### ISSUE THREAD

**Issue by ipsilantide** [RestComm/Restcomm-Connect#1870]
@otsakir commented on [Thu Dec 22 2016](https://github.com/RestComm/graphics-design/issues/60)

![adminui_issue1](https://cloud.githubusercontent.com/assets/8972800/21424644/de355e5e-c84c-11e6-8b0b-8448c29bebda.png)

---

@otsakir commented on [Thu Dec 22 2016](https://github.com/RestComm/graphics-design/issues/60#issuecomment-268824440)

Not sure if the patch above is the ideal in terms of UI. If fixes the overlap though. It now looks like this:

![adminui_issue_design_60](https://cloud.githubusercontent.com/assets/8972800/21430742/155460cc-c86d-11e6-9e54-60f379cb0994.png)

**Comment by ipsilantide** [comment]
moved here from design repository

**Comment by ammendonca** [comment]
Outdated.
