### ISSUE TITLE
We need to make Dashboard Responsive for Smart phones

### ISSUE THREAD

**Issue by ipsilantide** [RestComm/Restcomm-Connect#1872]
@ipsilantide commented on [Fri Dec 16 2016](https://github.com/RestComm/graphics-design/issues/44)

We need to make sure that we are responsive and we provide a great UX to the user of the mobiles

**Comment by ipsilantide** [comment]
moved here from design repository

**Comment by ammendonca** [comment]
Done as part of latest revamp.
