### ISSUE TITLE
The verbs needs to follow the scroll.

### ISSUE THREAD

**Issue by ipsilantide** [RestComm/Restcomm-Connect#1873]
@ipsilantide commented on [Fri Dec 02 2016](https://github.com/RestComm/graphics-design/issues/35)

When you add verbs there is a time that you need to scroll. We will provide a better UX if the verbs follow the scroll by moving down.

**Comment by ipsilantide** [comment]
moved here from design repository

**Comment by otsakir** [comment]
This issue was moved to RestComm/visual-designer#29

**Comment by otsakir** [comment]
This issue was moved to RestComm/visual-designer#30
