### ISSUE TITLE
Remove start up module

### ISSUE THREAD

**Issue by ipsilantide** [RestComm/Restcomm-Connect#1877]
@ipsilantide commented on [Wed Oct 12 2016](https://github.com/RestComm/graphics-design/issues/17)

Remove the start up module. and put it as an option in the modules dropdown to save space.

---

@ipsilantide commented on [Tue Feb 21 2017](https://github.com/RestComm/graphics-design/issues/17#issuecomment-281325979)

to think about

**Comment by otsakir** [comment]
This issue was moved to RestComm/visual-designer#28
