### ISSUE TITLE
Record maxLength parameter should be in units of 100ms

### ISSUE THREAD

**Issue by hrosa** [RestComm/Restcomm-Connect#1881]
The Record maxLength parameter must be converted from seconds to units of 100ms, just like it's done for timeout parameter.

**Comment by maria-farooq** [comment]
@hrosa i see a commit is referenced towards this issue.
does that mean this is done, or is there more to implement here.
Thanks
-Maria-

**Comment by hrosa** [comment]
I believe this does the trick. You can re-use that branch to test further and validate if everything is ok before merging.

**Comment by maria-farooq** [comment]
ok @hrosa 
thanks
-Maria-
