### ISSUE TITLE
Support nullable FinishOnKey for Recording

### ISSUE THREAD

**Issue by hrosa** [RestComm/Restcomm-Connect#1886]
The RCML should be able to support nullable FinishOnKey parameter for Recording.
MGCP-wise, the default value is "*". To disable it, the parameter "eik" must be explicitly set to "null".

https://tools.ietf.org/html/rfc2897#section-5

>    End Input Key:
> 
>       Specifies a key that signals the end of digit collection or voice
>       recording. The default end input key is the # key. To specify that
>       no End Input Key be used the parameter is set to the string
>       "null".  The default behavior not to return the End Input Key in
>       the digits returned to the call agent.  This behavior can be
>       overidden by the Include End Input Key (eik) parameter.

**Comment by gvagenas** [comment]
According to the Record API the if the finishOnKey is not provided then all digits would stop the recording http://documentation.telestax.com/connect/rcml/record-rcml.html#record. 
So in order not to break the API, we will introduce a new value "-1" that will cause to have null eik
