### ISSUE TITLE
Patch MGCP logger

### ISSUE THREAD

**Issue by hrosa** [RestComm/Restcomm-Connect#1888]
New logger for MGCP stack is `org.mobicents.media.control.mgcp`. Fix [here](https://github.com/RestComm/Restcomm-Connect/blob/master/restcomm/configuration/config-scripts/as7-config-scripts/restcomm/mediaserver.conf#L45).

**Comment by maria-farooq** [comment]
https://telestax.atlassian.net/browse/RESTCOMM-791

**Comment by maria-farooq** [comment]
- added `https://bitbucket.org/telestax/telscale-commons/src/master/RestcommCloud/restcomm_env_rms6.sh`

**Comment by maria-farooq** [comment]
All changes related to #1821 epic will be added in a single branch. in `https://github.com/RestComm/Restcomm-Connect/tree/issue-1821`
