### ISSUE TITLE
Video conference via RVD

### ISSUE THREAD

**Issue by ghjansen** [RestComm/Restcomm-Connect#1895]
Adapt RVD to allow video conferences through `<Dial>` verb.

Planned tasks
---
- [ ] Adapt UI elements
- [ ] Adapt uploader for video files
- [ ] Adapt project scheme to save new format
- [ ] Adapt RCML provision ensuring new format
- Tests:
- [ ] Create video conference using `<Dial>`
- [ ] Modify video conference parameters
      - If audio_only is selected, all the video options are disabled
      - If MCU is selected, the layout option is enabled

**Comment by otsakir** [comment]
Issue moved to [RestComm/visual-designer #89](https://github.com/RestComm/visual-designer/issues/89) via [**ZenHub**](https://www.zenhub.com/)
