### ISSUE TITLE
ForwardFrom is empty in CDRs

### ISSUE THREAD

**Issue by maria-farooq** [RestComm/Restcomm-Connect#1902]
`/2012-04-24/Accounts/{AccountSid}/Calls `
has a `ForwardFrom` field but it is always empty 
this should have the Diversion Header value which we do get at RVD level...

Is there any other place we can get the full CDR with the diversion headers?

@gvagenas should we consider it a bug or an improvement

**Comment by gvagenas** [comment]
@maria-farooq I believe we have to consider this as a bug. Please attach logs with SIP messages

**Comment by maria-farooq** [comment]
i checked the code for `Call` and `VoiceInterpreter`
here are few comments;

- it is `VoiceInterpreter` that [parse DiversionHeader details](https://github.com/RestComm/Restcomm-Connect/blob/master/restcomm/restcomm.interpreter/src/main/java/org/restcomm/connect/interpreter/VoiceInterpreter.java#L1488). 
- however at time to [setForwardedFrom it get it from callInfo](https://github.com/RestComm/Restcomm-Connect/blob/master/restcomm/restcomm.interpreter/src/main/java/org/restcomm/connect/interpreter/VoiceInterpreter.java#L1639).
- but call actor never initialises this data member
-- [reference A](https://github.com/RestComm/Restcomm-Connect/blob/master/restcomm/restcomm.telephony/src/main/java/org/restcomm/connect/telephony/Call.java#L198)
-- [reference B](https://github.com/RestComm/Restcomm-Connect/blob/master/restcomm/restcomm.telephony/src/main/java/org/restcomm/connect/telephony/Call.java#L394)

**Comment by maria-farooq** [comment]
@gvagenas logs are attached to https://telestax.zendesk.com/agent/tickets/33994

**Comment by maria-farooq** [comment]
https://telestax.atlassian.net/browse/RESTCOMM-800
