### ISSUE TITLE
Support of RVD USSD projects for PUSH USSD

### ISSUE THREAD

**Issue by FerUy** [RestComm/Restcomm-Connect#1904]
Currently, only PULL USSD is supported when creating USSD RVD projects. We should support both.

**Comment by FerUy** [comment]
A customer's request is to add the functionality of being able to upload a CSV file which would contain the list of MSISDNs to whom send the USSD push notification or start the USSD session.

**Comment by otsakir** [comment]
This issue was moved to RestComm/visual-designer#27
