### ISSUE TITLE
Improve RVD/ES error-prone 'Module Scope' field

### ISSUE THREAD

**Issue by otsakir** [RestComm/Restcomm-Connect#191]
Support multiple module selection in "Module scope" dropdown. That way selecting the modules an assignment is valid for will quick an easy.

Also, the 'All' option should NOT be default. Users tend to treat it lightly and create broken apps. A warning could also be displayed in case 'All' is selected with a link to documentation on "Module scope".

**Comment by ivelin** [comment]
This sounds like a hack. If module A transitions to B, then B should be able to look that up and respectively pre-populate in drop-downs variables declared in A.

**Comment by ivelin** [comment]
Agree that All should be discouraged and used with lots of caution. Maybe make it an extra step in the UX.

**Comment by otsakir** [comment]
This issue was moved to RestComm/visual-designer#85
