### ISSUE TITLE
UriUtils will cause StackOverflow if httpConnectorList == null AND getHttpConnectorList is called

### ISSUE THREAD

**Issue by abdulazizali77** [RestComm/Restcomm-Connect#1913]
A typo mistake it seems. Shouldve been a call to `getHttpConnectors`
https://github.com/RestComm/Restcomm-Connect/blob/master/restcomm/restcomm.commons/src/main/java/org/restcomm/connect/commons/util/UriUtils.java#L172

**Comment by deruelle** [comment]
Closed in https://github.com/RestComm/Restcomm-Connect/pull/1914
