### ISSUE TITLE
HTTP Basic Auth challenge after password change

### ISSUE THREAD

**Issue by ValkyrieUK** [RestComm/Restcomm-Connect#1926]
Hi,

I have used both the docker image and the Restcomm binary. After setup and admin password change subsequent logins present a HTTP basic auth challange.
![pasted image at 2017_03_07 03_17 pm](https://cloud.githubusercontent.com/assets/2189018/23663070/67899314-0349-11e7-8f42-c44e9bcaee39.png)

I have tried a number of logins that I thought it may have been but with no luck.

Has anyone seen anything like this before? If so is there a fix or have I got the wrong end of the stick here?

Cheers.

**Comment by ValkyrieUK** [comment]
After trying another browser it looks like this issue doesn't arise when using FireFox. Chrome still seems to have this issue.

**Comment by ammendonca** [comment]
Not able to reproduce, please comment if you are still facing this issue, with browser console logs and possible network log as well. Thanks.
