### ISSUE TITLE
Enable Chinese language for Acapela.

### ISSUE THREAD

**Issue by leftyb** [RestComm/Restcomm-Connect#1932]
Need to enable Chinese language for acapela TTS.  After some testing and quick investigation didnt manage to fix that issue. I will need to spend more time on it.

**Comment by leftyb** [comment]
Fixed. Will PR and merge

**Comment by gvagenas** [comment]
@leftyb can we close this issue?

**Comment by maria-farooq** [comment]
yes i merged the PR yesterday and @leftyb tested already
