### ISSUE TITLE
CDR resulting from sub-account-client inbound calls has parent 'accountSid'

### ISSUE THREAD

**Issue by otsakir** [RestComm/Restcomm-Connect#1939]
When a registered client makes a call the related CDR record does not belong to the account the client belongs too but to its parent.

I've reproduced the issue like this:

* On a local instance i created a sub-account of administrator@company.com. I named it orestis@company.com
* Created a SIP client named 'orestis'
* Registered with 'orestis' using jitsi
* Made a call to the cloud instance at sip:1234@cloud.restcomm.com call succeeded.
* Checked CDRs using the Calls API. No CDRs under 'orestis@company.com' account.
* Check CDRs using parent administrator@company.com account. The call is there having account SID "ACae6e420f425248d6a26948c17a9e2acf" (administrator).

looks like the owner of the CDR is wrong

**Comment by maria-farooq** [comment]
some more insights are:
it is happening for inbound calls, for outbound call account_sid is correct.
reason behind is that for inbound calls to a number, we are picking sid from account of number_number. if phone number belongs to parent then CDR will have account sid of parent, which is wrong.

**Comment by maria-farooq** [comment]
another test proved that:
if sub account make an inbound call to a phone-number owned by sub-account itself, in that case account-sid in CDR is correct (i.e. = sub-account-sid)

**Comment by maria-farooq** [comment]
Will add 2 test cases for following cases:

- [ ] Given `sub-account-client` dials `phone-number` owned by `parent-account`:resultant CDR  `account-sid` should be equal to `sub-account-sid` (this is current bug)
- [ ] Given `sub-account-client` dials `phone-number` owned by `sub-account` itself:resultant CDR  `account-sid` should be equal to `sub-account-sid` (this is current passing scenerio)

**Comment by maria-farooq** [comment]
### Comprehensive Problem Statement:
When a  `sub-account-client` dials a `phone-number` owned by `parent-account`: resultant CDR `account-sid` is `parent-account-sid` instead of `sub-account-sid`. Reason behind is that `CallManage`r is picking sid based on `account-sid` of `phone-number`, since phone-number belongs to parent hence cdr belongs to parent account-sid.
This impacts Calls Api, as sub-account-holders are unable to see CDRs that were made toward parent-phone-number.

**Comment by maria-farooq** [comment]
Solution need to be decided [here ](https://docs.google.com/document/d/16rd_HC6RGwNziY7zD62wqCXWO9QETc7mrkCPAPwhdZw/edit#heading=h.8knzg1nmnv01)

**Comment by maria-farooq** [comment]
final solution as discussed with @deruelle is [here](https://docs.google.com/document/d/16rd_HC6RGwNziY7zD62wqCXWO9QETc7mrkCPAPwhdZw/edit#heading=h.j8psogtjl9bh)

**Comment by maria-farooq** [comment]
so [solution 3](url) is final, now time to impl:

Will add 2 test cases for following cases:

- [ ] Given `sub-account-client` dials `phone-number` owned by `parent-account`:resultant CDR  `account-sid` should be equal to `sub-account-sid` (this is current bug)
- [ ] Given `sub-account-client` dials `phone-number` owned by `sub-account` itself:resultant CDR  `account-sid` should be equal to `sub-account-sid` (this is current passing scenerio)
