### ISSUE TITLE
Outbound call to SIP client not completed

### ISSUE THREAD

**Issue by ghjansen** [RestComm/Restcomm-Connect#1941]
## Description
Callee starts ringing successfully but by accepting the call the error https://gist.githubusercontent.com/ghjansen/850fe27b86c422e1d819a1164135ca67/raw/36b44612dd20f4a6426679aaa23c9e373d779425/rc-xms-dial-2 from Olympus causes the response SIP 480 to RestComm, which sends BYE to XMS and tries to continue with the RCML. By advancing in the RCML, RestComm throws this exception https://gist.githubusercontent.com/ghjansen/725c243b3ab184f8ca6ab8804cf055a3/raw/0e8817782b0b905deed6dcc5b3d33987cedcceb0/rc-xms-dial-3 and the caller keeps hearing the ringing tone forever.

## Environment
- latest Restcomm 
- latest JSR 309 connectors
- Olympus 1.0
- XMS.

## Scenario
`alice` calls `RCML app` -> `RC interpreter` calls `bob`
This is the RCML app:
```
<Response>
  <Say>This application performs tests for the issue 19 41.</Say>
  <Dial>
    <Client>bob</Client>
  </Dial>
  <Say>Test executed with success.</Say>
</Response>
```

**Comment by ghjansen** [comment]
Tested with Olympus 2.0 and the behaviour seems the same for the user, although the error thrown by Olympus is different this time: [54.90.157.242-1489509229817.txt](https://github.com/RestComm/Restcomm-Connect/files/843125/54.90.157.242-1489509229817.txt)
No stack traces on Restcomm log this time. 
I'll perform a new test using the old JSR 309 connectors.

**Comment by ghjansen** [comment]
Call stablished normally using old JSR 309 connectors, only problem showed up when callee hanged up: [54.90.157.242-1489540069849.txt](https://github.com/RestComm/Restcomm-Connect/files/843161/54.90.157.242-1489540069849.txt)
Seems that the exception while hanging up prevented to send BYE, and caller stays connected until manually force a hangup. But by doing so, forced hangup on caller throws an exception on Restcomm log.

**Comment by ghjansen** [comment]
Rolling back to Olympus 1.0 (build 19) and keeping the old JSR 309 connectors, the entire call flow was executed with success.

**Comment by deruelle** [comment]
@ghjansen is this tied to RestComm/olympus#99 ?

**Comment by ghjansen** [comment]
My bad for late response, but no @deruelle, RestComm/olympus#99 was an independent case.
This issue (#1941) was fixed by a patch from Dialogic on the JSR 309 connector, after that we discovered a new issue involving Olympus, reported through https://github.com/RestComm/olympus/issues/100 and fixed through https://github.com/RestComm/webrtcomm/issues/94 .
