### ISSUE TITLE
Get the Name of Restcomm Client that answered during dial fork

### ISSUE THREAD

**Issue by croufay** [RestComm/Restcomm-Connect#1943]
If you are using dial fork as follows

You create an application and attach an IncomingPhoneNumber. Your app does a dial fork as follows

<Response>
<Say>forwarding your call</Say>
<Dial>
<Client>alicee</Client>
<Client>bob</Client>
<Client>john</Client>
</Dial>
</Response>

You want to get the information about the Restcomm client that answered the call. You want to know if alicee, bob or john answered the call.

At the moment, Restcomm client doesn't have the StatusCallBack feature as described here

http://documentation.telestax.com/connect/rcml/client-rcml.html#client

If you use the IncomingPhoneNumber statusCallBack url, you only get the statuscallback of the initial inbound call to the IncomingPhoneNumber, you don't get the information about the forked call.

**Comment by gvagenas** [comment]
@croufay the Dial Client status callback is missing indeed and we have an open issue for that #1937.
I will schedule this issue for 8.2.0. 
Let me know if this is ok.

**Comment by croufay** [comment]
@gvagenas thanks for checking. The customer wants a patch for their current version and they are requesting that we fix this ASAP. I already suggested that they might need to upgrade but that is not an option. I can help with this if needed.

**Comment by gvagenas** [comment]
@croufay what exact version they are running?

**Comment by croufay** [comment]
Restcomm 7.9.0.1354

**Comment by gvagenas** [comment]
This issue will kept to track the time spent for the patch for 7.9.0.1354

**Comment by croufay** [comment]
@gvagenas Will this feature allow StatusCallback to be use to get inbound and outbound calls details. For example, you want to be notified when a Restcomm client receives a call or when a Restcomm client is making an outbound calls?

**Comment by gvagenas** [comment]
This new features implemented at #1937 and will not be backported to 7.9.0 or 8.0.0
