### ISSUE TITLE
Take a tour - Numbers application

### ISSUE THREAD

**Issue by alejandroretes** [RestComm/Restcomm-Connect#1954]
Mock-ups for:
- Pop-up showing applications for a created number (i.e. Voice, USSD, SMS) (1-2 hours)
- Pop-up showing how can we use an external service by URL for this number (1-2 hours)
- Pop-up showing how can we create a new RVD project and use it as application (1-2 hours)

Total time spend on this issue: 3-6 hours

@ipsilantide

**Comment by ipsilantide** [comment]
First we need to show to the user how to register a number - after we will explain what is provider and sip number. We will register a sip number and we will show him how to use an app. We need also to explain here what is RVD application and what is URL. 

Lets see those mock-ups and we are adding something more if needed
