### ISSUE TITLE
When RC is notified that a GS is triggered need to check RC need to  check if there is a conference going on where node is the Master.

### ISSUE THREAD

**Issue by leftyb** [RestComm/Restcomm-Connect#1968]
If node owns a conference that is the Master, need signal RC/Sip-Servlets that GS must be postponed by rescheduling the GS timer. Else proceed with the GS.  As no more INBOUND calls will be allowed there will be no problem of a sudden new conference. 

Linked with issue: [sip-servlets issue](https://github.com/RestComm/sip-servlets/issues/251#issuecomment-287081571)

**Comment by maria-farooq** [comment]
https://telestax.atlassian.net/browse/RESTCOMM-1172
