### ISSUE TITLE
Media Server version not properly updated in server log and README file

### ISSUE THREAD

**Issue by FerUy** [RestComm/Restcomm-Connect#1969]
Latest release of Restcomm-Connect has an outdated version of RMS both when logged in server log or in README file
For example, if `cat  /opt/telestax/TelScale-Restcomm-JBoss-AS7-8.0.0.1430/mediaserver/log/server.log | grep version` is executed, the following is obtained:
`INFO  [MainDeployer] (main) [[[[[[[[[ Mobicents Media Server: release.version=3.0.0.FINAL Started`
(while real version is `RMS 4.1.0.60`)
**README** file at /opt/telestax/TelScale-Restcomm-JBoss-AS7-8.0.0.1430/ states that RMS version is `2.2.0` (attached)
[README.txt](https://github.com/RestComm/Restcomm-Connect/files/851499/README.txt)

**Comment by deruelle** [comment]
@FerUy please create this issue in https://github.com/RestComm/mediaserver

**Comment by FerUy** [comment]
OK @deruelle, done: https://github.com/RestComm/mediaserver/issues/408
