### ISSUE TITLE
account closing should delete corresponding clients

### ISSUE THREAD

**Issue by maria-farooq** [RestComm/Restcomm-Connect#2003]
When an account is suspended or closed, corresponding clients should be deleted from DB and same should happen all clients of all sub-accounts in hierarchy of suspended account.
@deruelle can you please confirm if it makes sense, if not then we can close this issue

**Comment by deruelle** [comment]
yes @maria-farooq 

It should have been done as part of https://github.com/RestComm/Restcomm-Connect/issues/1270#issuecomment-249147534

**Comment by maria-farooq** [comment]
oh ok letme test for a new test account and see if clients are deleted or not

**Comment by maria-farooq** [comment]
right its working fine
