### ISSUE TITLE
Change the colors in Analytics

### ISSUE THREAD

**Issue by ipsilantide** [RestComm/Restcomm-Connect#2035]
Make them consistent to our new look and feel 
![telestax-color-pallette](https://cloud.githubusercontent.com/assets/17202395/24748844/b2581d74-1ac9-11e7-8809-d67d6b0f0da9.png)

**Comment by ipsilantide** [comment]
probably #c8c6c8 for calls and #44a5ab for minutes

**Comment by ammendonca** [comment]
Fixed in latest console revamp.
