### ISSUE TITLE
Use fonts instead of icons in users dropdown 

### ISSUE THREAD

**Issue by ipsilantide** [RestComm/Restcomm-Connect#2036]
- By hovering, both icon and text should be highlighted. 
- Change the radius of the dropdown's corners (probably to 10)
![screen shot 2017-04-06 at 1 06 01 pm](https://cloud.githubusercontent.com/assets/17202395/24749039/4b324bf0-1aca-11e7-98be-470a21233d5e.png)

**Comment by ammendonca** [comment]
Outdated issue/Fixed in latest revamp.
