### ISSUE TITLE
GUI: sometimes, numbers stop showing

### ISSUE THREAD

**Issue by FerUy** [RestComm/Restcomm-Connect#2056]
From a customer's ticket opened today, but not the first time seen (version 8.1.0.1502).
See attached image and query from the DB. While incoming numbers are present in the DB, the GUI doesn't show them.
![numbers_not_showing](https://cloud.githubusercontent.com/assets/14883482/24930628/7893c032-1ee0-11e7-8ea0-b6ee3316dd41.png)
DB query in Zendesk ticket #34190

**Comment by deruelle** [comment]
Closed as Invalid. Was a DB upgrade issue
