### ISSUE TITLE
Developer Role should have API permissions

### ISSUE THREAD

**Issue by scottbarstow** [RestComm/Restcomm-Connect#2075]
Right now if you create a sub account and assign it the role of 'Developer' it can't do anything with the API. You get 403 errors when you try to send messages or anything else. It would seem to me that a Developer role would mean that you can do Developer things, like use the API. 

Perhaps it makes sense to, upon creating the user, specify which API actions a developer can invoke.

**Comment by ammendonca** [comment]
@scottbarstow I see that a user with Developer role is able to use the API (create numbers, sub-accounts, and list everything). Closing this, please reopen or create a new one if there's any specific endpoint/action that doesn't work.
