### ISSUE TITLE
Make SIP Number and SIP Client tied to an account and Unique per Organization

### ISSUE THREAD

**Issue by maria-farooq** [RestComm/Restcomm-Connect#2106]
*Use Cases:*
- [x] Add new sip number should be possible even if that number exists in a different organization
- [x] Add new sip client should be possible even if that number exists in a different organization
- [x] Dialling a sip number means dialling that number of your(dialling client's) organization.
- [x] Dialling a sip client means dialling that number of your(dialling client's) organization.
- [x] upon sub account creation, tie the sub account to the same org as the parent.
- [x] Register clients with same login under their respective organizations.
- [x] #2128 
- [x] verify existing test suit
- [x] update db changes in test suit
- [x] add new test in test suit
- [x] add upgrade scripts ( for numbers and client table changes)

@scottbarstow @deruelle do we want to support inter calls between `client-to-number` and `client-to-client` of different organizations?
For Example: 
`maria@org1.restcomm.com` dials `scott@org2.restcomm.com`
or
`maria@org1.restcomm.com` dials `1234@org2.restcomm.com`
do you think that it is part of scope of this ticket or we should create a different issue for that?

**Comment by deruelle** [comment]
@maria-farooq looks good to me. 

```maria@org1.restcomm.com dials scott@org2.restcomm.com``` and ```maria@org1.restcomm.com dials 1234@org2.restcomm.com``` only via Dial SIP not via dial client or dial number or dial conference, all of those should stay within an organization

**Comment by scottbarstow** [comment]
@maria-farooq this looks right to me as well. Jean can speak better to the inter-org, but what I'm not sure about is if we'd want to treat inter-org calls in your example as off-net, but I think this is a billing decision not a technical one. @deruelle comment on Dial SIP sounds right, tho I'm not deep in the weeds on that yet.

Either way I think we should treat that as separate ticket so that we can include test cases separately.

**Comment by maria-farooq** [comment]
test suit packages verification

- [ ] org.restcomm.connect.testsuite
- [ ] org.restcomm.connect.testsuite.faultTolerance
- [ ] org.restcomm.connect.testsuite.http
- [ ] org.restcomm.connect.testsuite.provisioning.number.bandwidth
- [ ] org.restcomm.connect.testsuite.provisioning.number.nexmo
- [ ] org.restcomm.connect.testsuite.provisioning.number.vi
- [ ] org.restcomm.connect.testsuite.provisioning.number.voxbone
- [ ] org.restcomm.connect.testsuite.smpp
- [ ] org.restcomm.connect.testsuite.sms
- [ ] org.restcomm.connect.testsuite.telephony
- [ ] org.restcomm.connect.testsuite.telephony.proxy
- [ ] org.restcomm.connect.testsuite.telephony.security
- [ ] org.restcomm.connect.testsuite.telephony.ua
- [ ] org.restcomm.connect.testsuite.tools

**Comment by maria-farooq** [comment]
Add New test for the feature:
- [ ] Add same number in 2 (pre-configured) organizations
- [ ] Add same clients in 2 (pre-configured) organizations
- [ ] Add registrations of 2 clients with same login in 2 (pre-configured) organizations
- [ ] Test OPTIONS for registrations of 2 clients with same login in 2 (pre-configured) organizations
