### ISSUE TITLE
GUI: USSD sessions are included in "Calls" logs

### ISSUE THREAD

**Issue by FerUy** [RestComm/Restcomm-Connect#2112]
As can be noticed from the attached image, USSD sessions and voice calls are logged as the same. This is incorrect for almost the same reasons as for #2110.

As did with "Messages" logs (which shows SMS logs/CDRs), we should add a USSD page (also a Geolocation one would apply now).

![restcomm_voiceussdlogs](https://cloud.githubusercontent.com/assets/14883482/25480865/5421c0fc-2b68-11e7-9c91-a24c33493a9e.png)

**Comment by deruelle** [comment]
Thanks @FerUy. @ipsilantide can you provide a new mockup for that ? @ammendonca will implement it once @gvagenas will have refactored CDRs
