### ISSUE TITLE
Support for Java 8?

### ISSUE THREAD

**Issue by arslan70** [RestComm/Restcomm-Connect#2161]
Is there any specific reason  to not run Restcomm on Java 8? Or is it simply because it is not tested fully using oracle Java 8.

```
Restcomm-JBoss-AS7-7.6.0/bin/restcomm$ ./start-restcomm.sh 
Only Java 1.7 required.

```

```
Restcomm-JBoss-AS7-7.6.0/bin/restcomm$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**Comment by nhanth87** [comment]
Hi arslan,
Only java 7 supported now

Br,
TN

**Comment by arslan70** [comment]
Yeah, I was curious to know the underlying reason.

**Comment by FerUy** [comment]
Hi @arslan70 

Restcomm as for now runs over JBoss-AS7, which doesn't support Java 8. That's the underlying reason.
We have in the roadmap upgrading the the application server to Wildfly 10.x, then Java 8 will be supported.

Best regards
