### ISSUE TITLE
Filter by friendly name not working on dashboard's Sub Accounts menu

### ISSUE THREAD

**Issue by ghjansen** [RestComm/Restcomm-Connect#2176]
Using TADHack environment, it is not possible to find any account with friendly name `john`:

![screen shot 2017-05-31 at 08 28 52](https://cloud.githubusercontent.com/assets/1459428/26630305/83b20028-45dc-11e7-9345-913eca5b7f6c.png)

The expected result should be two accounts, as shown by the database query:

![screen shot 2017-05-31 at 08 36 44](https://cloud.githubusercontent.com/assets/1459428/26630266/595b6d8c-45dc-11e7-8a0d-91ce00c7c4b1.png)

No errors noticed in browser's console, also no network activity. The browser used is Chrome Version 58.0.3029.110 (64-bit). The same happens with Firefox 53.0.3 (64-bit).

**Comment by muhammadbilal19** [comment]
@ghjansen TADHack is some specific environment? I just tested that issue on latest master branch and it works fine.
**Few observation while i was testing this issue**

> Note: i have 12 sub accounts on my local system and i am finding using Friendly name
![subaccount1](https://user-images.githubusercontent.com/8377490/26859974-63d1942c-4b8f-11e7-90b2-632df6da904c.png)

- If i show all the records on page 1 (25 records per page) and than try to search using Friendly name it works fine.
![subaccount2](https://user-images.githubusercontent.com/8377490/26860002-95b350c0-4b8f-11e7-8fb7-ec3a8b00473b.png)
- If i show 10 records per page and try to find some records which is on page 1 it works fine.But pagination still shows 2 pages but total records are only 1
![subaccount3](https://user-images.githubusercontent.com/8377490/26860090-20b307a6-4b90-11e7-849d-12cf25f137de.png)
- If i am trying to search some record which is on page 2 it hide the table and show nothing on UI while i am on page 1.
![subaccount4](https://user-images.githubusercontent.com/8377490/26860148-7ff661c2-4b90-11e7-94c3-fd4b448f454b.png)
-  If i am trying to search some record which is on page 2 it only show the counter while i am on page 2.
![subaccount5](https://user-images.githubusercontent.com/8377490/26860179-aaa7ed14-4b90-11e7-9cc3-a2d4ec7a0dea.png)

- Accounts API doesn't have any pagination params in the requests/response so i guess it is returning all the accounts/sub accounts.

**Comment by deruelle** [comment]
@muhammadbilal19 would you mind reviewing the APIs and create an issue for each API that doesn't have yet pagination such as the Accounts API ?

**Comment by muhammadbilal19** [comment]
sure @deruelle  For Account i already created #2202. And for Clients API one issue already exists #2154. I will review and create issues for others.

**Comment by ammendonca** [comment]
This is fixed, issue present in current version.
