### ISSUE TITLE
RCML Downloader logging does not provide adequate information

### ISSUE THREAD

**Issue by otsakir** [RestComm/Restcomm-Connect#2178]
When downloader fails to retrieve/parse RCML from a source the exception thrown does not provide enough information in the log to troubleshoot the problem. It's like the following:
```
 [org.restcomm.connect.http.client.Downloader] (RestComm-akka.actor.default-dispatcher-1425) 
Problem while trying to download RCML javax.xml.stream.XMLStreamException: Error parsing the 
RCML:org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in 
prolog.
```

We could include the following:

1. HTTP return status code
2. URL that was supposed to return proper RCML
3. Small part of the response to get a clue of what went wrong. 50-100 chars only.

**Comment by deruelle** [comment]
We should also probably send a notification back to the developer so he can be notified something is wrong with his application

**Comment by otsakir** [comment]
I'm closing this issue but it's not merged yet. There is another requirement for adding one more notification in case download fails which will be taken care of in another issue, in another sprint.
