### ISSUE TITLE
What do we open architecture diagrams with?

### ISSUE THREAD

**Issue by gsaslis** [RestComm/Restcomm-Connect#2181]
As someone entirely new to the project, I navigated to the root level folder entitled `architecture_diagrams`. 

Filled with excitement I scrolled down to see they're all in some `.dia` format, which i cannot open on my mac. 

Could someone plz quickly confirm what application should be used to open these?

(i tried the top result on google - http://dia-installer.de/ - but couldn't install it on my mac as it requires `xquartz`. At this point I stopped and thought I'd better ask for help.)

I could then write down the steps I followed, so we could have that in a `README.md` in that folder.

**Comment by gvagenas** [comment]
@gsaslis the application is the one you mentioned found at http://dia-installer.de/ but we plan to move those diagrams to asciidoc dagrams, or plantuml or https://www.websequencediagrams.com/ (which I better prefer).
Also, unfortunately, most of the diagrams are are outdated and they need to get updated to the latest flows.

**Comment by gsaslis** [comment]
I see, thanks @gvagenas !

In that case, might I submit a PR with a simple `README.md` that informs people of the above (and basically tells them not to bother with this for now) ?
