### ISSUE TITLE
Contributing.md (?)

### ISSUE THREAD

**Issue by gsaslis** [RestComm/Restcomm-Connect#2182]
Might I suggest moving the contributor's guide from the [wiki page](https://github.com/RestComm/Restcomm-Connect/wiki/Contribute-to-Restcomm) into a `/CONTRIBUTING.md` that seems to be a sort of a standard for several OSS projects?

**Comment by gvagenas** [comment]
Sounds like great idea @gsaslis. Can you take care of this tasks and also add notes and tips/tricks as you move on with your contribution tasks?
