### ISSUE TITLE
Handle DLR for Restcomm Connect SMPP

### ISSUE THREAD

**Issue by deruelle** [RestComm/Restcomm-Connect#2190]
Handle Delivery Receipts status DLR over SMPP and make sure the  CDR reports reflect them

**Comment by imranrazakhan** [comment]
Find below summary of fix

- Two new columns added in restcomm_sms_messages (smpp_messageid, status_callback)
- If SMS Endpoint receive request with status_callback(its optional), it forward to SMSc with registereddelivery option as TRUE.
- Now for every SubmitSm, Restcomm will save messageid returned by SMSc in SubmitSmResp against each SMS.
- On receiving DeliverSm restcomm will check for deliveryreceipt and query DB against messageid and if found get status_callback URL and post SmsSid and Status like delivered on provided URL.
- Enduser can correlate SmsSid which he received as early acknowledgement.

**Comment by deruelle** [comment]
@imranrazakhan were you able to make a pull request for this ?

**Comment by imranrazakhan** [comment]
@deruelle pull request generated, please review

**Comment by maria-farooq** [comment]
@imranrazakhan please see my [comments on PR](https://github.com/RestComm/Restcomm-Connect/pull/2375#issuecomment-325631353)

**Comment by anhntnguyen** [comment]
Jira issue: https://telestax.atlassian.net/browse/RESTCOMM-1458
