### ISSUE TITLE
When using the Search function in Clients tab, system returns a 404 

### ISSUE THREAD

**Issue by muhammadbilal19** [RestComm/Restcomm-Connect#2233]
Type a value into search. It filters down. If you then hit enter, you get the error. See attached 

![client_error1](https://user-images.githubusercontent.com/8377490/27129132-5d41c4a8-5155-11e7-861a-6a680de264d3.png)
<img width="1433" alt="screen shot 2017-06-14 at 11 00 35 pm" src="https://user-images.githubusercontent.com/8377490/27129123-57fde9ea-5155-11e7-9a5f-614591ed6f95.png">

issue is same as #1867

**Comment by ammendonca** [comment]
Duplicate of #1867
