### ISSUE TITLE
Adapt CORS filter to multiple domains (organizations)

### ISSUE THREAD

**Issue by otsakir** [RestComm/Restcomm-Connect#2254]
CorsFilter should be able to work with multiple domain names and establish a convention that will connect restcomm domain and rvd domain. 

For example given that we have two organizations A and B with domain names A.restcomm.com and B.restcomm.com, RVD requests with the following Origins should get the CORS headers attached:

`rvd.A.restcomm.com and rvd.B.restcomm.com`

The filter should be able to consider existing organizations names and the exact convention used.

**Comment by maria-farooq** [comment]
@otsakir do you think issue description need to be updated as per any later discussion/design

**Comment by otsakir** [comment]
@maria-farooq , it looks the issue is no more relavant after the change of course in the architecture. Closing.
