### ISSUE TITLE
Create a convention that will build RVD origin from current/available organization in Dashboard

### ISSUE THREAD

**Issue by otsakir** [RestComm/Restcomm-Connect#2255]
In a multiple-domain restcomm setup, Dashboard need somehow to calculate where RVD is located. For example, if Dashboard was loaded from http://a.restcomm.com it should search for RVD at http://rvd.a.restcomm.com.

This could rely on the origin index.html was loaded from and apply some login on it while at the same time it filters out origins that are not available as organizations. The filtering may be skipped.

**Comment by maria-farooq** [comment]
@otsakir do you think issue description need to be updated as per any later discussion/design

**Comment by otsakir** [comment]
@maria-farooq , it looks the issue is no more relavant after the change of course in the architecture. Closing.
