### ISSUE TITLE
Change password redirection page after initial login exception

### ISSUE THREAD

**Issue by AShabana** [RestComm/Restcomm-Connect#2273]
Hi all , we just do a fresh installation to restcomm (Restcomm-JBoss-AS7-8.2.0.1248) following this guide (http://documentation.telestax.com/connect/configuration/Starting%20Restcomm-Connect.html) , after run ./start-restcomm.sh , it opens only one tmux session with one window called restcomm ,  

The big problem when I start to login to http://$myip:8080 it successfully login using default username and password , and it redirect me instantaneously to change your password page , which fail every time and through exception at console logs as 

`
13:13:42,299 ERROR [org.restcomm.connect.identity.passwords.JavascriptPasswordValidator] (http-/192.168.104.200:8080-4) Javascript-based password validation mechanism failed. Make sure a proper JAVA implementation is used.: javax.script.Sc riptException: sun.org.mozilla.javascript.EcmaError: TypeError: Cannot find function keys in object function Object() { [native code for Object.Object, arity=1] } . at com.sun.script.javascript.RhinoScriptEngine.eval(RhinoScriptEngine.java:224) [rt.jar:1.7.0_141] at com.sun.script.javascript.RhinoScriptEngine.eval(RhinoScriptEngine.java:240) [rt.jar:1.7.0_141] at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264) [rt.jar:1.7.0_141] at org.restcomm.connect.identity.passwords.JavascriptPasswordValidator.getStrength(JavascriptPasswordValidator.java:41) [restcomm-connect.identity-8.2.0.1248.jar:8.2.0.1248] at org.restcomm.connect.identity.passwords.JavascriptPasswordValidator.isStrongEnough(JavascriptPasswordValidator.java:18) [restcomm-connect.identity-8.2.0.1248.jar:8.2.0.1248] at org.restcomm.connect.http.AccountsEndpoint.prepareAccountForUpdate(AccountsEndpoint.java:446) [restcomm-connect.http-8.2.0.1248.jar:8.2.0.1248] at org.restcomm.connect.http.AccountsEndpoint.updateAccount(AccountsEndpoint.java:507) [restcomm-connect.http-8.2.0.1248.jar:8.2.0.1248] at org.restcomm.connect.http.AccountsJsonEndpoint.updateAccountAsJsonPut(AccountsJsonEndpoint.java:86) [restcomm-connect.http-8.2.0.1248.jar:8.2.0.1248] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.7.0_141] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [rt.jar:1.7.0_141] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_141] at java.lang.reflect.Method.invoke(Method.java:606) [rt.jar:1.7.0_141] at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) [jersey-server-1.13.jar:1.13] at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) [jersey-server-1.13.jar:1.13] at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) [jersey-server-1.13.jar:1.13] at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302) [jersey-server-1.13.jar:1.13] at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) [jersey-server-1.13.jar:1.13] at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108) [jersey-server-1.13.jar:1.13] at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) [jersey-server-1.13.jar:1.13] at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) [jersey-server-1.13.jar:1.13] at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1480) [jersey-server-1.13.jar:1.13] at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1411) [jersey-server-1.13.jar:1.13] at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1360) [jersey-server-1.13.jar:1.13] at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1350) [jersey-server-1.13.jar:1.13] at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416) [jersey-servlet-1.13.jar:1.13] at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538) [jersey-servlet-1.13.jar:1.13] at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716) [jersey-servlet-1.13.jar:1.13] at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [jboss-servlet-api_3.0_spec-1.0.2.Final.jar:1.0.2.Final] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295) [jbossweb-7.2.0.Final.jar:7.2.0.Final] at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.2.0.Final.jar:7.2.0.Final] at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:230) [jbossweb-7.2.0.Final.jar:7.2.0.Final] at org.mobicents.servlet.sip.startup.SipStandardContextValve.invoke(SipStandardContextValve.java:263) [restcomm`

**Comment by AShabana** [comment]
Dears your response is very appreciated .

**Comment by AShabana** [comment]
Dears , if this issue may take long time , please forward to me the last working commit

**Comment by ammendonca** [comment]
Hi @AShabana,

This issue seems a known issue with some JVM (some versions of OpenJDK 7), it has already been reported in https://github.com/RestComm/Restcomm-Connect/issues/2077, so please follow the discussion there.

Closing as duplicate.
