### ISSUE TITLE
Create JSR309 MockGateway to mock connector behaviour

### ISSUE THREAD

**Issue by ghjansen** [RestComm/Restcomm-Connect#2326]
Create a MockGateway similar to [MockMediaGateway](https://github.com/RestComm/Restcomm-Connect/blob/master/restcomm/restcomm.mgcp/src/main/java/org/restcomm/connect/mgcp/MockMediaGateway.java) so its possible to mock the JSR 309 connector with the behaviour expected from the interactions between the driver and XMS, contributing to testsuite scenarios and the investigation of issues reported by customers.

**Comment by deruelle** [comment]
@ghjansen please put a link as a comment here to the design document.

**Comment by ghjansen** [comment]
Sure @deruelle here it is: https://docs.google.com/document/d/1mFFB7K7DCE752lcHV4bNcSqgXyxzJQ2LJ5--2xs2RpQ/edit#heading=h.z6ne0og04bp5

**Comment by ghjansen** [comment]
It was decided to not execute this issue for now.
