### ISSUE TITLE
RVD Send SMS does not support Unicode characters

### ISSUE THREAD

**Issue by scottbarstow** [RestComm/Restcomm-Connect#2368]
Related to #1903 there is no way to set encoding of SMS message to UCS-2 to support Unicode messages such as Japanese or other languages.

There needs to be a setting added to the SMS Verb to support the setting of encoding for the message.

**Comment by marca56** [comment]
@otsakir ... we need to get this issue fixed this week due to customer meetings in Japan and rest of Asia

**Comment by marca56** [comment]
Issue moved to [RestComm/visual-designer #182](https://github.com/RestComm/visual-designer/issues/182) via [**ZenHub**](https://www.zenhub.com/)

**Comment by marca56** [comment]
according to @scottbarstow this morning, it's not working still
