### ISSUE TITLE
After deleting a number, the list gets cleared

### ISSUE THREAD

**Issue by ammendonca** [RestComm/Restcomm-Connect#2370]
When deleting a number from the list, the whole numbers list gets cleared and the message `No incoming numbers matching query. Register one now!` is shown. Only after switching to another tab, does the numbers show again.

![jul-19-2017 12-32-31](https://user-images.githubusercontent.com/1737954/28364900-668a69f4-6c7e-11e7-9acd-a926f658312a.gif)

**Comment by ddhuy** [comment]
@ammendonca and @desipepova , can I start investigating on this issue

**Comment by ammendonca** [comment]
@ddhuy thanks for the availability to help but this issue is currently outdated, the layout has changed and there's no delete on the listing, so the issue is gone.

Closing.
