### ISSUE TITLE
Completed option is duplicated in calls logs search by "Status"

### ISSUE THREAD

**Issue by FerUy** [RestComm/Restcomm-Connect#2424]
The select drop-down list for searching call logs (CDRs) by **Status** field includes two **Completed** options (while the first gets the CDRs with status 'completed', the second one gets no records -very likely the second one was thought to include current misleading status 'COMPLETED', or would be useful for the status decided after issue #2423 is solved-):

![completed_call_status](https://user-images.githubusercontent.com/14883482/29299344-5886f00e-8144-11e7-8438-4ce86ba2bc27.png)

**Comment by ammendonca** [comment]
Outdated issue/Fixed in latest revamp.
