### ISSUE TITLE
AdminUI login sometimes fails with remembered crendentials

### ISSUE THREAD

**Issue by otsakir** [RestComm/Restcomm-Connect#245]
A strange issue happens in AdminUI login when the credentials are remembered. The issue is possibly attributed to uninitialized internal angular model. 

There is a chance to reproduce the error with the following steps:
1. In the login form type the credentials manually and proceed
2. In the browser brompt for remembering the credentials click login
3. Restart the browser and try to login. This time do not type the credentials and use the pre-completed values.
4. Login should fail and an javascript exception should be displayed in the browser console.

**Comment by leftyb** [comment]
I don’t know if I check it correctly but, when I try to reproduce and
restart the browser, I don’t get any pre-completed values.

I need to insert the Acount/Email correctly and then insert any character
at the password field, because of the "requirement field".

Maybe we need to use at the login button "form.$invalid" to be active when
form is valid. So the "Please Fill out this field" will not prevent from
login.

**Comment by otsakir** [comment]
The problem as far as i've seen is that there is an inconsystency between what you see (a pre-completed form) and the internal angular model which is empty.

So, theoritically your suggestion should work. It can hide or disable the login button if the form model is $invalid. But still, the UX is strange. You will have a precompleted form looking allright and you won't be able to press "Login".

**Comment by leftyb** [comment]
Yes you are right,
probably we could activate it with something like that
ng-disabled="form.$invalid || !rememberMeCheck"
This means, that "Remember me" cannot be checked from default.

**Comment by leftyb** [comment]
No, I just tried it, it is not working, sorry.

**Comment by deruelle** [comment]
I'm noticing this issue on Cloud.restcomm.com. Even manually typing the username and password doesn't help. There is no way I can login anymore for some reason I'm getting a 401

**Comment by otsakir** [comment]
When the issue occurs right after restcomm installation it may be related/fixed with #616 . Let's keep an eye on it and report if it happens again.

**Comment by ammendonca** [comment]
This is not happening anymore.
