### ISSUE TITLE
Wrong port in 'docker run' command in docs quick start

### ISSUE THREAD

**Issue by otsakir** [RestComm/Restcomm-Connect#2494]
According to the docs found here:

http://documentation.telestax.com/connect/configuration/docker/Restcomm%20-%20Docker%20Quick%20Start%20Guide.html#install-and-run-restcomm-docker

the command to start restcomm instance is:

```
docker run  -i -d --name=myrestcomm -v /var/log/restcomm/:/var/log/restcomm/ -e RCBCONF_STATIC_ADDRESS="192.168.2.5" -e ENVCONFURL="https://raw.githubusercontent.com/RestComm/Restcomm-Docker/master/env_files/restcomm_env_locally.sh" -p 80:80 -p 443:443 -p 9990:9990 -p 5060:5060 -p 5061:5061 -p 5062:5062 -p 5063:5063 -p 5060:5060/udp -p 65000-65050:65000-65050/udp restcomm/restcomm:latest
```

Trying to access http://ANY_DOCKER_OR_ETHERNET_IP:80 doesn't work.

The `-p 80:80` seems wrong since no response comes from there. Replacing it with `-p 80:8080` fixes the issue. It looks like restcomm is started on port 8080 internally.

**Comment by croufay** [comment]
I am closing this issue, fixed with this commit
https://github.com/RestComm/Restcomm-Connect/commit/0c4ec2e71ec7602e469405c60400387344bf328f
