### ISSUE TITLE
RestComm-Connect USSD PUSH API >>> HTTP Status 500 - Internal Server Error

### ISSUE THREAD

**Issue by soiavaq** [RestComm/Restcomm-Connect#2551]
Hello,
This is a response from a server of RestComm-Connect USSD PUSH API:

JBWEB000065: HTTP Status 500 - Internal Server Error
JBWEB000309: type JBWEB000067: Status report
JBWEB000068: message Internal Server Error
JBWEB000069: description JBWEB000145: The server encountered an internal error that prevented it from fulfilling this request.
JBoss Web/7.2.0.Final

Why?
What is the problem?
How to fix it?

**Comment by abdulazizali77** [comment]
Hi @soiavaq can you make some changes to your RC setup and provide us with further details?
1. increase the log levels in `{installation_folder}/standalone/configuration/standalone-sip.xml`

Please provide us :
1. Verbose log/stacktrace of when the 500 happens
2. Details of your environment: os? jdk version? etc
3. Details of how you deploy and test RC and USSD. plain binary? docker? 
4. Detail of the curl command or the method you use to invoke the Ussd Push.




thanks

**Comment by FerUy** [comment]
@soiavaq... in addition to @abdulazizali77 's requests, we recently improved the USSD PUSH API documentation here: http://documentation.telestax.com/connect/api/ussd-push-api.html#uss-push (you can find an example there). So, I would add:

5. Your RVD project?
6. Do you use the RVD project identifier in the curl command?
7. Are you using jSS7 simulator connected to the USSD Gateway to see the PUSH USSD command arriving at it?
8. Do you have a Wireshark trace of the test?

Thanks and best regards

**Comment by soiavaq** [comment]
I just want to test it:

curl -X POST -H "application/json" https://AC2b6a92d05940d206c30892cc16c9857b:TOKEN@cloud.restcomm.com/restcomm/2012-04-24/Accounts/AC2b6a92d05940d206c30892cc16c9857b/UssdPush -d "From=Restcomm" -d "To=1234567890" -d "Url=https://cloud.restcomm.com/restcomm-rvd/services/apps/AP8984a927006a4f428b1022536d8cdb7a/controller"

But it does not work.

**Comment by FerUy** [comment]
OK @soiavaq, understood ... as it states here: http://documentation.telestax.com/connect/api/ussd-push-api.html#supported-operations *HTTP POST sends a USSD message to the configured USSD Gateway* and following here: http://documentation.telestax.com/connect/api/ussd-push-api.html#example-of-ussdpush : *The USSD Gateway to which Restcomm must send the USSD message must be configured in the restcomm.xml file. IP address and port must be configured (i.e. they are mandatory).Username/password for the USSD are optional*. So, if you don't have a USSD Gateway configured in `$RESTCOMM_HOME/standalone/deployments/restcomm.war/WEB-INF/conf/restcomm.xml`, it won't work and will throw that error you are getting.

Briefly: you need to have a USSD Gateway to whom send the request to from Restcomm-Connect.

**Comment by soiavaq** [comment]
Is this possible via cloud.restcomm.com?

**Comment by FerUy** [comment]
It will be soon possible (we are currently working on USSD Gw in the cloud), but not yet @soiavaq

**Comment by soiavaq** [comment]
OK
Thanks all
Good luck

**Comment by FerUy** [comment]
Thank you @soiavaq and best regards
