### ISSUE TITLE
Implement Application listing view

### ISSUE THREAD

**Issue by otsakir** [RestComm/Restcomm-Connect#2561]
Create a new view in Dashboard that lists applications according to mockups. It will use the Applicaitons API to retrieve apps. 

Note, no paging will be supported as a first iteration.

**Comment by ammendonca** [comment]
![image](https://user-images.githubusercontent.com/1737954/32411002-b697c416-c1c7-11e7-9cf2-d27c9cad8d0f.png)

Completed. To be pushed when whole refactor is complete.
