### ISSUE TITLE
Prepare video development for final merge and release

### ISSUE THREAD

**Issue by ghjansen** [RestComm/Restcomm-Connect#2568]
- [x] Merge last part of development for video (#1550) with the branch used for updating TADHack environment (#2130)
- [x] Merge master into this new branch
- [x] Create new build and test using EC2 instance configured with XMS to ensure that JSR309 is good
- [x] Execute testsuite job against the new branch to ensure that MGCP is good

**Comment by jaimecasero** [comment]
running testsuite against branch as it is (we can run it later, but lets have  a first impression on it...)
http://ci.telestax.com/view/Restcomm/job/Restcomm-TestSuite-Parallel/47/

**Comment by jaimecasero** [comment]
@ghjansen  fixed test comp issue becuase of new mediatts at https://github.com/RestComm/Restcomm-Connect/commit/52a109b53eb64a6838f87e4d5a44449909aea3a5

**Comment by jaimecasero** [comment]
@ghjansen  merged lastest changes from master with recording from @gvagenas 
there were 4 conflicts:
Auto-merging restcomm/restcomm.telephony/src/main/java/org/restcomm/connect/telephony/Call.java
Auto-merging restcomm/restcomm.mscontrol.mms/src/main/java/org/restcomm/connect/mscontrol/mms/MmsCallController.java
CONFLICT (content): Merge conflict in restcomm/restcomm.mscontrol.mms/src/main/java/org/restcomm/connect/mscontrol/mms/MmsCallController.java
Auto-merging restcomm/restcomm.mscontrol.mms/src/main/java/org/restcomm/connect/mscontrol/mms/MmsBridgeController.java
CONFLICT (content): Merge conflict in restcomm/restcomm.mscontrol.mms/src/main/java/org/restcomm/connect/mscontrol/mms/MmsBridgeController.java
Auto-merging restcomm/restcomm.mscontrol.jsr309/src/main/java/org/restcomm/connect/mscontrol/jsr309/Jsr309CallController.java
CONFLICT (content): Merge conflict in restcomm/restcomm.mscontrol.jsr309/src/main/java/org/restcomm/connect/mscontrol/jsr309/Jsr309CallController.java
Auto-merging restcomm/restcomm.mscontrol.jsr309/src/main/java/org/restcomm/connect/mscontrol/jsr309/Jsr309BridgeController.java
CONFLICT (content): Merge conflict in restcomm/restcomm.mscontrol.jsr309/src/main/java/org/restcomm/connect/mscontrol/jsr309/Jsr309BridgeController.java
Auto-merging restcomm/restcomm.interpreter/src/main/java/org/restcomm/connect/interpreter/VoiceInterpreter.java
Auto-merging restcomm/restcomm.interpreter/src/main/java/org/restcomm/connect/interpreter/BaseVoiceInterpreter.java
Automatic merge failed; fix conflicts and then commit the result.


i managed to fix them

**Comment by jaimecasero** [comment]
test results on this branch before last master merging (recording changes)
http://ci.telestax.com/view/Restcomm/job/Restcomm-TestSuite-Parallel/48/testReport/ 

just 57 failures, i will check if there is soem unsual test failing

**Comment by ghjansen** [comment]
Closed via #2575 .
