### ISSUE TITLE
RestComm-Console - Client - Voice Request does not updated UI

### ISSUE THREAD

**Issue by xhoaluu** [RestComm/Restcomm-Connect#2588]
There is a UI issue that The Console does not update Client Voice Request - selected Application. Even when I have already chosen RVD application and successfully saved the RVD app. Next time, when Reopen the client, the Voice Request is not updated.

Attached the image, it's seem RC does not send App_Sid to UI for updating info.
![screen shot 2017-10-20 at 10 21 31 am](https://user-images.githubusercontent.com/19316067/31804056-43cd4750-b581-11e7-90f2-307b21b3ae8e.png)

**Comment by anhntnguyen** [comment]
Jira ticket:
https://telestax.atlassian.net/browse/RESTCOMM-1176

**Comment by ammendonca** [comment]
This has been fixed in #2653.
