### ISSUE TITLE
Restcomm Connect RVD

### ISSUE THREAD

**Issue by Nyasak** [RestComm/Restcomm-Connect#2599]
I have downloaded and installed Restcomm (Restcomm-JBoss-AS7-8.2.1-67.zip) 
on my linux box and i can login to the dashboard without any problems but the same credentials are failing when i try to login to RVD and Olympus, do RVD and Olympus have separate login credentials? if yes what are they? If not how can i solve this problem? I have also tried building from source but the outcome is still the same

**Comment by mmgc84** [comment]
Hi Nyasak

The first time you run Restcomm user is "administrator@company.com" and the default password is "RestComm", without quotations marks, then you set your own password.

For the RVD you should be able to login with your new password.

Olympus has 2 clients "alice" and "bob", default password for both is "1234"

Regards

**Comment by Nyasak** [comment]
Thanks for the quick response but i did follow the instructions about changing the password at first time logon and still the new password that doesn't work on RVD but works on the management console. As for Olympus, both 'alice' and 'bob' are not working with 1234 as a password.

**Comment by mmgc84** [comment]
-Have you tried different browsers? Firefox/Chrome
-Are you using different ports than default values? Are you using SSL?

I'm using a virtual machine using debian to try to reproduce your error but I log in just fine, this is my restcomm.conf, I have no change in advanced.conf and no SSL

 # Network configuration
NET_INTERFACE='eth0'
PRIVATE_IP='192.168.0.68'
SUBNET_MASK='255.255.255.0'
NETWORK='192.168.0.0'
BROADCAST_ADDRESS=''
# PUBLIC IP ADDRESS
STATIC_ADDRESS='192.168.0.68'

**Comment by Nyasak** [comment]
I have similar settings, all defaults ports, different browsers but no change, will try it on virtual box, at present i am running Bash on Ubuntu on Windows 10

**Comment by mmgc84** [comment]
Hi Nyasak.

Did you fix your problem?

**Comment by otsakir** [comment]
@Nyasak

1. Olympus has a different set of credentials than Dashboard/RVD. It uses 'client' credentials. Defaults for community restcomm should be alice/1234. 

2. RVD uses the account credentials as Dashboard does. So, not being able to login to RVD while being able to login to Dashboard is strange. Check .../standalone/log/rvd/rvd.log for message like the following: 

> 1026 13:39:16,478 +03 INFO (http-/192.168.2.3:8080-3) using restcomm server at http://192.168.2.3:8080/ 

That's the url where RVD tries to access restcomm REST API. If this address is wrong that might explain it. You could get around this by explicitly setting a value in rvd.xml/restcommBaseUrl property:

https://github.com/RestComm/visual-designer/blob/4a02be421f1acaca9156e12ea80964bcd1ce32fc/designer/src/main/webapp/WEB-INF/rvd.xml#L37-L37

**Comment by Nyasak** [comment]
Thanks for the quick response but i did exactly as you have explained, i got prompted for a new password and i changed but the new credentials are still not being accepted by RVD,

**Comment by Nyasak** [comment]
@otsakir , you are correct, the base URL for Restcomm API is pointing to a wrong IP, i think this is due to my previous attempts, now i need to know the location of rvd.xml so i can correct it or is there another way of correcting the URL?, thanks

**Comment by Nyasak** [comment]
I am sorry to say the issue still hasn't been resolved despite following all those instructions many times over. RVD is still rejecting the same credentials that work on Restcomm console. Besides correcting the wrong baseURl it can be ruled out because the error message specifically mentions an "incorrect login" Generally speaking i have found this particular Restcomm product very difficult to work with. I wonder why resetting a password isn't a standard feature. Due to my time constraints i may now have to consider abandoning this Restcomm solution and look elsewhere.

**Comment by Nyasak** [comment]
i finally solved it by deleting the whole configuration and starting afresh, it looks like there were persistent previous configs that were interfering.

**Comment by mmgc84** [comment]
Hi @Nyasak, Restcomm by default uses HSQL, from my experience your assumption might be right, you can find several HSQL browsers on the web or you can even set Restcomm to use MySql or MariaDB.

Regards
