### ISSUE TITLE
Play and Say verb in Dial Action cannot be executed if enable-200-ok-delay is true

### ISSUE THREAD

**Issue by xhoaluu** [RestComm/Restcomm-Connect#2633]
in restcomm.xml set enable-200-ok-delay to true.
Call to RCML app has Dial verb with Action attribute do link to an RCML has Play or Say verb at the beginning.

The callee does not respond to the call of Dial verb, action attribute invoked which returned Play or Say verb. The call cannot be hang up, cannot hear any thing.

**Comment by xhoaluu** [comment]
https://telestax.atlassian.net/browse/RESTCOMM-1259

**Comment by maria-farooq** [comment]
fixed and merged
