### ISSUE TITLE
Implement workaround for displaying numbers in application details

### ISSUE THREAD

**Issue by otsakir** [RestComm/Restcomm-Connect#2647]
Use the application listing that includes numbers and just pick the one interested in. 

Once https://github.com/RestComm/Restcomm-Connect/issues/2608 is merged, we can rely on that.

**Comment by otsakir** [comment]
![no_numbers](https://user-images.githubusercontent.com/8972800/33125264-771675a2-cf88-11e7-8079-f58b869cfda0.png)

app is not assigned to any numbers

![some_numbers](https://user-images.githubusercontent.com/8972800/33125369-d59b05fc-cf88-11e7-97c7-0daff86b907e.png)

app is assigne to some numbers

**Comment by ammendonca** [comment]
Fixed by https://github.com/ammendonca/Restcomm-Connect/pull/5.
