### ISSUE TITLE
If a registered sip client doesn't respond to OPTIONS requests , Restcomm should remove it

### ISSUE THREAD

**Issue by desipepova** [RestComm/Restcomm-Connect#27]
If a registered sip client doesn't respond to OPTIONS requests , Restcomm should remove it

**Comment by gvagenas** [comment]
UserAgentManager stores the REGISTRATION object to the OPTIONS application session before send out.

UserAgentManagerProxy implements SipApplicationSessionListener, but when the OPTIONS request expires because there is no response, only SessionDestroyed event is fired and the 
```event.getApplicationSession().getAttribute(Registration.class.getName())``` returns null.

**Comment by gvagenas** [comment]
There are cases where there is no Request Timeout for OPTIONS requests that don't get response.
