### ISSUE TITLE
Web Trigger: Create call - failure but call worked

### ISSUE THREAD

**Issue by anhntnguyen** [RestComm/Restcomm-Connect#2711]
When I use Web Trigger to make a call, call worked but result display is failure.
I attached the screen shot:

![screen shot 2017-12-13 at 3 39 35 pm](https://user-images.githubusercontent.com/24792490/33930060-380898b2-e01e-11e7-8ba1-8b802942a697.png)

**Comment by anhntnguyen** [comment]
Jira ticket: https://telestax.atlassian.net/browse/RESTCOMM-1438

**Comment by bourgois** [comment]
This is indeed an issue as our API calls can't tell if things are working or not...

**Comment by otsakir** [comment]
hmm, issue does not occur either locally or on staging. Digging further...
