### ISSUE TITLE
Display warning when saving project in a multi user scenario

### ISSUE THREAD

**Issue by otsakir** [RestComm/Restcomm-Connect#274]
**Scenario**
Alice and Bob work on the same RVD project. Alice saves first. Bob does not know that and saves after Alice. Alice's changes will be overwritten by Bob's.

A warning should be displayed in such a case so that Bob knows what he is about to do.

An option to save Bob's work under a different name would also help.

**Comment by deruelle** [comment]
Agreed. We may want to introduce a locking mechanism similar to wordpress describing that someone else is editing. Also we may want to introduce revisions for each change made to the project similar to how google docs or git works so rolling back to a previous known working version is easy.

**Comment by otsakir** [comment]
This issue was moved to RestComm/visual-designer#78
