### ISSUE TITLE
I can't download it

### ISSUE THREAD

**Issue by zhouyusunquan** [RestComm/Restcomm-Connect#2744]
I can't download   Restcomm-JBoss-AS7-8.2.1-67.zip
I can't download    Source code (zip)
I can't download   Source code (tar.gz)

**Comment by gsaslis** [comment]
Hi @zhouyusunquan, 

You should be able to access the latest downloads for Restcomm-Connect here: 
https://www.restcomm.com/downloads/

We are currently migrating all binary downloads there. You should still be able to download source code packages from GitHub.
