### ISSUE TITLE
Problems to make test call olympus

### ISSUE THREAD

**Issue by danielrive** [RestComm/Restcomm-Connect#2747]
Hi

I am trying use Restcomm, i am using Docker with docker-compose on Linux, the container run ok and can see the Restcomm´s login page, i use the credentials for test but when i try to make a call (+1234), i can hear the ring tone but the call is not established so i not hear the welcome message.

These are some configurations made:

* RCBCONF_STATIC_ADDRESS is with machine's local ip, i made that since the machine where i run the docker container gets slow when run the container.

* The browsers used are Opera and Google Chrome

* i made the calls with Jitsi SIP and the browser directly

* When i try make the call to +12345 i get the next message
![image](https://user-images.githubusercontent.com/20462958/34615071-83d0e8d6-f201-11e7-8c2a-8dadb14d7767.png)

* When i try make the call to Bob i get the next message
restcomm_1  | 14:36:21,161 INFO  [org.mobicents.servlet.sip.core.session.SipSessionImpl] (MSS-Executor-Thread-9) Invalidating the sip session (86554210_30388926_57a5b08a_21bdf6aa;96c1f0fe274e1901130dc3362484c31f@172.18.0.2;21bdf6aa;RestComm)
restcomm_1  | 14:36:21,162 INFO  [org.mobicents.servlet.sip.core.session.SipApplicationSessionImpl] (MSS-Executor-Thread-9) Invalidating the following sip application session 21bdf6aa;RestComm
restcomm_1  | 14:36:21,162 INFO  [org.mobicents.servlet.sip.core.session.SipApplicationSessionImpl] (MSS-Executor-Thread-9) The following sip application session 21bdf6aa;RestComm has been invalidated

* In this Links you can download the full Logs obtained
https://s3.amazonaws.com/logrestcomm/capture_docker_restcomm.txt

**Comment by danielrive** [comment]
Hello @gsaslis 

With my comment i wanted to say  the following: 

i work with 2 computers, in the first i have the container running Restcomm and in the other i access to interface web of restcomm(https://ip_firts_machine:8443/olympus)  for make tests throught  port(8443) and the IP configured  in firts machine in the RCBCONF_STATIC_ADDRESS, in this option i write the local IP of the firts machine(192.168....).

i make that because the firts machine when run docker container gets slow and can't access to other functions like browser for make test.

i going to test  the #2751 and will give my feedback

Thanks

**Comment by gsaslis** [comment]
Thanks @danielrive! Yes, please let me know if that helps cause part of your problem does sound very similar to what that PR solves.

**Comment by danielrive** [comment]
Hi @gsaslis, i am sorry for the delay answering, I reviewed the  #2751 case and it worked, I will work on some Olympus functionalities and I will give you my feedback soon.

Thanks

**Comment by gsaslis** [comment]
@danielrive fantastic! thanks for sharing this feedback!

In that case, I'm going to close this for now and let's open a new issue (or re-open this one) once you're through with your tests  ; )

Thanks!
