### ISSUE TITLE
Client's password is not updated

### ISSUE THREAD

**Issue by JuankGarcia** [RestComm/Restcomm-Connect#2769]
Hi,
I tried to update the password for some clients from console and it is not possible, in Restcomm Console says "update successfully", but in DB is not updated.

WebConsole logs: 
`RestComm Client "clientXXX" updated successfully!`

**Comment by gsaslis** [comment]
Hi @JuankGarcia 👋 

Thanks for raising this. 
Could you please give some extra information about how the issue comes about? 

Please provide: 
* steps to reproduce
* log output
