### ISSUE TITLE
Unable to authorize sip clients. SIP/2.0 403 Forbidden

### ISSUE THREAD

**Issue by suyashbhatt** [RestComm/Restcomm-Connect#2774]
I was finally able to get RestComm-Connect working through Docker in my digitalocean droplet with Authorized SSL from letsencrypt. everything seemed to work fine until I created new client and tried to login to Olympus. I got `Invalid Username or Password. Please try again.` error. I tried to reset password for client and login again but no avail kept getting same error. Console indicates 403 unauthorized but it doesnt make any sense why would it not authorize. I even tried making few more clients but I was not able to authorize single one of them. I am wondering if anyone can give me any idea on what could be wrong, If anyone wants to test, let me know I can provide server details as well to investigate. [Console output (with domain name in log changed to my-cool-domain):](https://gist.github.com/suyashbhatt/66bc429d89279fa2cb7b7d7c75a8ee85)

EDIT: moved console output to Gist

**Comment by gsaslis** [comment]
Hi @suyashbhatt !

This sounds like some issue with the values of `RCBCONF_STATIC_ADDRESS` and `RMSCONF_EXTERNAL_ADDRESS` in `docker-compose.yml`. 

Can you please share your `docker-compose.yml` and the command you use for starting it?

**Comment by suyashbhatt** [comment]
Here is my [docker-compose.yml](https://gist.github.com/suyashbhatt/f4b705b4f299e89f4fc9ad0f7902dcc7)

**Comment by suyashbhatt** [comment]
I tried to check back [Quick Start Guide: RestComm on Docker](http://documentation.telestax.com/connect/configuration/docker/Restcomm%20-%20Docker%20Quick%20Start%20Guide.html) to check back again if I missed anything and there was no mention about changing value of `RMSCONF_EXTERNAL_ADDRESS` so I even tried to change it back to `127.0.0.1` that did not help either

**Comment by suyashbhatt** [comment]
I got an update with the issue. I was testing by changing configurations to single out the issue cause. Client was able to login while using self signed certificate but not when Lets encrypt SSL was applied. When using `RCADVCONF_SECURESSL: AUTH` clients get `Invalid Username or Password. Please try again.` error but everything seems to work perfectly.
@gsaslis am I doing anything wrong with certificate?

These were the steps used to create Java Keystore from letsencrypt certs:

**1. Create pkcs12 file by exporting private and public keys**
`openssl pkcs12 -export -in fullchain.pem -inkey privkey.pem -out cert.pkcs12`

**2. Import certs to keystore from pkcs12 and create Java Keystore**
`keytool -importkeystore -destkeystore keystore.test -srckeystore cert.pkcs12 -srcstoretype PKCS12`

Doing this browsers are accepting keys without any issues. I can login to dashboard without issues. Olympus Android app is also able to connect to server with no issues but 403 error is persistent.

**Comment by gsaslis** [comment]
@suyashbhatt 
Not really my area of expertise, but this does sound like a configuration issue...

Two things i'd check: 
1. when accessing from your browser, do you use the IP or some domain name? if the latter, give it a go with just the IP
2. Go through the docs again on [HTTPS setup](http://documentation.telestax.com/connect/configuration/Restcomm%20-%20Enable%20HTTPS%20secure%20connector%20on%20JBoss%20AS%207%20or%20EAP%206.html#secure) and check all settings. 
I'm not sure if it will make a difference, but, for example, according to those docs [this](https://gist.github.com/suyashbhatt/f4aa996137507289ba865118906d69a7#file-docker-compose-yml-L45) should be `strict`. Maybe there's also sth else...

**Comment by suyashbhatt** [comment]
You were right about ipaddress, I was able to login to one of the account with IP, I will give it a go to `strict` mode and see if that will make any difference.

**Comment by suyashbhatt** [comment]
@gsaslis can you mention anyone here with the expertise in this area?

**Comment by gsaslis** [comment]
ok, the issue with that then is because of [Organizations](http://documentation.telestax.com/connect/api/organization-api.html). 

Restcomm basically binds all user accounts created to a specific `Organization`. The `Organization` itself is bound to a domain name. By default, with the config options you've set in the `docker-compose.yml` you're telling Restcomm to bind the default Organization it creates to the IP. 

This is why sign-in attempts fail when you try to access with domain. 
You should be able to overcome this by adding the env var: 
`RCBCONF_RESTCOMM_HOSTNAME: <your domain name>`  in your `docker-compose.yml`. 

If this solves the issue, it would be great if you could share some feedback about which docs you might have used, so that we can improve them and save others some of the trouble you've been facing.

**Comment by suyashbhatt** [comment]
I added `RCBCONF_RESTCOMM_HOSTNAME: xyz.com` to my `docker-compose.yml` changed my hostname in `/etc/hostname` and `/etc/hosts` to `xyz.com ` and still having the same issue. Is there any way to check if my domain exist in organization. I could not get list of all organization of domains. I could make a new organization and get its Sid?

**Comment by suyashbhatt** [comment]
@gsaslis I did a simple test, as mentioned in api docs adding `test` with `curl -X PUT "https://<accountSid>:<authtoke>@xyz.com/restcomm/2012-04-24/Organizations/test"` should result with `<DomainName>test.xyz.com.</DomainName>` but in my case its output is `<DomainName>test</DomainName>`. I wonder if that makes any sense to you

**Comment by suyashbhatt** [comment]
It worked!! I think DNS took some time to apply new changes of hostname in /etc/hostname and /etc/hosts. but eventually it worked. It was the issue with Organization

**Comment by gsaslis** [comment]
Glad to hear @suyashbhatt !

Do you think you could help improve the docs on this setup to make this easier for others?

**Comment by suyashbhatt** [comment]
Auth worked but hit another roadblock `500 Problem to setup the call` `Reason: Problem while trying to download RCML`. This issue was pointed on [HTTPS Setup](http://documentation.telestax.com/connect/configuration/Restcomm%20-%20Enable%20HTTPS%20secure%20connector%20on%20JBoss%20AS%207%20or%20EAP%206.html#secure) and resolution is to add `RESTCOMM_HOSTNAME='YOUR_HOST_NAME'` which we already did through `docker-compose.yml`

**Comment by suyashbhatt** [comment]
For the documentation, I am already on it. I will contribute towards the documentation so it makes easier for others.

**Comment by gsaslis** [comment]
@suyashbhatt awesome thanks! 

Yes, the `docker-compose.yml` is not really targeted towards production deployments, so it makes sense you'll be facing some issues. We only really put it together to help testing Restcomm in a `dev` env. 

Anyway, let's close this issue and raise another one (referencing this one as well) with the new issue you're facing!

Looking forward to your suggestions on the docs ;)

**Comment by suyashbhatt** [comment]
Closing issue
