### ISSUE TITLE
Problem while trying to download RCML

### ISSUE THREAD

**Issue by suyashbhatt** [RestComm/Restcomm-Connect#2778]
I have been trying to setup RC in Digital Ocean Droplet with a domain. I had some other issue related to HTTPS which was due to Organization not binding domain name #2774 which @gsaslis helped me figure out . Now that issue is resolved but I am unable to place calls over HTTPS getting error `500 Problem to setup the call` `Reason: Problem while trying to download RCML`. 

I know [HTTPS documentation](http://documentation.telestax.com/connect/configuration/Restcomm%20-%20Enable%20HTTPS%20secure%20connector%20on%20JBoss%20AS%207%20or%20EAP%206.html#secure) has pointed out that if `RESTCOMM_HOSTNAME='YOUR_HOST_NAME'` is not set I will be hitting this issue. I am using docker to deploy RC and my `docker-compose.yml` already has environment variable `RESTCOMM_HOSTNAME: 'YOUR_HOST_NAME'` set. I can also verify that `restcomm.conf` file has `RESTCOMM_HOSTNAME='YOUR_HOST_NAME'` in place which should have resolved the problem I am facing but regardless of that I am still getting this error.

**Comment by suyashbhatt** [comment]
This issue only occurs while trying to call number in RC (ex. +1234). Calls to client are successful. Error console logs while trying place call from [Olympus Web](https://gist.github.com/suyashbhatt/0c9728524e12c2bbba76103d7736782a#file-olympus-web-error-txt-L210) and [Olympus Android](https://gist.github.com/suyashbhatt/231948879ee588b418fac1e85aa11ab4#file-olympus-android-error-txt-L1008-L1019)

**Comment by gsaslis** [comment]
@hrosa this sounds to me like it's similar to a problem we were discussing a couple of weeks ago... 

Could you please take a quick look here?
