### ISSUE TITLE
Developer users are unable to modify their password in the UI

### ISSUE THREAD

**Issue by ammendonca** [RestComm/Restcomm-Connect#2786]
When a user with the `Developer` role tries to modify his password on the UI, it fails as the whole user profile is being sent and the `role` property cannot be modified by such users.

Possibly, [here](https://github.com/RestComm/Restcomm-Connect/blob/master/restcomm/restcomm.http/src/main/java/org/restcomm/connect/http/AccountsEndpoint.java#L520-L527), the backend could check if there's not modification on the role and let the operation go on if there isn't.. @gvagenas thoughts ?

Anyway, in the UI, we should only send the modified fields.

**Comment by gvagenas** [comment]
@ammendonca `Developer` role has all permissions in the Accounts endpoint. Also the endpoint doesn’t check role…. I have to further check on this
