### ISSUE TITLE
Traffic throttling extension

### ISSUE THREAD

**Issue by gvagenas** [RestComm/Restcomm-Connect#282]

**Comment by gvagenas** [comment]
Support for Voice, SMS and USSD traffic

**Comment by deruelle** [comment]
Ensure we can restrict # of calls, SMS per account and that there is a correct error code similar to Twilio ones when the traffic is above the threshold

**Comment by gvagenas** [comment]
Restrict the number of DIDs per account

**Comment by deruelle** [comment]
We need API for throttling:

- [ ] Throttle number of allowed DID to be purchased per account (including sub accounts)
- [ ] Throttle number of Restcomm Client to be created (including sub accounts)
- [ ] Throttle inbound or outbound any calls and SMS per DID
- [ ] Throttle inbound or outbound any calls and SMS per Account
- [ ] Throttle inbound or outbound any calls and SMS per Restcomm Client

Allow to throttle Calls and SMS by
- [ ] number of concurrent voice/video sessions
- [ ] number of SMS per second
- [ ] number of calls per second

**Comment by deruelle** [comment]
We also need to be able to restrict Account capabilities:

- [ ] DID purchase

**Comment by gvagenas** [comment]
As discussed with @deruelle for now we throttle only SMS that are proxied out, no throttle to P2P IP Messaging for now
