### ISSUE TITLE
Automated voice saying TRIAL every few seconds while making audio/video calls

### ISSUE THREAD

**Issue by suyashbhatt** [RestComm/Restcomm-Connect#2831]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
When call is answered/made from specific device audio is blocked and it says `TRIAL` with lady's voice in every few seconds.
**What you expected to happen**:
Calls to go through like normal and not have automated voice say trial.

**How to reproduce it (as minimally and precisely as possible)**:
Reason on why this happened is unknown. I redeployed Restcomm 8.3.0-140 with docker compose with same setup I had before.

**Anything else we need to know?**:
Test calls were made after long time  since I was working on other features of the app and all the call made to and from one specific device with any client logged-in gives this issue. using same clients on other devices are fine.

**Environment**:
- Restcomm Connect version (from startup logs): `Restcomm 8.3.0-140`
- Cloud provider or hardware configuration: `DigitalOcean Droplet, 4 GB Memory / 25 GB Disk`
- OS (e.g. from /etc/os-release): `Ubuntu 16.04.3 LTS`
- Kernel (e.g. `uname -a`): `4.4.0-112-generic`
- Deployment method (e.g. `docker-compose`, with linked `docker-compose.yml` file, 
or application server info + deployment option): [`docker-compose`](https://gist.github.com/suyashbhatt/49988c5ea42cb2909fe2da9bfd04f127)
- Others:
`N/A`

**Comment by suyashbhatt** [comment]
Hi RestComm team, is there any update on this issue?

**Comment by gsaslis** [comment]
Hi @suyashbhatt ! 

Thanks for raising this. 

I see we are missing steps to reproduce the issue... Is that something you can help nail down? 
If not I guess we'll just have to wait until someone else also stumbles upon this and can help us out with providing such detailed steps that result in the issue occurring. Otherwise I don't believe we'll have much progress on this soon...

**Comment by suyashbhatt** [comment]
I tried a lot but I have no idea why this is happening. I even tried to find references of word trial in RC code. But could not find anything. Voice is definately from text to speech api. But I have no idea what is triggering this. It is persistent even after redeploying RC.

**Comment by suyashbhatt** [comment]
Is there any limit on how many calls/messages can be sent or maybe number of connections are limited. I havent seen any limitations anywhere so far but just asking.

**Comment by suyashbhatt** [comment]
Finally found why it was doing it. My client device had Virtual Audio Cable installed and for some reason chrome was using it as default device rather than hardware microphone. turns out its not restcomm issue its was issue in my client device.

**Comment by gsaslis** [comment]
thanks so much for reporting back @suyashbhatt !
