### ISSUE TITLE
Spam Prevention - Raise alarm if DID is receiving and sending too much SMS

### ISSUE THREAD

**Issue by croufay** [RestComm/Restcomm-Connect#302]
Check and raise an alert if a DID is receiving or Sending a lot of SMS within a determined time frame. 

There can also be some form of SMS throttling

**Comment by croufay** [comment]
> Yes, if the send/receive rate for a number is higher (80%) within a given (5 minute) period than its normal rate (average 5 minute rate over the previous 24 hours), raise an alert. Simultaneously, the send rate can be bumped up (3x) to slow down potential spam attack, but not totally block in case its legit traffic. For every 5 minutes that the unusually high traffic continues, new alert message can be sent and the defensive delay can be further increased until traffic slows down or admin intervenes.

**Comment by gvagenas** [comment]
This is covered by the traffic throttling extension
