### ISSUE TITLE
Update database schema from the Restcomm core

### ISSUE THREAD

**Issue by croufay** [RestComm/Restcomm-Connect#308]
As we discuessed your next task would be to enable Database schema updates from the Restcomm core itselft.

That means that when Restcomm starts it should check the Database schema and update it if needed.

Some of the requirements and thoughts I have on the issue:

    The schema update should work for any database engine we support, that means for HSQL or MariaDB
    We should introduce a new table Version that we should keep the schema version, This way it would be easier to know if we need to update the schema and from what version.
    The schema update can be done in two way in my opinion:
        In the bash script level: Using the auto-config scripts, we can add one more bash script that will check what is the active DB (hsql or MariaDB) and then will proceed to check the DB schema and update if needed,
        In the Restcomm core: Using Java and MyBatis, see here: https://mybatis.github.io/migrations/runtime-migration.html
    For any of the above methods (bash script or java/mybatis) as a best practice we should have an sql file with the changes needed to be done, this way every developer that changes schema will need to change the HSQL sql files, the MariaDB sql files AND the update sql files (for HSQL and MariaDB).

Let me know what you think

Charles,

The upgrade process should be left outside the Restcomm core, for example using the upgrade script for the AMI or docker pull for the docker image etc.
After Restcomm core upgrade is done, the Migration tool will take care to upgrade the schema.

We should provide a REST API endpoint though that will check for new Restcomm version and provide a notification to the user.

The Restcomm version should be left out of the DB.

The DB should have a table with the schema version that could be the same with the Restcomm version but its not necessary to be the same.

**Comment by deruelle** [comment]
It's still unclear if that should be done at all as in a full cluster, if one instance upgrades the DB with non backward compatible changes, all the other instances in the cluster will fail. I think the database upgrade should be thought in the context of a cloud environment and provide best practices. Moving to 7.6.0 for now
