### ISSUE TITLE
Authentication of web triggers for RVD apps

### ISSUE THREAD

**Issue by scottbarstow** [RestComm/Restcomm-Connect#311]
In working with the RVD at TADHack, I came across the methodology for accessing the underlying Restcomm API.  

It seems that you have to configure a one-time username and password under the 'Settings' menu that the RVD uses to call down into Restcomm API.

This has a couple of problems:
1.  When this was not configured, I got no meaningful error response telling me what might be wrong. I got a generic 500 error with an HTML stack.
1. It would seem to me that it would make more sense to simply require authentication on the web trigger, and configure it there.  It's easy to see a scenario where I want to use different users for different apps.  

Suggest the following changes:
1. If web trigger requires a real user in order to execute the telephony APIs, then it should be configured on that screen.  Select an existing user or just enter un/pw as you do on the Settings screen.  The current methodology is non-obvious and will be frustrating for users.  It's not clear to me what the ramifications of this are when distributing apps, so there may be a better solution here, but passing BASIC auth credentials to the web trigger is easily done by any client.
1.  When / if authentication fails, the response must have an API-consumable error message.

**Comment by otsakir** [comment]
Related to #592

**Comment by otsakir** [comment]
In addition to HTTP authentication implemented in #592, specifying a different user to execute the trigger seems like an nice feature that can be built on top of #592.

**Comment by otsakir** [comment]
This issue was moved to RestComm/visual-designer#76
