### ISSUE TITLE
Call search method fails when StartTime filter is used

### ISSUE THREAD

**Issue by otsakir** [RestComm/Restcomm-Connect#342]
Using REST for querying for calls fails if the StartTime option is specified. For example, following query fails with an 'invalid date syntax' excpetion:

curl -v -X GET '...../restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/Calls.json?StartTime=2015-01-01'

The issue has been confirmed for hsql setup. I don't know what happens with mysql.

**Comment by ammendonca** [comment]
This has been fixed.
