### ISSUE TITLE
RVD - Improper English in Project chooser dialog

### ISSUE THREAD

**Issue by scottbarstow** [RestComm/Restcomm-Connect#360]
Please _chose_ a sms project from the list below or create a new one

Should be:

Please _choose_ an  (for voice and SMS) and Please choose a for USSD

**Comment by croufay** [comment]
Hi scott,

What about this:

You may create new project or choose an existing project from the list below

**Comment by scottbarstow** [comment]
That works great

**Comment by otsakir** [comment]
This issue was moved to RestComm/visual-designer#73
