### ISSUE TITLE
Implement RVD visual components for presence based logic

### ISSUE THREAD

**Issue by ivelin** [RestComm/Restcomm-Connect#381]
Allow RVD apps to implement conditional logic based on user presence information. For example:

Forward incoming sales call to user (call center agent) if presence status is active in the past 10 minutes.

Related to #380

**Comment by otsakir** [comment]
Conditional logic could also be based on #317 which is more or less about creating an branching element in RVD. If that's the case the 'presense' aspect would be only about setting some RVD variables and let the branching element make the decistion.

@ghjansen , @ivelin  wdyt?

**Comment by ghjansen** [comment]
Sounds good to me @otsakir, if @ivelin agree we can go ahead this way, i think.

**Comment by otsakir** [comment]
This issue was moved to RestComm/visual-designer#71
