### ISSUE TITLE
Remember IDE status modules etc. per user/project

### ISSUE THREAD

**Issue by otsakir** [RestComm/Restcomm-Connect#403]
When a user re-opens a project he has already worked on it would be nice to remember which modules where open. Other IDE settings may also me remembered too.

The question is whether the 'remembering' will be per user, per project or per user-project.

**Comment by deruelle** [comment]
I would say per project so that even if someone else edit, the last edits or change could be seen ?

**Comment by ghjansen** [comment]
I agree with "per project" approach. Considering that projects are now even closer to the applications, may a given same project won't be accessible from different users frequently, so "per user-project" approach seems not worth it.

**Comment by otsakir** [comment]
This issue was moved to RestComm/visual-designer#69
