### ISSUE TITLE
Olympus gets no Audio when dialing apps like 1234

### ISSUE THREAD

**Issue by croufay** [RestComm/Restcomm-Connect#452]
Olympus client to client works but when you dial an application like 1234 or 1235 you get no reply 

The logs shows the following

13:25:24,305 ERROR [org.mobicents.protocols.mgcp.stack.JainMgcpStackProviderImpl] (Thread-603) The TransactionHandler not found for TransactionHandle 7 May be the Tx timed out. Event = 400 0The transaction could not be executed due to a transient error.

**Comment by thanhthuy40** [comment]
same me!

**Comment by croufay** [comment]
fixed
