### ISSUE TITLE
Try Fallback Voice URL when Voice URL returns 404

### ISSUE THREAD

**Issue by peteroyle** [RestComm/Restcomm-Connect#468]
Hi,

As per google group discussion at: https://groups.google.com/forum/#!topic/restcomm/KxIl8BCmkOQ

When RestComm receives a 404 from the Voice URL response it simply forwards that 404 to the caller. I would like to see RestComm instead failed over to the Fallback Voice URL in that situation. This would make the Fallback Voice URL useful in the following scenarios:

- HTTP proxy used to serve the RCML is down
- HTTP proxy is up but all application servers behind it are down
- HTTP proxy is up, application servers are also up, but the RCML application is not deployed
- IncomingPhoneNumber is misconfigured with a problematic Voice URL, but the Fallback Voice URL works

All of the above scenarios return a 404 which would currently result in RestComm ending the call, rather than attempting the Fallback Voice URL.

I have created 3 new failing tests in the RestComm test suite to capture the way I would like RestComm to behave under these 3 conditions:
- If Voice URL returns a 404, try the Fallback Voice URL straight away
- If the Voice URL contains a hostname which doesn't resolve, try the Fallback URL (whether straight away, or after a timeout of maximum 5 seconds)
- If the Voice URL times out, try the Fallback Voice URL within 5 seconds
These tests can be found in the pull request here: #424 

cc @leftyb

**Comment by gvagenas** [comment]
relates to #479

**Comment by peteroyle** [comment]
Hi Folks. Is there any chance this will make it into 7.6.0 before the code freeze on April 8th please? I have just had a good look at https://github.com/leftyb/RestComm/commit/07ecc47a8e1eb825b462e82fee0dd0d7a52a9394 and it looks right to me. Do we know yet whether this commit makes the tests I provided pass?

**Comment by gvagenas** [comment]
@peteroyle the fallback url is already supported and this one here is a duplicate. Can you please test the latest Restcomm and report here?

**Comment by peteroyle** [comment]
Thanks @gvagenas I'll try it out soon. Can you please tell me where to find the other ticket which this duplicates?

**Comment by gvagenas** [comment]
PR https://github.com/RestComm/Restcomm-Connect/pull/528 closes this issue

**Comment by peteroyle** [comment]
Hi @gvagenas, you are right. I tested the fallback URL in the latest build and it's working fine. Thanks!
