### ISSUE TITLE
Redirect to account details after creating new Restcomm account with AdminUI

### ISSUE THREAD

**Issue by otsakir** [RestComm/Restcomm-Connect#547]
After creating a new Restcomm account using AdminUI/"Create New Account" the account details view should appear allowing for further customization.

**Comment by hunglevan2017** [comment]
Hi @otsakir  can I start on this task.

**Comment by otsakir** [comment]
Hi @hunglevan2017 !

It looks like a lot has changed since the issue was created and seems that it no longer applies. I'll close the issue as invalid.

Thanks for stepping up and sorry for the inconvenience. 

Orestis
