### ISSUE TITLE
RVD cannot return application list for user sub-accounts

### ISSUE THREAD

**Issue by otsakir** [RestComm/Restcomm-Connect#568]
RVD can only return the applications that belong to the logged account. There is no way to request a list of applications that belong to a sub-account of the current account (no parameter in the URI). And even if it were, RVD has no account hierarchy information so can't really make such a filtering. 

The issue will be solved when application listing passes to Restcomm instead of RVD: #552 and #530

**Comment by ghjansen** [comment]
@otsakir considering the multi-tenancy validations performed on Applications REST API (RestComm side), each Account can access its own Applications, so the intended logic with this issue violates this principle.

I remember that this multi-tenancy validation was created in compatibility with Twilio, and its behaviour is a little distinct from other endpoints. Do you mind to enumerate some scenarios where the Applications list of a sub-account would be required? So we can keep thinking about this.

**Comment by otsakir** [comment]
Indeed @ghjansen, i will close this issue as invalid. It's probably a leftover of the old times when it was not really clear how multi-tenancy will be implemented.
