### ISSUE TITLE
RVD Automatically clear browser cache after upgrade

### ISSUE THREAD

**Issue by ivelin** [RestComm/Restcomm-Connect#57]
Going to a direct link results in nonsensical view:

http://------:8080/restcomm-rvd/#/designer/MAINivrVoiceMAILonly%20(1)

![screen shot 2014-10-06 at 3 26 48 pm](https://cloud.githubusercontent.com/assets/2234901/4532864/1b13ac32-4d97-11e4-8536-2a1562a49985.png)

**Comment by otsakir** [comment]
There are automatic "build" tools for the client applications that pack all .js code into a single file for deployment. For each release this file has a different name effectively avoiding cache issues. Typically, javascript grunt can help in that direction. html template caching is still an issue.

**Comment by otsakir** [comment]
This issue was moved to RestComm/visual-designer#88
