### ISSUE TITLE
Push SMS in RVD USSD projects

### ISSUE THREAD

**Issue by FerUy** [RestComm/Restcomm-Connect#588]
As it is contemplated for voice project, RVD should add a push SMS option for USSD projects. It's a widely used feature in classical USSD projects (e.g. the result of a monetary transaction should be sent by SMS rather than thru USSD, as it would likely take longer than the USSD single interaction timeout and would be stored in the user equipment either).

**Comment by deruelle** [comment]
This should be factored in the RVD future refactoring

**Comment by otsakir** [comment]
Hi @FerUy, 

You mean that one should be able to send an SMS from a USSD application. Correct ? Indeed, RVD misses such an element. I also think that this is not supported at the RCML either. @gvagenas ?

Also, @FerUy, can you please briefly give an example on the use case with USSD timeout you described? If i got this right, it may occur that restcomm/RVD takes too long to build a USSD response because the application operation takes too long (e.g. a monetary transaction). In that case it's good practice to make the application should also send an SMS to the mobile device to make sure the user got the message. Is that correct ?

**Comment by FerUy** [comment]
@otsakir exactly, you got it right.

A use case that is very common: Top ups (recharge prepaid subscriber's accounts). Not only the interaction with the online charging system may take time and it's better to close the USSD session, release resources and send an SMS when the time is right (which also has the advantage of store and forward in case of failure), but as a security notification for either the retailer and customer (they both get the same transaction id, so the customer is sure he's not been cheated). All mobile financial services have similar behaviours regarding receipts/bills notifications, and SMS is better for that (as it is also stored in memory).

Another one: SIM activation via USSD. The process always takes some time (1-2 minutes or more), so depending only on USSD to notify a successful or failed transaction is inconvenient.

All in all you got it right from the beginning, just giving you some more examples (there are more).

Thanks

**Comment by FerUy** [comment]
Oh... I forgot another one I'm working for a lot @otsakir: location services in cellular networks. To retrieve current geographic information of the user equipment, positioning methods take some time (30 seconds in average for triangulation and processing information), so it's better also to release resources taken by the USSD session and later send the SMS when the network returns the location information back to Restcomm. This location information could also be tied to mobile advertising for example, then more than one SMS could be needed (one for the location information itself, another one for other kind of related info).

**Comment by otsakir** [comment]
Thanks for the feedback @FerUy. Let me discuss this with @gvagenas to see what can be done in the context of a USSD application.

**Comment by FerUy** [comment]
You're welcome @otsakir, anytime.

**Comment by gvagenas** [comment]
@otsakir USSD application is an extension of the RCML so no worries to break any spec if we add SMS for USSD apps.
If SMS in USSD applications make sense and there are use cases where we need this, I am fine to support this. 
To support SMS in USSD applications we need support from Restcomm side besides RVD.
I created Issue #1730 for this and provided label "Help Wanted"

**Comment by otsakir** [comment]
This issue was moved to RestComm/visual-designer#61
