### ISSUE TITLE
AdminUI allows creation of sub-accounts from within sub-accounts

### ISSUE THREAD

**Issue by otsakir** [RestComm/Restcomm-Connect#594]
The policy on account creation is not clear and needs to be defined. Currently even sub-accounts can create grand-sub-accounts in AdminUI. Should we disable it?

If several account levels are to be allowed we should take it into account in multitenancy access rules also.

@gvagenas, @deruelle comments here?

**Comment by ghjansen** [comment]
Considering Twilio design, we have three main components:
**E-mail** (1): Used to establish the first contact with Twilio platform, and have access to all its services;
**Master Account** (1..\*): The first effective layer of accounts available to use with the API;
**Sub Account** (0..\*): Accounts created from a Master Account, with a hierarchically dependent nature.

Like this:
![untitled diagram](https://cloud.githubusercontent.com/assets/1459428/10846776/3665fed8-7ef9-11e5-82f1-1290c4a3f37a.png)

In our current design we don't have this **E-mail** layer, and i'm not sure that we need something like that for now, but I agree with two-levels hierarchy (Master accounts + Sub accounts).

**Comment by deruelle** [comment]
@otsakir this is a question related to SSO ? 
@ghjansen can you share you document related to how Twilio works with regards to Multitenancy so things are clearer for @otsakir  ?

**Comment by otsakir** [comment]
@deruelle , if i got this right and judging from @ghjansen schematic, there are two levels of accounts. Master accounts and sub-accounts in twilio. So it seems wrong to allow sub-accounts to create additional child sub-accounts on their own. I've also studied Gui's document and experimented with the actual twilio API. The conclusion from experimentation was that ALL sub-accounts had Master Account as parent. 

In SSO branch this functionality is disabled already (in terms of AdminUI). I was thinking whether we should do the same in the main branch.

**Comment by otsakir** [comment]
@deruelle, @gvagenas, i further investigated accounts in twilio docs. I confirmed that only Master accounts are allowed to have subaccounts. Shall we also deprecate long nesting ?

I

**Comment by deruelle** [comment]
@ghjansen might be provide a more thoughful answer based on his investigations with multitenancy. But I would tend to follow Twilio indeed.

**Comment by ghjansen** [comment]
@deruelle i agree with the idea to remove the n-level support for accounts nesting and keep it as 2-levels, like Twilio does currently. I don't see a clear benefit by keep it unlimited and perhaps it bring some problems in the future, as discussed in a parallel conversation between me an @otsakir .

Just to remember, here is the document about multi-tenancy:

https://docs.google.com/a/telestax.com/document/d/1zjZts9a86oL9xV2wlADJ5m2BA96flvPJ8gQ2qRWErJE/edit?usp=sharing

**Comment by deruelle** [comment]
agreed then. please make modifications so we have backward compatible behavior with Twilio here.

**Comment by ammendonca** [comment]
Already implemented limit in sub-accounts level, as in https://github.com/RestComm/Restcomm-Connect/blob/665e292da5d9f7d25e35a44edc56a8f9d1a53bc2/restcomm/restcomm.http/src/main/java/org/restcomm/connect/http/AccountsEndpoint.java#L415-L420
