### ISSUE TITLE
RVD: Continue to other modules after ending the initial flow call/session.

### ISSUE THREAD

**Issue by FerUy** [RestComm/Restcomm-Connect#629]
There’s no way to, for instance, end a USSD session and at the same time, continue to another module within the application’s scope. For example, sometimes it may be needed to end a USSD session to start actions, sometimes for security reasons. Examples: execute a MAP ATI for retrieving the user’s state which must be “idle” to proceed, a state that can’t be obtained during a USSD session; sending an SMS with the result of a financial transaction; start a call; execute a location service, etc.

**Comment by otsakir** [comment]
@FerUy , i'm moving this issue to RVD repo. 

However, before getting to RVD implementation, an RCML spec for what you describe should be settled with the vvs. Once this is reached we could proceed with the RVD part.

**Comment by otsakir** [comment]
Issue moved to [RestComm/visual-designer #270](https://github.com/RestComm/visual-designer/issues/270) via [**ZenHub**](https://www.zenhub.com/)
