### ISSUE TITLE
Improve error feedback when the operation Save Project fails

### ISSUE THREAD

**Issue by ghjansen** [RestComm/Restcomm-Connect#670]
With a new RVD Project created, sometimes while editing the project, a inconsistent state can be reached affecting the the success of the "Save" operation. This can be caused by leaving mandatory fields empty or another state not allowed by the validation process.

Currently, a generic warning message is displayed informing that the project was saved with errors. Besides this message, would be very helpful if possible to point a specific message that helps the user to locate the inconsistency inside the modules/verbs of his project.

**Comment by ghjansen** [comment]
Issue created based on:
http://stackoverflow.com/questions/33943360/restcomm-visual-designer-project-issues-when-saving

**Comment by otsakir** [comment]
A quick improvement would be to add an additional "exclamation mark" in the label (tab) of the module that contains the faulty element.

**Comment by otsakir** [comment]
This issue was moved to RestComm/visual-designer#57
