### ISSUE TITLE
Cancelling a call fails from Android SDK or Jitsi to Olympus Web

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/Restcomm-Connect#683]
Scenario:
- Make a call from Android Olympus or Jitsi to Olympus Web
- While the call is ringing in Olympus Web CANCEL it from the caller side

Important note: this is only reproducible at the cloud (i.e. staging.restcomm.com). In my own amazon instance it isn't

At this point the call doesn't stop ringing and JS console shows that the CANCEL never arrives. RestComm logs showing no outgoing CANCEL towards Olympus can be found at:

https://gist.github.com/atsakiridis/8df1315e64d4116a7cf7#file-restcomm-server-log-L872

@gvagenas, @deruelle: same scenario but with Olympus Web on the callee side works, so its like it only works between websocket clients for some reason. 

P.S. I also took a trace from the good scenario from my AMI cause I wanted to compare the logs, make sure the lack of CANCEL is not a missing trace statement:

https://gist.github.com/atsakiridis/0c217ff9c565a050f3d2#file-restcomm-server-log-L90

**Comment by deruelle** [comment]
which version do you use in your instance ? we will need to enable DEBUG logs to see what's going on in terms of routing at the SIP Servlets layer. But indeed it looks like the CANCEL is not created for the Olympus leg

**Comment by deruelle** [comment]
and no 487 response is sent either...

**Comment by atsakiridis** [comment]
@deruelle I've tried both with 7.4.LATEST and 7.5.LATEST. I'll try with DEBUG and let you know

Thanks

**Comment by ammendonca** [comment]
Not reproducible anymore.
