### ISSUE TITLE
Create a SPI for Workspace Management

### ISSUE THREAD

**Issue by ghjansen** [RestComm/Restcomm-Connect#714]
As discussed on issue #530 and also by mail, we should have a new layer for the way RVD is currently storing projects in workspace. The goal of this new layer is to turn the projects storage into a SPI, allowing workspaces different than file system, like MongoDB and others.

So in near future, "Workspace Manager SPI" in the image below could be also another implementation called "MongoDB Manager", not only the "FS Manager".

![530-4](https://cloud.githubusercontent.com/assets/1459428/11656490/b91920be-9d9c-11e5-9263-e65cc902755e.png)

**Comment by otsakir** [comment]
This issue was moved to RestComm/visual-designer#56
