### ISSUE TITLE
Monitis SIP down alert .

### ISSUE THREAD

**Issue by leftyb** [RestComm/Restcomm-Connect#733]
The last days we have been receiving  fluent alerts on SIP requests failures from Monitits. On cloud.restcomm.com. In general, all the times, we receive a "service recovery (UP) mail" after a minute approximately or even after some seconds.

The same issue happened today in the morning at around  (06:23 AM)

The monitis Ip is :
http://whatismyipaddress.com/ip/173.193.219.173

Which can be located at the restcomm log file. As well pcap file of this time  :
https://app.box.com/files/0/f/5763264993/Monitis_alerts_issue_733

Here for a quick look, there is a "WARN" appearing at this specific time for this IP :
https://gist.github.com/leftyb/022c358620c49daa2cf1

**Comment by gvagenas** [comment]
@leftyb From the logs I can see the the OPTIONS request arrives 06:23:28,556 and Restcomm responds with a 200 OK at 06:23:28,563, 7 ms later.
So definitely this is not Restcomm issue.

There might be a delay on the network that causes the 200 OK from Restcomm to arrive late at Monitis service.
I would suggest you to check the Monitis settings, maybe there is a configurable timeout there that you can increase.

**Comment by leftyb** [comment]
@gvagenas  George same issue occurred tonight at about the same time, 06:20 AM (server time).
Monitis report:
```Dec-16-15      08:20 (Users time)     0.0     NOK     FR
China
SIP timeout: No response from SIP server after 10 seconds ,
France
SIP timeout: No response from SIP server after 10 seconds```

RestComm log file of today's monitis report :  
https://app.box.com/files/0/f/5763264993/1/f_46923785425

The timeout at the monitis service is set to 10secs, I just rise it to 15 secs.
