### ISSUE TITLE
Adapt Arquillian and RVD allowing testsuite to use RVD as deployment

### ISSUE THREAD

**Issue by ghjansen** [RestComm/Restcomm-Connect#747]
Currently, testsuite only uses restcomm.war as deployment, so in order to have testsuite working with restcomm-rvd.war, some adaptations may be required.

Some tests executed with RVD as a deployment in a new prototyped testsuite scenario revealed two main parts to start analysing:

1 - **sip.xml configuration**. This file is already used by Restcomm and is currently required to execute testsuite. Also, it contains several configurations (like bootstrap) that should be adapted for RVD's usage, or elaborate in another way to provide for Arquillian the information needed when using RVD as deployment.
2 - **restcomm.xml configuration**. At some point of RVD bootstrap, we currently consult informations present inside Restcomm configuration file, which doesn't work pretty well considering the context naming convention used by testsuite's Tomcat Embedded container. Considering this, probably some adaptations on RVD side will be needed as well.

Another adjustments could also appear while looking closer, so we probably have to brainstorm some more options.

Having testsuite running with RVD context could be very useful for issue #714 .

**Comment by otsakir** [comment]
RVD (alone) already uses Arquilian for integration testing in the rvd.testsuite package. Restcomm integration testing won't be done using arquillian but but a binary built using the normal procedure.

Closing the issue as obsolete.
