### ISSUE TITLE
Adapt multi-tenancy to work with DNS organization namespace

### ISSUE THREAD

**Issue by ghjansen** [RestComm/Restcomm-Connect#748]
Review and adapt the concept of the current implementation of multi-tenancy (done on issues #87 and #4) to properly deal with DNS organization namespace.

The DNS organization namespace should work in the same style as Slack and another services already does. So if the organization 'FooBar' starts using Restcomm Cloud, they will access the cloud using "foobar.restcomm.com" and manage the information related to their domain only.

Evaluate the possibility to consider the domain as a top level, above the accounts.

**Comment by ghjansen** [comment]
Design/Brainstorm document: https://docs.google.com/document/d/1On1cqXMQBjzgNdXqEXT851BUMb3X61UJk4qU3hQDNZw/edit

**Comment by ghjansen** [comment]
@gvagenas @otsakir @deruelle Organizations elementary parts seems to be in place. Here follows my manual access test scenario and results.

* `/etc/hosts` configuration for access over **loopback interface** (127.0.0.1):
```
127.0.0.1 ax foobar foobar.restcomm.com xpto xpto.restcomm.com
192.168.25.104 ax 
```
* `/etc/hosts` configuration for access over **ethernet interface** (192.168.25.104):
```
127.0.0.1 ax 
192.168.25.104 ax foobar foobar.restcomm.com xpto xpto.restcomm.com
```
* Entity hierarchy created inside RestComm:
```
+ Default Organization          + Foobar Organization          + XPTO Organization
|                               |                              |
+-- Administrator Account       +--+ Foobar Account            +--+ XPTO Account
                                   |                              |
                                   +-- Subaccount Foo             +-- Subaccount XP
                                   +-- Subaccount Bar             +-- Subaccount TO
```
* Results for access over IP using loopback or ethernet interfaces:
 * **Accounts allowed:** all
 * **Accounts denied:** none

* Results for access over DNS **foobar** or **foobar.restcomm.com** using loopback or ethernet ethernet interfaces:
 * **Accounts allowed:** Foobar Account, Subaccount Foo and Subaccount Bar
 * **Accounts denied:** Administrator Account, XPTO Account, Subaccount XP and Subaccount TO

* Results for access over DNS **xpto** or **xpto.restcomm.com** using loopback or ethernet ethernet interfaces:
 * **Accounts allowed:** XPTO Account, Subaccount XP and Subaccount TO
 * **Accounts denied:** Administrator Account, Foobar Account, Subaccount Foo and Subaccount Bar

So, i think the results matches with the desired behaviour. Please, if you guys are able to test this as well it will be good, because there are a lot of possibilities and i may miss something.

I'll open the PR for what is finished until now and try to continue on #1095 by tomorrow/today.

**Comment by deruelle** [comment]
That looks good to me. Shall we have a master account above all that can create / delete organizations and see all accounts and subaccounts  ?

**Comment by ghjansen** [comment]
@deruelle Currently, the `Administrator` Account (RestComm Admin) is able (solely) to create/read/update/delete all Organizations, but there is no such thing yet considering Accounts. To see all Accounts from a Organization, the `Organization Administrator` Account, which is a master Account, must access the `/Accounts.json` or `/Accounts` endpoint to obtain the complete list of sub accounts, which is equivalent to all Accounts in his Organization.

You see this as enough, or maybe we should include something else?

**Comment by deruelle** [comment]
ok that's enough then. We will have a mode for impersonating users as part of #715 and #716

**Comment by ghjansen** [comment]
Mostly done. Only be sure that the current behaviour is the expecte one.
