### ISSUE TITLE
Refactor VoiceInterpreter to cleanup and extract methods from onReceive() method

### ISSUE THREAD

**Issue by gvagenas** [RestComm/Restcomm-Connect#794]
VoiceInterpreter onReceive() method is a huge spaghetti and needs cleanup and extract to external methods for many of the FSM handling such as handling of the CallStateChanged events, FSM for dial forking, dial action execution etc.

**Comment by maria-farooq** [comment]
Hi @gvagenas 
I have started work on  #78 and according to my findings it involve changes in VoiceInterpreter.

**Comment by gvagenas** [comment]
Hi @maria-farooq , thanks for your update. 

You can proceed with the #78 issue and after your finish I will check your work. 

The VoiceInterpreter refactoring will work later this week or early next week, so you have the time to provide the patch for #78 before I start the refactoring.

Thanks
George

**Comment by gvagenas** [comment]
related issue #750

**Comment by gvagenas** [comment]
Closed by final commit 20ffc490625fdc74612c43bd8cd8651304b14c46
