### ISSUE TITLE
The sample RVD apps don't show up as 'linked' to the respective numbers in Admin UI incoming numbers screen

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/Restcomm-Connect#829]
Seems that the RVD apps are linked in reality, but don't show up as linked in the admin UI. As a result, when you make a call to a number (i.e. 1241) that appears in admin ui as not connected, you still get the gather RVD app. The other issue is that if you try to update the RVD app from the admin UI (for example change 1241 and 'link' it to RVD say demo) it still points to the old. 

As a result: 
- some numbers that are supposed to be linked to RVD show up unlinked and 
- an app is connected when calling the number from olympus and that app cannot be updated in admin ui

Here are the logs:

https://drive.google.com/file/d/0BwfD74mG87iMak5XdXF0VzFLdVk/view?usp=sharing

**Comment by otsakir** [comment]
@atsakiridis , after some investigation i noticed the following:

DIDs to demo RVD applications are created using the following query in restcomm.xml:
```
INSERT INTO "restcomm_incoming_phone_numbers" VALUES('PN46678e5b01d44973bf184f6527bc33f7','2014-02-17 22:37:08.709000','2014-02-17 22:37:08.709000','This is an IVR app that maps user input to specific action','ACae6e420f425248d6a26948c17a
9e2acf','+1240','2012-04-24',FALSE,NULL,'POST',NULL,'POST',NULL,'POST','AP73926e7113fa4d95981aa96b76eca854',NULL,'POST',NULL,'POST',NULL,'/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/IncomingPhoneNumbers/PN46678e5b01d4
4973bf184f6527bc33f7',NULL,NULL,NULL,NULL,TRUE,'0.0')
```

New DIDs, when mapped to an RVD applicationcontain no AP* sid foreign key. For example:
```
INSERT INTO "restcomm_incoming_phone_numbers" VALUES('PN8a4ea0898dfb4b85bd40752bae2d4e59','2016-02-01 14:18:51.259000','2016-02-01 14:18:51.259000','4455','ACae6e420f425248d6a26948c17a9e2acf','455','2012-04-24',FALSE,'/restcomm-rvd/servic
es/apps/SECOND%20TEST/controller','POST',NULL,'POST',NULL,'POST',NULL,NULL,'POST',NULL,'POST',NULL,'/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/IncomingPhoneNumbers/PN8a4ea0898dfb4b85bd40752bae2d4e59',NULL,NULL,NULL,N
ULL,TRUE,NULL)
```

Also, even when updating the default DIDs to RVD sample apps, the ApplicationSid (that contains the AP* SID) field does not change. Thus, we have a DID with the correct VoiceURL but an old ApplicationSid. 

This is the query that creates the 1240 initialy:
```
INSERT INTO "restcomm_incoming_phone_numbers" VALUES('PN46678e5b01d44973bf184f6527bc33f7','2014-02-17 22:37:08.709000','2014-02-17 22:37:08.709000','This is an IVR app that maps user input to specific action','ACae6e420f425248d6a26948c17a
9e2acf','+1240','2012-04-24',FALSE,NULL,'POST',NULL,'POST',NULL,'POST','AP73926e7113fa4d95981aa96b76eca854',NULL,'POST',NULL,'POST',NULL,'/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/IncomingPhoneNumbers/PN46678e5b01d4
4973bf184f6527bc33f7',NULL,NULL,NULL,NULL,TRUE,'0.0')
```
And this is the query that "updated 1240 to RVD 'test' application:
```
INSERT INTO "restcomm_incoming_phone_numbers" VALUES('PN46678e5b01d44973bf184f6527bc33f7','2014-02-17 22:37:08.709000','2014-02-17 22:37:08.709000','This is an IVR app that maps user input to specific action','ACae6e420f425248d6a26948c17a
9e2acf','+1240','2012-04-24',FALSE,'/restcomm-rvd/services/apps/test/controller','POST',NULL,'POST',NULL,'POST','AP73926e7113fa4d95981aa96b76eca854',NULL,'POST',NULL,'POST',NULL,'/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9
e2acf/IncomingPhoneNumbers/PN46678e5b01d44973bf184f6527bc33f7',NULL,NULL,NULL,NULL,TRUE,'0.0')
```
Notice the AP73926e7113fa4d95981aa96b76eca854 ApplicationSid remains the same in both inserts. Btw, The VoiceUrl is removed from the first query.

IMO, we should remove ApplicationSid from the creation of the default DIDs to RVD demo apps.

@ghjansen thoughts ?

**Comment by ghjansen** [comment]
I understand @otsakir @atsakiridis . This is a modification made by me while working on issues #4 and #87, following a suggestion of @gvagenas . Please check the item 2 in the following link:

https://github.com/RestComm/RestComm-Core/pull/499#issuecomment-149485769

This issue will be solved by the set of issues i'm currently working, that will allow users to configure DIDs with URLs or Applications as a mutual exclusion choice. Either way, i agree that the current state could be confusing and might generate some problems, so I agree to rollback the DIDs to use URL only and let the use of applicationSid to my next patch that will handle it in full.

**Comment by ghjansen** [comment]
@atsakiridis @otsakir @gvagenas i've reverted the DIDs 1239, 1240 and 1241 back to URLs, now the modifications on AdminUI behave as expected. PR #844 created for this issue.

**Comment by ammendonca** [comment]
Fixed, as mentioned above.
