### ISSUE TITLE
Support urls to .wav in DialConference waitUrl parameter

### ISSUE THREAD

**Issue by otsakir** [RestComm/Restcomm-Connect#841]
Currently, in RVD's Dial/Conference waitUrl is populated with a link to an RVD module (i.e. RCML). In addition to that returning a direct link to a .wav should be supported. 

Check the details of waitUrl here: 
http://docs.telestax.com/restcomm-rcml-conference/

**Comment by gvagenas** [comment]
related to #842

**Comment by otsakir** [comment]
issue fixed as of 11f68c0
