### ISSUE TITLE
Login to RVD with "inactive" account works but project management fails

### ISSUE THREAD

**Issue by otsakir** [RestComm/Restcomm-Connect#849]
Although RVD login is allowed when an inactive account is used, further operations that involves usage of the Restcomm REST API fails. The reason is that RVD login relies on:

<code>GET /restcomm/2012-04-24/Accounts.json/administrator@company.com</code>

which works for inactive accounts. But creating an application afterwards will fail as

<code>POST /restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/Applications.json </code>

also checks account status (i.e. active/inactive).

I suggest rejecting RVD logins if an account is inactive.

**Comment by ghjansen** [comment]
I agree with your approach @otsakir .
I've executed some tests and the validation of the account status is executed one step before multi-tenancy validations, and is present in all endpoints but not in Accounts Endpoint, what seems to be right.

So once the REST API is ok, I agree to make RVD reject logins the account is inactive.
