### ISSUE TITLE
Need to add a scroll bar at the sub accounts list.

### ISSUE THREAD

**Issue by leftyb** [RestComm/Restcomm-Connect#856]
When the the registered users are more than a certain number, not possible to see the last users in the list. Need to zoom out to be able to see them all.
![sub_accounts](https://cloud.githubusercontent.com/assets/4802924/12898434/5d9c202a-ceb5-11e5-8246-477f094ee081.png)

**Comment by deruelle** [comment]
Since the number of sub accounts can go to 1000. I think a More... link to the dedicated page with paging and searching would be more effective than an scroll bar. Added Help Wanted tag for contributors here.

**Comment by muhammadbilal19** [comment]
@leftyb @deruelle 
I created a table of subaccounts with pagination and filters. Please have a look and let me know if you want to add anythings else in it.If you guys are ok with design i will commit my code.


![restcomm](https://cloud.githubusercontent.com/assets/8377490/15982883/3660d880-2fe9-11e6-90d6-6258f280ab92.png)

![subaccounts](https://cloud.githubusercontent.com/assets/8377490/15982884/3ad95298-2fe9-11e6-9e0c-7f4587f4a370.png)

![subaccountsfilters](https://cloud.githubusercontent.com/assets/8377490/15982886/3ea78304-2fe9-11e6-9954-47ec7276c9fc.png)

**Comment by deruelle** [comment]
@muhammadbilal19 great ! did you do a PR of that ?

**Comment by muhammadbilal19** [comment]
@deruelle sure i will create a PR for that fix today.

**Comment by muhammadbilal19** [comment]
@deruelle PR created for this issue.
