### ISSUE TITLE
Callback Url and Record Action not showing variables

### ISSUE THREAD

**Issue by croufay** [RestComm/Restcomm-Connect#859]
Has there been changes to the status callback feature of restcomm in the latest release?
has there been.. I am using peter spruce .war file and I am only getting part of the Callback status response

I was expecting to see the following = Possible values are queued, ringing, in-progress, completed,

**********************CONSOLE OUTPUT*****************************

croufay@localhost restcomm]$ tail -f /home/croufay/telestax/test/Mobicents-Restcomm-JBoss-AS7-7.5.0.786/standalone/log/server.log | grep stdout
08:46:44,528 INFO  [stdout] (http-/192.168.1.3:8080-5)                                       (DialCallDuration=0)
08:48:18,635 INFO  [stdout] (http-/192.168.1.3:8080-5) ------- Recording
08:48:18,635 INFO  [stdout] (http-/192.168.1.3:8080-5)                                       (CallSid=CA1b07b62c37ea4ab89a6e98a83597545b)
08:48:18,635 INFO  [stdout] (http-/192.168.1.3:8080-5)                                       (CallStatus=ringing)
08:48:18,636 INFO  [stdout] (http-/192.168.1.3:8080-5)                                       (CallDuration=null)
08:48:18,636 INFO  [stdout] (http-/192.168.1.3:8080-5)                                       (DialCallSid=null)
08:48:18,636 INFO  [stdout] (http-/192.168.1.3:8080-5)                                       (DialCallStatus=null)
08:48:18,637 INFO  [stdout] (http-/192.168.1.3:8080-5)                                       (DialCallDuration=null)
08:48:30,290 INFO  [stdout] (http-/192.168.1.3:8080-4) ------- Hanging Up
08:48:30,291 INFO  [stdout] (http-/192.168.1.3:8080-4)                                       (CallSid=CA1b07b62c37ea4ab89a6e98a83597545b)
08:48:30,291 INFO  [stdout] (http-/192.168.1.3:8080-4)                                       (CallStatus=completed)
08:48:30,291 INFO  [stdout] (http-/192.168.1.3:8080-4)                                       (CallDuration=null)
08:48:30,291 INFO  [stdout] (http-/192.168.1.3:8080-4)                                       (DialCallSid=null)
08:48:30,292 INFO  [stdout] (http-/192.168.1.3:8080-4)                                       (DialCallStatus=null)
08:48:30,293 INFO  [stdout] (http-/192.168.1.3:8080-4)                                       (DialCallDuration=null)
08:48:30,305 INFO  [stdout] (http-/192.168.1.3:8080-3) ------- Hanging Up
08:48:30,306 INFO  [stdout] (http-/192.168.1.3:8080-3)                                       (CallSid=CA1b07b62c37ea4ab89a6e98a83597545b)
08:48:30,306 INFO  [stdout] (http-/192.168.1.3:8080-3)                                       (CallStatus=completed)
08:48:30,306 INFO  [stdout] (http-/192.168.1.3:8080-3)                                       (CallDuration=null)
08:48:30,307 INFO  [stdout] (http-/192.168.1.3:8080-3)                                       (DialCallSid=null)
08:48:30,307 INFO  [stdout] (http-/192.168.1.3:8080-3)                                       (DialCallStatus=null)
08:48:30,307 INFO  [stdout] (http-/192.168.1.3:8080-3)                                       (DialCallDuration=0)
08:48:56,188 INFO  [stdout] (http-/192.168.1.3:8080-7) ------- Recording
08:48:56,189 INFO  [stdout] (http-/192.168.1.3:8080-7)                                       (CallSid=CA424771bf09dd429b80983a86726e7699)
08:48:56,189 INFO  [stdout] (http-/192.168.1.3:8080-7)                                       (CallStatus=ringing)
08:48:56,189 INFO  [stdout] (http-/192.168.1.3:8080-7)                                       (CallDuration=null)
08:48:56,190 INFO  [stdout] (http-/192.168.1.3:8080-7)                                       (DialCallSid=null)
08:48:56,190 INFO  [stdout] (http-/192.168.1.3:8080-7)                                       (DialCallStatus=null)
08:48:56,190 INFO  [stdout] (http-/192.168.1.3:8080-7)                                       (DialCallDuration=null)
08:49:08,787 INFO  [stdout] (http-/192.168.1.3:8080-2) ------- Hanging Up
08:49:08,787 INFO  [stdout] (http-/192.168.1.3:8080-2)                                       (CallSid=CA424771bf09dd429b80983a86726e7699)
08:49:08,787 INFO  [stdout] (http-/192.168.1.3:8080-2)                                       (CallStatus=completed)
08:49:08,788 INFO  [stdout] (http-/192.168.1.3:8080-2)                                       (CallDuration=null)
08:49:08,788 INFO  [stdout] (http-/192.168.1.3:8080-2)                                       (DialCallSid=null)
08:49:08,788 INFO  [stdout] (http-/192.168.1.3:8080-2)                                       (DialCallStatus=null)
08:49:08,788 INFO  [stdout] (http-/192.168.1.3:8080-2)                                       (DialCallDuration=null)
08:49:08,796 INFO  [stdout] (http-/192.168.1.3:8080-1) ------- Hanging Up
08:49:08,797 INFO  [stdout] (http-/192.168.1.3:8080-1)                                       (CallSid=CA424771bf09dd429b80983a86726e7699)
08:49:08,797 INFO  [stdout] (http-/192.168.1.3:8080-1)                                       (CallStatus=completed)
08:49:08,797 INFO  [stdout] (http-/192.168.1.3:8080-1)                                       (CallDuration=null)
08:49:08,797 INFO  [stdout] (http-/192.168.1.3:8080-1)                                       (DialCallSid=null)
08:49:08,797 INFO  [stdout] (http-/192.168.1.3:8080-1)                                       (DialCallStatus=null)
08:49:08,798 INFO  [stdout] (http-/192.168.1.3:8080-1)                                       (DialCallDuration=0)
***********************************************************************
[rc-record-action.zip](https://github.com/RestComm/RestComm-Core/files/123280/rc-record-action.zip)
Please find attached the war file that you need to test the status callback and record action URL.
Create a war file from the zip and 
You put this in the deployments folder and start Restcomm.
Then go to the http://RESTCOMM_IP:8080/rc-record-action
Follow the instruction on that page.

**Comment by croufay** [comment]
This is the result from the latest binary


[croufay@localhost restcomm]$ tail -f ../../standalone/log/server.log | grep stdout
21:21:55,991 INFO  [stdout] (http-/192.168.1.3:8080-10) --------------------- Status=ringing
21:21:55,992 INFO  [stdout] (http-/192.168.1.3:8080-10)                                       (CallSid=CA2601266415494fefb6342a4d9d7e967c)
21:21:55,992 INFO  [stdout] (http-/192.168.1.3:8080-10)                                       (CallStatus=ringing)
21:21:55,992 INFO  [stdout] (http-/192.168.1.3:8080-10)                                       (CallDuration=null)
21:21:55,992 INFO  [stdout] (http-/192.168.1.3:8080-10)                                       (DialCallSid=null)
21:21:55,993 INFO  [stdout] (http-/192.168.1.3:8080-10)                                       (DialCallStatus=null)
21:21:55,993 INFO  [stdout] (http-/192.168.1.3:8080-10)                                       (DialCallDuration=null)
21:21:56,000 INFO  [stdout] (http-/192.168.1.3:8080-6) ------- Recording
21:21:56,000 INFO  [stdout] (http-/192.168.1.3:8080-6)                                       (CallSid=CA2601266415494fefb6342a4d9d7e967c)
21:21:56,001 INFO  [stdout] (http-/192.168.1.3:8080-6)                                       (CallStatus=ringing)
21:21:56,001 INFO  [stdout] (http-/192.168.1.3:8080-6)                                       (CallDuration=null)
21:21:56,002 INFO  [stdout] (http-/192.168.1.3:8080-6)                                       (DialCallSid=null)
21:21:56,002 INFO  [stdout] (http-/192.168.1.3:8080-6)                                       (DialCallStatus=null)
21:21:56,002 INFO  [stdout] (http-/192.168.1.3:8080-6)                                       (DialCallDuration=null)
21:21:56,106 INFO  [stdout] (http-/192.168.1.3:8080-1) --------------------- Status=in-progress
21:21:56,106 INFO  [stdout] (http-/192.168.1.3:8080-1)                                       (CallSid=CA2601266415494fefb6342a4d9d7e967c)
21:21:56,107 INFO  [stdout] (http-/192.168.1.3:8080-1)                                       (CallStatus=in-progress)
21:21:56,108 INFO  [stdout] (http-/192.168.1.3:8080-1)                                       (CallDuration=null)
21:21:56,109 INFO  [stdout] (http-/192.168.1.3:8080-1)                                       (DialCallSid=null)
21:21:56,109 INFO  [stdout] (http-/192.168.1.3:8080-1)                                       (DialCallStatus=null)
21:21:56,110 INFO  [stdout] (http-/192.168.1.3:8080-1)                                       (DialCallDuration=null)
21:22:05,391 INFO  [stdout] (http-/192.168.1.3:8080-3) --------------------- Status=completed
21:22:05,391 INFO  [stdout] (http-/192.168.1.3:8080-3)                                       (CallSid=CA2601266415494fefb6342a4d9d7e967c)
21:22:05,392 INFO  [stdout] (http-/192.168.1.3:8080-3)                                       (CallStatus=completed)
21:22:05,392 INFO  [stdout] (http-/192.168.1.3:8080-3)                                       (CallDuration=null)
21:22:05,392 INFO  [stdout] (http-/192.168.1.3:8080-3)                                       (DialCallSid=null)
21:22:05,392 INFO  [stdout] (http-/192.168.1.3:8080-3)                                       (DialCallStatus=null)
21:22:05,393 INFO  [stdout] (http-/192.168.1.3:8080-3)                                       (DialCallDuration=null)
21:22:05,419 INFO  [stdout] (http-/192.168.1.3:8080-11) ------- Hanging Up
21:22:05,420 INFO  [stdout] (http-/192.168.1.3:8080-11)                                       (CallSid=CA2601266415494fefb6342a4d9d7e967c)
21:22:05,421 INFO  [stdout] (http-/192.168.1.3:8080-11)                                       (CallStatus=completed)
21:22:05,421 INFO  [stdout] (http-/192.168.1.3:8080-11)                                       (CallDuration=null)
21:22:05,421 INFO  [stdout] (http-/192.168.1.3:8080-11)                                       (DialCallSid=null)
21:22:05,421 INFO  [stdout] (http-/192.168.1.3:8080-11)                                       (DialCallStatus=null)
21:22:05,421 INFO  [stdout] (http-/192.168.1.3:8080-11)                                       (DialCallDuration=null)
21:22:05,430 INFO  [stdout] (http-/192.168.1.3:8080-7) ------- Hanging Up
21:22:05,431 INFO  [stdout] (http-/192.168.1.3:8080-7)                                       (CallSid=CA2601266415494fefb6342a4d9d7e967c)
21:22:05,431 INFO  [stdout] (http-/192.168.1.3:8080-7)                                       (CallStatus=completed)
21:22:05,431 INFO  [stdout] (http-/192.168.1.3:8080-7)                                       (CallDuration=null)
21:22:05,431 INFO  [stdout] (http-/192.168.1.3:8080-7)                                       (DialCallSid=null)
21:22:05,432 INFO  [stdout] (http-/192.168.1.3:8080-7)                                       (DialCallStatus=null)
21:22:05,432 INFO  [stdout] (http-/192.168.1.3:8080-7)                                       (DialCallDuration=0)
21:22:05,438 INFO  [stdout] (http-/192.168.1.3:8080-13) --------------------- Status=completed
21:22:05,439 INFO  [stdout] (http-/192.168.1.3:8080-13)                                       (CallSid=CA2601266415494fefb6342a4d9d7e967c)
21:22:05,439 INFO  [stdout] (http-/192.168.1.3:8080-13)                                       (CallStatus=completed)
21:22:05,439 INFO  [stdout] (http-/192.168.1.3:8080-13)                                       (CallDuration=null)
21:22:05,439 INFO  [stdout] (http-/192.168.1.3:8080-13)                                       (DialCallSid=null)
21:22:05,439 INFO  [stdout] (http-/192.168.1.3:8080-13)                                       (DialCallStatus=null)
21:22:05,440 INFO  [stdout] (http-/192.168.1.3:8080-13)                                       (DialCallDuration=null)

**Comment by croufay** [comment]
Please note that there are duplicate hanging up and completed.

This only happens when you hangup the phone after leaving a message. If you press the star "*" button after leaving a message you don't get duplicate  --------------------- Status=completed or duplicate ------ Hanging Up

**Comment by peteroyle** [comment]
Just noting here that I have confirmed @croufay's findings. When the caller presses * to end the call everything is fine, but if they simply hang up to end the call, both the action Url and the status callback are called twice.

**Comment by gvagenas** [comment]
Added test case for the issue which are failing before the patch according to the issue description.
- https://github.com/RestComm/Restcomm-Connect/blob/master/restcomm/restcomm.testsuite/src/test/java/org/mobicents/servlet/restcomm/telephony/TestDialVerbPartTwo.java#L608
- https://github.com/RestComm/Restcomm-Connect/blob/master/restcomm/restcomm.testsuite/src/test/java/org/mobicents/servlet/restcomm/telephony/TestDialVerbPartTwo.java#L683
