### ISSUE TITLE
Explicit oauth token creation from AdminUI - SSO

### ISSUE THREAD

**Issue by otsakir** [RestComm/Restcomm-Connect#881]
Althought Restcomm REST api works fine with oauth tokens, there is no workflow in the UI for a user to create such tokens. Apart from _inspecting element_ and sniffing it from the ajax requests.

Such a capability should be added to AdminUI, in the account details page. Such tokens typically have a long lifetime and they are referred to as _off-line tokens_ in keycloak jargon.

**UI Considerations**

Since both offline tokens and API Keys (former Restcomm accoundsid/password credentials) are only used for Restcomm REST api access they should be displayed in their respective section. Also, offline token option will only be available if the account is linked to a user.

Read more on offline tokens  here: http://keycloak.github.io/docs/userguide/keycloak-server/html/timeouts.html#offline-access

**Comment by otsakir** [comment]
The use case of offline tokens is to generate them once, store them somewhere and use them in the client applications for a long time. Here are some additional issues:

1. Where will these tokens be stored if at all ?
2. Functionality overlap with old-school *API keys* (stored in the Account and used with HTTP authentication) at business level. We have two kinds of tokens doing *almost* the same thing.
3. The difference is that *offline tokens* will grant access to all Restcomm applications (RVD too)  while API keys affect only Restcomm REST API.

Is this really needed or shall we stick to old-scoll *API keys* for accessing Restcomm rest api ?

**Comment by deruelle** [comment]
Can we stick to old-school API keys for accessing Restcomm rest api for the time being and potentially add later support for tokens if needed ?

**Comment by otsakir** [comment]
I remembered old discussions we had on that and wanted to keep some record for future reference. It's probably sth that will need.

Yes, let's stick to existing setup.

**Comment by otsakir** [comment]
Closing as 'wontfix'
