### ISSUE TITLE
RVD relies on having logged in AdminUI with same user in order to operate properly

### ISSUE THREAD

**Issue by otsakir** [RestComm/Restcomm-Connect#906]
When different users are logged in RVD and AdminUI, RVD cannot display (or access) applications.

RVD UI uses Restcomm Application API. It provides no explicit credentials while doing it though. It does that using the JSESSIONID cookie provived probably by Shiro. That seems to be the reason applications cannot be accessed.

The issue appeared after project migration patch when RVD started accessing directly the Application REST API.

**Comment by ghjansen** [comment]
Closed via 9a779998bf70f8c7def9abafb15214ca387cb5da

**Comment by otsakir** [comment]
Error notification disappears too quickly. We should increase the timeout.
