### ISSUE TITLE
Proxy-Authentication does not work if uri has uri-parameters

### ISSUE THREAD

**Issue by thaeger71** [RestComm/Restcomm-Connect#935]
If a client sends a REGISTER with parameters in request uri, for example:

test@192.168.1.1;transport=udp

Then this request uri will be included as uri field in the digest which comes from client, and then the authentication does not work on RestComm. It sends just 407 again and again ....

Tested with snom phone, just enter as registrar 192.168.1.1:5080;transport=tcp
The phone then try to register via tcp, and then you can watch this behaviour.
If you discharge this parameter, the phone will again try to register via udp and oh wonder, it works.

Btw, in case that authentication failed there a better messages for sure just as send another 407 which ends in an endless loop....

**Comment by thaeger71** [comment]
Sorry I forgot to menation the verion I'am using:

RestComm v7.6.0-SNAPSHOT

**Comment by deruelle** [comment]
Thanks @thaeger71 for opening the issue. Would you like to try contributing a patch for it ?

**Comment by thaeger71** [comment]
Hello Jean,

yes, I would like to try to contribute a patch.
I've already identified the issue, and I will try to provide a patch soon.

Greets,

Thomas.

2016-03-17 18:18 GMT+01:00 Jean Deruelle <notifications@github.com>:

> Thanks @thaeger71 <https://github.com/thaeger71> for opening the issue.
> Would you like to try contributing a patch for it ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/RestComm/Restcomm-Connect/issues/935#issuecomment-197982499>
>



-- 
********************************************
Dipl.- Ing. Thomas Häger
Wiesbadener Str. 4
12161 Berlin
Tel.:   +49 30 854 016 46
Mobile: +49 176 24250798
mailto:thaeger@hdsnetz.de
********************************************

**Comment by deruelle** [comment]
@thaeger71 Great ! Thanks !

You can follow the Dev Process section of our [open source playbook](https://docs.google.com/document/d/1RZz2nd2ivCK_rg1vKX9ansgNF6NpK_PZl81GxZ2MSnM/edit#heading=h.mcjitemt6ng1) for contributions

**Comment by thaeger71** [comment]
Hello Jean,

I really appriciate the openness with you invited me to contribute to this
repository, but I don't want to make something wrong.
Therefore I would like to ask you to apply my attached patch for several
fixes:

fixes for Issue #935: bug with uri-parameters in Digest, changed answer to
unsuccessful REGISTER to 403 FORBIDDEN, disabled keepalive (OPTIONS) even
for tcp sessions

Greets,

Thomas.

2016-03-18 9:34 GMT+01:00 Jean Deruelle <notifications@github.com>:

> Assigned #935 <https://github.com/RestComm/Restcomm-Connect/issues/935>
> to @thaeger71 <https://github.com/thaeger71>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/RestComm/Restcomm-Connect/issues/935#event-594551842>
>



-- 
********************************************
Dipl.- Ing. Thomas Häger
Wiesbadener Str. 4
12161 Berlin
Tel.:   +49 30 854 016 46
Mobile: +49 176 24250798
mailto:thaeger@hdsnetz.de
********************************************

**Comment by thaeger71** [comment]
Hi Jean,

I just want to ask you to wait with applying the patch...I found a similar
issue with the callhandler (CallControlHelper) .....

Thnx,
Thomas.

2016-03-18 13:44 GMT+01:00 Thomas Häger <thaeger@hdsnetz.de>:

> Hello Jean,
>
> I really appriciate the openness with you invited me to contribute to this
> repository, but I don't want to make something wrong.
> Therefore I would like to ask you to apply my attached patch for several
> fixes:
>
> fixes for Issue #935: bug with uri-parameters in Digest, changed answer to
> unsuccessful REGISTER to 403 FORBIDDEN, disabled keepalive (OPTIONS) even
> for tcp sessions
>
> Greets,
>
> Thomas.
>
> 2016-03-18 9:34 GMT+01:00 Jean Deruelle <notifications@github.com>:
>
>> Assigned #935 <https://github.com/RestComm/Restcomm-Connect/issues/935>
>> to @thaeger71 <https://github.com/thaeger71>.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/RestComm/Restcomm-Connect/issues/935#event-594551842>
>>
>
>
>
> --
> ********************************************
> Dipl.- Ing. Thomas Häger
> Wiesbadener Str. 4
> 12161 Berlin
> Tel.:   +49 30 854 016 46
> Mobile: +49 176 24250798
> mailto:thaeger@hdsnetz.de
> ********************************************
>



-- 
********************************************
Dipl.- Ing. Thomas Häger
Wiesbadener Str. 4
12161 Berlin
Tel.:   +49 30 854 016 46
Mobile: +49 176 24250798
mailto:thaeger@hdsnetz.de
********************************************

**Comment by thaeger71** [comment]
fyi: new patch attached

2016-03-18 14:44 GMT+01:00 Thomas Häger <thaeger@hdsnetz.de>:

> Hi Jean,
>
> I just want to ask you to wait with applying the patch...I found a similar
> issue with the callhandler (CallControlHelper) .....
>
> Thnx,
> Thomas.
>
> 2016-03-18 13:44 GMT+01:00 Thomas Häger <thaeger@hdsnetz.de>:
>
>> Hello Jean,
>>
>> I really appriciate the openness with you invited me to contribute to
>> this repository, but I don't want to make something wrong.
>> Therefore I would like to ask you to apply my attached patch for several
>> fixes:
>>
>> fixes for Issue #935: bug with uri-parameters in Digest, changed answer
>> to unsuccessful REGISTER to 403 FORBIDDEN, disabled keepalive (OPTIONS)
>> even for tcp sessions
>>
>> Greets,
>>
>> Thomas.
>>
>> 2016-03-18 9:34 GMT+01:00 Jean Deruelle <notifications@github.com>:
>>
>>> Assigned #935 <https://github.com/RestComm/Restcomm-Connect/issues/935>
>>> to @thaeger71 <https://github.com/thaeger71>.
>>>
>>> —
>>> You are receiving this because you were mentioned.
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/RestComm/Restcomm-Connect/issues/935#event-594551842>
>>>
>>
>>
>>
>> --
>> ********************************************
>> Dipl.- Ing. Thomas Häger
>> Wiesbadener Str. 4
>> 12161 Berlin
>> Tel.:   +49 30 854 016 46
>> Mobile: +49 176 24250798
>> mailto:thaeger@hdsnetz.de
>> ********************************************
>>
>
>
>
> --
> ********************************************
> Dipl.- Ing. Thomas Häger
> Wiesbadener Str. 4
> 12161 Berlin
> Tel.:   +49 30 854 016 46
> Mobile: +49 176 24250798
> mailto:thaeger@hdsnetz.de
> ********************************************
>



-- 
********************************************
Dipl.- Ing. Thomas Häger
Wiesbadener Str. 4
12161 Berlin
Tel.:   +49 30 854 016 46
Mobile: +49 176 24250798
mailto:thaeger@hdsnetz.de
********************************************

**Comment by deruelle** [comment]
@thaeger71 we don't accept patches as files but as Pull Request only (https://github.com/RestComm/Restcomm-Connect/pulls).  

You need to follow the [Pull Request section of our open source playbook](https://docs.google.com/document/d/1RZz2nd2ivCK_rg1vKX9ansgNF6NpK_PZl81GxZ2MSnM/edit#heading=h.vybjjnyzyp0)

**Comment by deruelle** [comment]
@thaeger71 just checking if there is anything blocking from your side in doing a formal github pull request  for that issue ?

**Comment by thaeger71** [comment]
Hello Jean,

nothing blocking, except work. I just was in vacation, today first day I'am back...and I have a lot of other things at the moment to do, so I will see when I'am able to do the patch....if you were able to commmit this in any way I would appriciate this. I promise I will deal with the paper you've sent.

Greets,

Thomas.

**Comment by deruelle** [comment]
@thaeger71 as mentioned in my earlier comments. Your patch file didn't make it to github so please add it again. What I sent is not really paper it's just a better way (and standard github way) to contribute the patch and make sure your name is attached to it as well.

**Comment by deruelle** [comment]
Merged in https://github.com/RestComm/Restcomm-Connect/pull/970

**Comment by gvagenas** [comment]
Patch merged to master. Thanks @thaeger71
