### ISSUE TITLE
RVD HTTP based authentication for raw-import does not work

### ISSUE THREAD

**Issue by otsakir** [RestComm/Restcomm-Connect#947]
Project raw-import method fails when basic auth credentials are used.

**Comment by deruelle** [comment]
@otsakir do we have an RVD API to upload an app either a new version of an existing application or create a new one. Similarly is there an API to remove an application ?

**Comment by otsakir** [comment]
Issue was fixed when the no noshiro patch (#1045) was applied. Further improvements in the HTTP interface done by last commit -  6a0ecdc
