### ISSUE TITLE
Move sipSession.invalidate() from Call to CallManager

### ISSUE THREAD

**Issue by gvagenas** [RestComm/Restcomm-Connect#950]
CallManger should invalidate sessions after received a final response to Bye request.
Move session invalidation from Call to CallManager.

CallManager should check if session is valid before start working on the session.

**Comment by gvagenas** [comment]
Call actor invalidates SipSession when call reaches state Failed and Completed.

Call moves to Completed state after Restcomm sends Bye to the client thus when client sends 200 OK for Bye, there is an exception because session is invalid

**Comment by deruelle** [comment]
Adding logs from latest perf run from @hrosa [restcomm-260l-30r-50000m.txt](https://github.com/RestComm/Restcomm-Connect/files/199096/restcomm-260l-30r-50000m.txt)
