### ISSUE TITLE
Add additional parameters to proxy.conf

### ISSUE THREAD

**Issue by knosach** [RestComm/Restcomm-Connect#955]
In case Restcomm is used with LB it patches the contact header for requests/responses.
IP address is changed correctly  , however Port is always set to 5060 even while LB is listening to different port on external IP.
Need to add additional parameter PROXY_PORT.
This parameter should be used for following script :
https://github.com/RestComm/Restcomm-Connect/pull/954

As soon as correct PORT is set in standalone-sip.xml , restcomm paches contact correctly

**Comment by deruelle** [comment]
@knosach did you do a Pull Request for that ?

**Comment by knosach** [comment]
No, I didn't do this

**Comment by deruelle** [comment]
ok please do as time permits

**Comment by gvagenas** [comment]
wont fix
