### ISSUE TITLE
Exception while trying to download RCML for new users

### ISSUE THREAD

**Issue by hamsterksu** [RestComm/Restcomm-Connect#960]
Hi,

in new version of restcomm i get error `SIP/2.0 503 Problem to setup services` with reason `"Exception while trying to download RCML"`. 
it happens for each user who is registered over web ui (menu numbers -> restcomm clients). for predefined users(`bob` and `alice`) everything is ok. 
reproduced for restcomm with embedded db and external maria db

in restcomm 7.5.0 everything is ok. 

**UPD**: 
i noticed only one difference between **bob** and my new user: **bob** has values for columns *voice_url* and *voice_method*
so i fixed my new user when apply sql update for **restcomm_clients** table with the following data `set voice_url=NULL, voice_method='POST'`

**UPD2**:
seems exception was thrown by https://github.com/RestComm/Restcomm-Connect/blob/master/restcomm/restcomm.http/src/main/java/org/mobicents/servlet/restcomm/http/client/Downloader.java

**reason** - https://github.com/RestComm/Restcomm-Connect/blob/master/restcomm/restcomm.http/src/main/java/org/mobicents/servlet/restcomm/http/client/Downloader.java#L176 

i have found this message in restcomm log
`22:50:18,644 INFO  [org.mobicents.servlet.restcomm.http.client.Downloader] (RestComm-akka.actor.default-dispatcher-30) Exception while trying to download RCML, exception: java.lang.IllegalArgumentException:  is not a supported downloader method.` 
but log level is **INFO**

**Comment by gvagenas** [comment]
@hamsterksu when this exception happens? When client registers, when it dials out or when Restcomm tries to call this client? 

Please provide logs.

Thanks

**Comment by hamsterksu** [comment]
hi @gvagenas 

Steps to reproduce:

1. add new user
2. use jitsy with this user 
3. make call to 1234 
4. call will failed
5. review logs on the server. you will find error

**Comment by gvagenas** [comment]
This issue is caused by the data the AdminUI sends but I will patch Restcomm side to add more validation in the data in order to make sure db schema is not violated .

**Comment by hamsterksu** [comment]
@gvagenas  "adminui" is the separate project?

**Comment by gvagenas** [comment]
Its the restcomm.ui module, an angular application
