### ISSUE TITLE
DB maintenance

### ISSUE THREAD

**Issue by gvagenas** [RestComm/Restcomm-Connect#961]
Define procedures for:
1. DB upgrade
2. DB backup/restore
3. DB scale
4. DB retention policy
5. DB cleanup

**Comment by deruelle** [comment]
Related document work in progress 
https://docs.google.com/document/d/1XwnU50tN-UKp0jUqO6aByyGn3AUv7ULq1UAtpJNTiKY/edit?usp=sharing

**Comment by deruelle** [comment]
Let's try to have the DB upgrade process ready for 7.6.0 milestone.

**Comment by gvagenas** [comment]
Tools to consider:
http://www.liquibase.org/documentation/changeset.html
https://flywaydb.org/
