### ISSUE TITLE
Use Guarded Logging

### ISSUE THREAD

**Issue by gvagenas** [RestComm/Restcomm-Connect#977]

**Comment by deruelle** [comment]
There is a lot of places like https://github.com/RestComm/Restcomm-Connect/blob/890e960ed103dc4855133597578bd38e16b1e610/restcomm/restcomm.interpreter/src/main/java/org/mobicents/servlet/restcomm/interpreter/VoiceInterpreter.java#L557 where the logging is not guarded. 

This is not good for performance. Instead the code should be guarded as in https://github.com/RestComm/Restcomm-Connect/blob/890e960ed103dc4855133597578bd38e16b1e610/restcomm/restcomm.interpreter/src/main/java/org/mobicents/servlet/restcomm/interpreter/VoiceInterpreter.java#L482

See https://wiki.base22.com/display/btg/Java+Logging+Standards+and+Guidelines . Section Use Guarded Logging is specially important for performance.

A full review of the code base should be made for all level types (except ERROR and WARN usually) and changed to guarded logging.

**Comment by zahidMed** [comment]
ok, It's ongoing..

**Comment by deruelle** [comment]
Thanks @zahidMed ! 
when you're done, don't forget to create a Pull Request so we can review.

**Comment by gvagenas** [comment]
Closed with PR #1016

**Comment by deruelle** [comment]
@zahidMed acknowledged at https://telestax.com/acknowledgements/ ! Thanks !
