### ISSUE TITLE
restcomm not sending SIP response to  source packet port

### ISSUE THREAD

**Issue by leftyb** [RestComm/Restcomm-Connect#978]
When using jitsi form some reason RestComm is not using the source packet port.
The jitsi INVITE comes from a port other than 5060

<img width="1440" alt="screen shot 2016-04-04 at 10 09 11 2" src="https://cloud.githubusercontent.com/assets/4802924/14251148/4716a31a-fa8a-11e5-976c-407c09f5f24e.png">

[nomediajitsi.tar.gz](https://github.com/RestComm/Restcomm-Connect/files/202611/nomediajitsi.tar.gz)

**Comment by deruelle** [comment]
Fixed in JAIN SIP
