### ISSUE TITLE
Pass dialed digits to Client application

### ISSUE THREAD

**Issue by deruelle** [RestComm/Restcomm-Connect#979]
jjs : Is Olympus capable of Dialing an external DID?

jean.deruelle : not by itself. it needs to go through a Restcomm app and restcomm media server as PSTN uses a different standard than WebRTC for media

jjs : Dumb question: if you start dialing a number in Olympus, there should be a "Central App" in Restcomm that should allow this to function

ivelin: I concur. It came up during a demo with a customer today.
It should be straightforward to call PSTN numbers for any Restcomm client.

@atsakiridis : thoughts?
@gvagenas : can provide input as well here
@gvagenas: is there a way to actually set a default application
for outgoing calls
or have a rule such as if the number called is not a registered restcomm DID number in the DB
nor a Restcomm Client
and outbound proxy is set
then use Dial Sip

**Comment by gvagenas** [comment]
@derulle Restcomm currently supports clients to dial out. For clients that wants to dial out Restcomm acts as a B2BUA, no media server here. 

For Olympus clients we need the client default application, so we force the call to go through the media server. One details that needs to be checked here is how to pass the dialled digits to the application

Also keep in mind that the default application is set on the client so if alice has a default application, Restcomm will execute this application if alice is using Olympus or Jitsi or whatever sip client.

**Comment by deruelle** [comment]
Is this one valid ?

**Comment by gvagenas** [comment]
@deruelle no, it is not valid.

Restcomm request to the application server (RVD) will include the dialed digits as parameter "To". RVD variable will be "$core_To".

For the WebRTC client to be able to dial out through the outbound proxy, we need CallManager to setup the call over RMS, this issue #1042
