### ISSUE TITLE
XMS drops the m=video section completely when answering an audio/video call but is configured without video codecs

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/Restcomm-Connect#983]
This breaks peer connection in the client side that always expects the same number of m-lines in the answer as it sent in the offer per specs and results in call failing.

I think it should reply with an m=video line with port 0 to negate it instead so that the answer is accepted.

**Comment by RomanDS** [comment]
We found an issue with Dialogic JSR 309 connector where when CodecPolicy feature is used to specify the call to be audio only we have been removing the entire m= video lines from the incoming SDP. This has been modified, verified, and will be available in our 5.2 SU1 Connector version.

**Comment by deruelle** [comment]
Thanks @RomanDS. Can we close this issue ?

**Comment by RomanDS** [comment]
Yes, I believe it has been verified by your team that the issue was resolved.
