### ISSUE TITLE
Investigate External Service call on RestComm side

### ISSUE THREAD

**Issue by ghjansen** [RestComm/Restcomm-Connect#984]
Currently, the RVD app that contains a ES (External Service) verb is executed in a sequence different than the sequence of verbs defined while designing this app on RVD.

The ES verb is executed by RVD before build the RCML of this app. After the HTTP response been processed by RVD, the RCML is finished and delivered to RestComm, where the sequence of verbs is interpreted.

The suggestion is to find a way to migrate to RestComm the RVD structure that executes the HTTP request configured on ES verb. Maybe creating a new RCML entry exclusive for ES, so RestComm can manage to execute this HTTP request in the appropriate time.

**Comment by deruelle** [comment]
I'm not sure having an ES Verb on Restcomm makes sense. We should instead use Redirect Verb within RVD RCML generation to ensure that the ES is executed at the right time in the sequence.

**Comment by otsakir** [comment]
I agree, moving ES to Restcomm is a bad idea. IMO, the idea behind RVD is to provide a high level interface to build complex constructs using a mininal but robust set of commands offered by Restcomm. For now it only speaks RCML but if we leverage the Restcomm REST API too a great deal of cool new features will possible. 

Why put that burden to restcomm ?

**Comment by ghjansen** [comment]
Thanks @deruelle and @otsakir , lets discard this option then.
@otsakir do you think we could close this issue and handle the sequence on which ES verb is executed using issue #985, that already deals with the sequence of modules?

**Comment by otsakir** [comment]
Closing the issue. See #985  and #317 for related improvements.
