### ISSUE TITLE
Support RVD Redirect element with module targets in addition to URLs

### ISSUE THREAD

**Issue by ghjansen** [RestComm/Restcomm-Connect#985]
RVD currently have some specific verbs that allow to change the app execution flow from one module to another. Investigate the possibility to integrate a flow control resource to each verb, if this actually fits into a good design strategy.

**Comment by otsakir** [comment]
Why not support two different types of redirections using the existing Redirect element? We could have *Url* and *Application module* types. 

There is also an open issue for creating a flow-control element that can break the execution of a module (inside RVD) and continue to the execution of another module. 

Btw, here is the rough algorithm that RVD uses to process a module:
```
process_module():
  rcmlResponse <-- ""
    for element IN allElements do:
      chainedElement = process(element, rcmlResponse) // this makes sense only for ES and Log
      rcmlResponse += render(element)
      if *chainedElement*:
        process_module(chainedElement, rcmlResponse)
  return rcmlResponse
```

Some important notes:
1. There are two types of elements. Those that produce RCML and those that are processed and do sth else like ES or Log element.
2. All elements are being processed/rendered in a sequential fashion.  
3. It could be possible to break the sequence of a module processing and chain to another module. That's what ES does. BUT, at all costs a single response of RCML would be returned.

**Comment by ghjansen** [comment]
I agree with the improvement on Redirect element. In fact this is way better than have this resource in each verb.
@otsakir I think the flow issue you mentioned is #317 right?

**Comment by otsakir** [comment]
yes @ghjansen. I would love to plan that for 7.7.0.

**Comment by otsakir** [comment]
This issue was moved to RestComm/visual-designer#47
